### ISSUE TITLE
Configure Spring Boot Actuators

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1000]
The code for this should be under the the [strongbox-web-core](https://github.com/strongbox/strongbox/tree/master/strongbox-web-core) module.

# Tasks:
* [ ] Configure Spring Boot Actuators
* [ ] Secure the Spring Boot Actuator end-points

# Useful links
* [Spring Boot: Actuators](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html)
* [Baeldung: Spring Boot Actuators](https://www.baeldung.com/spring-boot-actuators)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by SheikhHamza** [comment]
Hi @carlspring, 
I am new to opensource contributions and I would love to take this issue as an oppurtunity to get started. Is this issue still open? Is someone already working on it?

**Comment by carlspring** [comment]
Hi!

Feel free to give it a go and good luck! :)

**Comment by carlspring** [comment]
Also, feel free to join our [chat](https://chat.carlspring.org/) for more help.

**Comment by carlspring** [comment]
@SheikhHamza ,

Are you still looking into this? I'm asking, as @adavid9 is also interested in working on it.

**Comment by SheikhHamza** [comment]
Sure, @adavid9 can work on it.

**Comment by fuss86** [comment]
@adavid9 pick it, if you are on it, please 🌝
