### ISSUE TITLE
CronTaskController is unable to return list of tasks

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1001]
The `CronTaskController#getConfigurations` is unable to return the list of cron tasks - it returns `406 Could not find acceptable representation`. This is likely because of broken serialization to JSON. We need to create a test case which checks if the endpoint actually returns a valid response with at least one result inside. 

NOTE: The returned crontasks JSON should look like this:

```
{
   "crontasks": [
      {uuid: ...., name: ....., etc },
      {uuid: ...., name: ....., etc },
      ......
   ]
}
```

**Comment by steve-todorov** [comment]
@ptirador would you be interested in picking this one? :)

**Comment by ptirador** [comment]
Sure! I'll take it.
