### ISSUE TITLE
Saving group repositories does not preserve the order

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1003]
When you go to the UI and try to add a Group Repository, the order of the grouped repositories **MUST** be the way it's ordered - otherwise, this could lead to possible invalid `maven-metadata.xml` due to the way Strongbox would generate the metadata.

**Comment by ptirador** [comment]
Hi! Could you give me an example? Thanks!

**Comment by steve-todorov** [comment]
Yes, sure. Do a `mvn clean install` and then `mvn clean spring-boot:run`. Then:

1. Go to `http://localhost:48080/admin/storages/storage-common-proxies/group-common-proxies/update`
2. Reorder the repositories in the `Group repositories` tab
3. Save (and remember the ordering you did)
4. `cat strongbox-web-core/strongbox/etc/conf/strongbox.xml | grep -i -A 8 'id="group-common-proxies"'` - result will be the old order. 

I just noticed that if you create a new group repository - it preserves the correct order. However, if you're updating an existing one - it would not update the order of the repos in the xml.
