### ISSUE TITLE
Add checksums to `ArtifactEntry`

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1005]
# Task Description

When the artifact is physically stored (see [here](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/ArtifactManagementService.java#L167)) we save its metadata in the [ArtifactEntry](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/domain/ArtifactEntry.java) `@Entity` in the orientDb database [here](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/io/RepositoryStreamSupport.java#L163). If the artifact is not a checksum file, we have its checksums calculated during file streaming (see [here](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/ArtifactManagementService.java#L193)). We should store this map in the  [ArtifactEntry](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/domain/ArtifactEntry.java) `@Entity` to be able to search the database by the checksum algorithm and value.

In order to modify the database schema liquibase changeset should be provided in the [strongbox-db](https://github.com/strongbox/strongbox-db/tree/master/strongbox-db-liquibase/src/main/resources/db/changelog/v1.0.0) project.

# Acceptance Test

* [ ] Building the code and running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by Forbob** [comment]
@fuss86 @carlspring may i be assigned to this issue?

**Comment by carlspring** [comment]
@Forbob ,

Are you still interested in this task?

**Comment by ogryniuk** [comment]
Hi @carlspring ,

This issue interests me and I would much appreciate if you could assign it to me.

**Comment by carlspring** [comment]
@ogryniuk ,

Please, feel free to proceed with this task!
