### ISSUE TITLE
Add script generation for MacOS for the strongbox-distribution

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1008]
# Task Description

We need to enable the generation of shell scripts for MacOS in the `strongbox-distribution`.

Have a look at the [appassembler plugin](https://github.com/strongbox/strongbox/blob/master/strongbox-distribution/pom.xml#L179).

In theory, the work has already been done, but has never been tested under MacOS.

# Hints:

* https://github.com/strongbox/strongbox/blob/master/strongbox-distribution/pom.xml#L276
* https://github.com/strongbox/strongbox/blob/master/strongbox-distribution/src/main/assembly/distribution.xml#L45

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by cbrianhill** [comment]
I tested creating the distribution on MacOS, and found the following to work:
- `mvn install` succeeds.
- The resulting archives (zip and tar) work on MacOS and on Linux for installing and running strongbox.
I'll work on documenting some install procedures for MacOS.

**Comment by carlspring** [comment]
Excellent news! Thanks for the update! :)

**Comment by carlspring** [comment]
Thanks for your help!
