### ISSUE TITLE
Implement controller support for search by fully-qualified class name (fqcn) in Maven repositories

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1011]
## Task description:
In the `strongbox-web-core` module, in the [MavenArtifactController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/maven/MavenArtifactController.java) we need to add additional method to search for maven artifacts by fully-qualified class name (`FQCN`). We should return a collection of DTOs based on [ArtifactEntry](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/domain/ArtifactEntry.java) entity.

## Background
We use [listArchiveFilenames](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/Maven2LayoutProvider.java#L301) method to [store](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/support/ArtifactStoredEventListener.java#L89) the file names (included in the `jar`/`war`/`ear`) in the orientDb database (in the [ArtifactEntry](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/domain/ArtifactEntry.java#L42)). Proper [service](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceImpl.java) method will need to be implemented too, to search by the requested criteria.

**Comment by sbespalov** [comment]
Currently we use only AQL to search artifacts on UI, so probably we don't need any extra endpoints for this.

We should think how to add layout specific Class Name search support in AQL.

**Comment by carlspring** [comment]
Could you please give us links to the classes involved?

**Comment by sbespalov** [comment]
> Could you please give us links to the classes involved?

it probably should be done with `AQL.g4`, but first we need to decide how it should look like in terms of grammar

**Comment by carlspring** [comment]
@sbespalov / @anki2189 ,

Would this be a follow-up of #1752 , or should we close it?

**Comment by steve-todorov** [comment]
I vote we close it. I've also added a relation in #1678 and we can decide on how to achieve this at a later stage or as a follow-up to #1678.

**Comment by sbespalov** [comment]
I agree with @steve-todorov

**Comment by steve-todorov** [comment]
Closing this :)
