### ISSUE TITLE
Remove the jetty-maven-plugin configurations and the associated profiles from the pom.xml files

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1028]
# Task Description

As we've moved to Spring Boot and we can run it in the `strongbox-web-core`, as well as in the `strongbox-distribution`, we can now safely remove the need for the `jetty-maven-plugin` configurations and the related Maven profiles from the `pom.xml` files.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by efedchen** [comment]
I would like to give it a try

**Comment by carlspring** [comment]
Hi,

I'm afraid this task was just implemented last night by @yupitsleen. Would you like to pick a different task, or join our [chat](htrps://chat.carlspring.org/]?

**Comment by carlspring** [comment]
Ah! I seem to have created a duplicate task (#1033)! My apologies!

**Comment by yupitsleen** [comment]
Almost done
