### ISSUE TITLE
Remove the jetty-maven-plugin configurations from the pom.xml files

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1033]
# Task Description

As we've migrated to Spring Boot, we will now have to perform a clean up of the `pom.xml` files. Most-likely, this will only involve the `strongbox-web-core`.

**Tasks**
* [ ] Drop the Maven profiles that contain the invocations of the `jetty-maven-plugin`.
* [ ] Drop all the profile that are providing variables for the `jetty-maven-plugin`.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by yupitsleen** [comment]
I'm going to work on this.

**Comment by carlspring** [comment]
Hi!

Great, thanks!

**Comment by carlspring** [comment]
Feel free to join our [chat](https://chat.carlspring.org/) for more details and help.

**Comment by yupitsleen** [comment]
Thanks!
