### ISSUE TITLE
Use the Spring Boot Actuator logger management instead of our own solution

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1046]
# Task Description

After we integrate with Spring Boot Actuators (#1000), we should migrate our logging management to `spring-boot` (see https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#loggers). We will drop `LoggingManagementController` and we need to update `LoggingManagementControllerTestIT` (also rename it) to test that are actuator config works fine in terms of loggers. We should also drop:

```
<dependency>
    <groupId>org.carlspring.logging</groupId>
    <artifactId>logback-configuration-rest</artifactId>
</dependency>
```

from project dependencies.

# Tasks
* Check which of the following methods have analogues in the Spring Boot Logging Actuator (and list them):
  * [x] `addLogger`
  * [x] `updateLogger`
  * [x] `deleteLogger`
  * [ ] `downloadLog`
  * [x] `liveLogStreaming`
  * [ ] `generateLogDirectoryListing`
* [ ] Re-work the controller so that it extends the Spring Boot Logging Actuator with the features that it doesn't have (that we need).
* [ ] Consider contributing the improved logging actuator to the Spring Boot project.

# Useful Links

* [Spring Boot: HOWTO Logging](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html)
* [Spring Boot Actuators: Loggers](https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#loggers)
* [Spring Boot: Configure Log Level](https://blog.codeleak.pl/2017/03/spring-boot-configure-log-level-in.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
@adavid9 ,

If you're interested in following up on the Spring Boot Actuators, perhaps this task would also be of interest to you...?

**Comment by adavid9** [comment]
Sure I will take this one 😃
