### ISSUE TITLE
Add Strongbox related information in the EnvironmentInfoController

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1055]
We need to add the following Strongbox related information into the `EnvironmentInfoController`:

1. `storages` - the total count of storages in Strongbox
2. `repositories` - the total count of repositories in Strongbox
3. `users` - the total count of users in Strongbox.

This should be done in the `getEnvironmentInfo` method as an additional:
```
propertiesMap.put("strongbox", getStrongboxInfo());
```

**Comment by adavid9** [comment]
@steve-todorov I can work on that one :)

**Comment by steve-todorov** [comment]
Sure, pick it up! :)
