### ISSUE TITLE
Update the project structure in the wiki

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1058]
The project structure in the [wiki](https://github.com/strongbox/strongbox-docs/blob/master/docs/developer-guide/project-structure.md) has become out-of-date and we need to update it. (Please, note that the actual changes are in a different project on Github).

* [x] Remove all modules that no longer exist.
* [x] Update any modules have been renamed.
* [x] Add a line, or two for each module (unless it's an aggregator (a project that only contains sub-modules)).
* [x] The [`strongbox-parent`](https://github.com/strongbox/strongbox-parent) is now a separate project. Please, add it to the list!
* [x] The [`strongbox-db`](https://github.com/strongbox/strongbox-db/) is a separate project. Please, add it to the list!

**Comment by ShumailAhmed123** [comment]
Hi, 

Can I help to do this but I will need your help because I don't know about the full project. 

thanks

**Comment by carlspring** [comment]
Hi @ShumailAhmed123 ,

Thanks for offering to help! Have a look at the modules that are listed and check if they exist under the [`strongbox`](https://github.com/strongbox/strongbox/) project. If they don't then just remove them from the wiki page. Update the page with the new ones and so on.

If you have questions about any of the modules, just ask here, or feel free to join our [chat](https://chat.carlspring.org/).

**Comment by ShumailAhmed123** [comment]
okay, sure. 

Thank You

**Comment by ShumailAhmed123** [comment]
It will be done by tomorrow fully. 
Thanks

**Comment by carlspring** [comment]
Great! Thank you! :)

**Comment by ShumailAhmed123** [comment]
Hi, 

I have fork the project and updated the file but I am having some issues. I am not able to make a hyperlink in the module name as you have made in old files. 

here is the link can you please have a look at this, 

https://github.com/ShumailAhmed123/strongbox-docs/blob/master/docs/developer-guide/project-structure.md

**Comment by carlspring** [comment]
@ShumailAhmed123 ,

Just use markdown links like this:

```
[strongbox-aql](https://github.com/strongbox/strongbox/tree/master/strongbox-aql)
```

**Comment by ShumailAhmed123** [comment]
oh! thank You

**Comment by steve-todorov** [comment]
In addition to @carlspring 's comment - it is usually better to use reference links:
```
My ultra cool sentence which uses [strongbox-aql] inside and can be used as many times as [strongbox-aql] is needed.

(somewhere at the bottom of the page)
[strongbox-aql]: https://github.com/strongbox/strongbox/tree/master/strongbox-aql
```

This makes it easier to read the sentence and in case you are using the same link multiple times, you can easily replace it when necessary.

**Comment by ShumailAhmed123** [comment]
Hi, 

I have updated the wiki page. Please have a look at it and give your feedback on this. 

Thanks

**Comment by carlspring** [comment]
Hi,

Could you please create a pull request for this?

Thanks! :)

**Comment by ShumailAhmed123** [comment]
Hi, 

I did it. 

Thanks
