### ISSUE TITLE
Drop the org.apache.tomcat:catalina:6.0.53 dependency from the strongbox-event-api

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1059]
# Task Description

Drop the `org.apache.tomcat:catalina:6.0.53` dependency from the `strongbox-event-api` and apply any necessary changes to the code. This dependency should no longer be required, as we implemented this with Spring instead.

Affected classes:
- [ ] `EventExecutorFactoryBean`

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by adavid9** [comment]
I can work on that issue.

**Comment by carlspring** [comment]
@sbespalov , @fuss86 ,

Could you please review the description and add any hints that might be useful? @adavid9 will be looking into this and he could use the advice.

Thanks! :)
