### ISSUE TITLE
Make the *ArtifactControllerTests not print the contents of artifacts to the console

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1062]
# Task Description

The `*ArtifactControllerTest`-s are printing out the contents of artifacts to the console. This causes:
- Windows consoles to break
- IntelliJ terminals (under Windows) to break
- An awful lot of unnecessary and human-unintelligible output in the console

We need to silence this output when the tests below are executed.

Affected tests:
- [ ] `MavenArtifactControllerTest`
- [ ] `NpmArtifactControllerTest`
- [ ] `NugetArtifactControllerTest`
- [ ] `RawArtifactControllerTest`

The problem here may lie in the restassured dependency. Maybe we could upgrade to a newer version of it (the latest currently being `3.3.0`) and perhaps we can control it somehow through there. This needs to be investigated and fixed. We might have to create a fix for the restassured project itself and contribute it back to them.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by pgmpofu** [comment]
@carlspring @sbespalov @fuss86 may I work on this?

**Comment by carlspring** [comment]
@pgmpofu ,

Please, feel free to pick up this task! It would be of great help! Also, please feel free to join our [chat](https://chat.carlspring.org/) for more help! :)

**Comment by pgmpofu** [comment]
I am no longer working on this. Anyone may take over. Thanks

**Comment by carlspring** [comment]
Thanks for confirming!

**Comment by mujahid** [comment]
It seems the method `peek()` in `RestAssuredResponseOptionsImpl` is printing the response.

**Comment by carlspring** [comment]
Great! Would you mind submitting a pull request for this? We'd really appreciate the help!

Also, please feel free to join [our chat](https://chat.carlspring.org/).

**Comment by mujahid** [comment]
> Great! Would you mind submitting a pull request for this? We'd really appreciate the help!

I'll submit a pull request

**Comment by mujahid** [comment]
@carlspring

-  `NugetArtifactControllerTest`
-  `RawArtifactControllerTest`
