### ISSUE TITLE
Expose versioning information using Spring Boot Actuator

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1071]
# Task Description

We need to expose our versioning information using Spring Boot Actuators.

In Maven we have the following properties in place:
* `${project.version}` – a built-in Maven property, that shows what the version of the artifact that is being produced is.
* `${strongbox.revision}` – a property, exposd via the `org.codehaus.mojo:buildnumber-maven-plugin` that could be used to get the exact git revision.

These values could be replaced using Maven resource filtering of the `application.properties`.

# Tasks

* [x] Do properties replacement using Maven resource filtering against the `application.properties.
* [x] Expose the versioning information via Spring Boot Actuators.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by adavid9** [comment]
I can work on this one ;)
