### ISSUE TITLE
Enable metrics, scheduledtasks, shutdown, threaddump and Spring Boot Actuators

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1072]
# Task Description

We need the following Spring Boot Actuators to be enabled:
* `metrics`
* `scheduledtasks`
* `shutdown`
* `threaddump`

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by sbespalov** [comment]
@carlspring we don't use HTTP `sessions` on our backend, so we probably don't need this.

**Comment by adavid9** [comment]
@carlspring consider that what @sbespalov if you will decide that we thought add them I could do it, `metrics` is already enabled.

**Comment by carlspring** [comment]
@sbespalov ,

Thanks for clarifying! :)

**Comment by steve-todorov** [comment]
Out of curiosity, is there an `restart` endpoint which can be enabled? This could be very handy in the near future.

**Comment by fuss86** [comment]
As far as I see, there is a [shutdown](https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#shutdown) "native" method, but I think _restart_ can be implemented too, by hand :)

**Comment by adavid9** [comment]
@fuss86 @steve-todorov @sbespalov How do you think, should we implement other actuators or this task should be closed?

**Comment by steve-todorov** [comment]
I think you've missed to add `scheduledtasks, shutdown, threaddump` in your PR. But other than that - I don't know. If the restart works, then we can close it (I haven't had time to check it out). :)

**Comment by fuss86** [comment]
I think we can enable https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#caches too but it can be done in the follow up task :)

**Comment by steve-todorov** [comment]
Yeah, we can open up a new task for this :)
