### ISSUE TITLE
Implement a custom annotation for the creation of test repositories

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1083]
# Task Description

We need to implement a custom annotation that will handle the generation and clean up of test repositories. Each test case (and method) should create its own isolated test resources and not share them with other tests. This way, tests can safely be executed in parallel.

## Current Implementation

Excerpt from `MavenArtifactControllerTest.init()`, (the same kind of examples could be seen across the tests for all providers):
```
MutableRepository repository1 = mavenRepositoryFactory.createRepository(REPOSITORY_ID);
repository1.setPolicy(RepositoryPolicyEnum.RELEASE.getPolicy());
repository1.setRepositoryConfiguration(mavenRepositoryConfiguration);

createRepository(STORAGE0, repository1);
```

## Desired implementation

We need to implement a custom `@TestRepositories` annotation like below:
```
@TestRepositories({ @TestRepository(layout=MavenLayoutProvider.ALIAS,
                                    storage = "storage0",
                                    repository="test-releases",
                                    // This should be the default,
                                    // in order to guarantee test resource isolation:
                                    ignoreIfExists = false,
                                    // This should be the default value:
                                    createStorageIfNeeded = false
                                    // This should be the default value:
                                    removeRepositoryBeforeExection = true ) })
```

The `@TestRepositories` annotation should accept an array of `@TestRepository` and should thus be able to handle the generation of multiple repositories.

# Task Links

This task is:
* Required for #949.
* Similar to #1084.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by spasbelev** [comment]
Planning to have a look at this issue
