### ISSUE TITLE
Implement a custom annotation for the generation and clean up of test artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1084]
# Task Description

We need to implement a set of custom annotations that will handle the generation and clean up of test artifacts. Each test case (and method) should create its own isolated test resources and not share them with other tests. This way, tests can safely be executed in parallel.

## Current Implementation

Excerpt from `MavenArtifactControllerTest.init()`, (the same kind of examples could be seen across the tests for all providers):
```
MutableRepository repository1 = mavenRepositoryFactory.createRepository(REPOSITORY_RELEASES1);
repository1.setPolicy(RepositoryPolicyEnum.RELEASE.getPolicy());
repository1.setRepositoryConfiguration(mavenRepositoryConfiguration);

createRepository(STORAGE0, repository1);

// Generate releases
// Used by testPartialFetch():
generateArtifact(getRepositoryBasedir(STORAGE0, REPOSITORY_RELEASES1).getAbsolutePath(),
                 "org.carlspring.strongbox.partial:partial-foo",
                 new String[]{ "3.1",
                               // Used by testPartialFetch()
                               "3.2"
                               // Used by testPartialFetch()
                 }
);
```

## Desired implementation

We need to implement a custom `@TestArtifacts` annotation like below:
```
@TestArtifacts({ @TestArtifact(generator=MavenArtifactGenerator.class,
                               storage = "storage0",
                               repository="releases",
                               path="path/to/artifact.jar")
})
```

Obviously, the example above is quite generic (and abstract). For convenience, this should be a base annotation and there should be sub-implementations for the different layout providers such as:
- [ ] `MavenTestArtifact`
- [ ] `NpmTestArtifact`
- [ ] `NugetTestArtifact`
- [ ] `RawTestArtifact`

The `TestArtifacts` annotation should accept an array of these sub-implementations and should be able to handle the generation and clean up of multiple artifacts.

This annotation will generate aritfacts before test execution and clean them up from the FS and DB after execution. This way we won't need to manage artifacts with any code in test or setup, or tear down methods.

# Task Links

This task is:
* Required for #947, #948, #949, #950.
* Similar to #1083.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by denizseaside82** [comment]
Any possibility to help you with this one or another one? That would be my first experience and I am open to discuss in which areas I might be helpful to you.

**Comment by carlspring** [comment]
Hi @denizseaside82 ,

Thanks for offering to help, but we were just discussing this with @sbespalov earlier today and, given that he's already implemented #1083 in #1105 , he will look into this task as well.

Would you like to join our [chat](https://chat.carlspring.org/)? We could discuss some tasks there, if you like.

**Comment by denizseaside82** [comment]
Great! Is there any exact time which you all gather and discuss issues in your chat?

**Comment by carlspring** [comment]
There's always someone around.
