### ISSUE TITLE
Update the "Getting Started With Persistence" page to have a section on OrientDB Studio

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1087]
# Task Description

We need to update the wiki with some explanations on how to get the OrientDB enabled for development and debugging.

# Tasks

* [ ] Check the OrientDB properties on the [Application Properties](https://strongbox.github.io/user-guide/application-properties.html) page and the [Getting Started With Persistence](https://strongbox.github.io/developer-guide/getting-started-with-persistence.html) page with a section on how to enable Orient DB Studio.
* [ ] Add some screenshots to the page.

# Task Relationships

This task:
* Relates to: #991, #1026, #713, #715.

# Useful Links

* [Strongbox Docs README](https://github.com/strongbox/strongbox-docs)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by Ade400** [comment]
Hi, 
 I have looked at your label and seen you want someone to contribute to the documentation. I am a beginner and would like to contribute to the documentation. Please let me know if I can be of any help.

**Comment by carlspring** [comment]
Hi @Ade400 ,

Would you like to take this task?

**Comment by Ade400** [comment]
Hi carlspring, 
Please I would love to. Please if you can kindly direct me how you want the documentation done since I am a newbie it would be very much appreciated.  Thanks ever so much for getting in touch and will be looking forward for your directions and guidance.

**Comment by carlspring** [comment]
@Ade400 ,

Have a look at strongbox/strongbox-docs and feel free to join our 
[chat channel](https://chat.carlspring.org/).

**Comment by atutko2** [comment]
I would like to contribute to this. Would you please assign me this issue?

**Comment by carlspring** [comment]
@atutko2 ,

Please, feel free to pick this up and join our 
[chat channel](https://chat.carlspring.org/).

**Comment by carlspring** [comment]
Thanks for your help, @cbrianhill! :)
