### ISSUE TITLE
Document default url and credentials for strongbox UI

### ISSUE THREAD

**Issue by kalski** [strongbox/strongbox#1094]
# Task Description

There is a very nice section for `User Interface` in the `User Guide` [here](https://strongbox.github.io/). We should add a section, or perhaps a new page on what the default URL and built-in users are.

The documentation is handled via the [`strongbox-docs`](https://github.com/strongbox/strongbox-docs) project.

The default usernames are:
* `admin:password`
* `deployer:password`

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by evrimnurcelik** [comment]
I can start working on this, after #1138 is merged, Is that ok?

**Comment by carlspring** [comment]
Yes, please! :)
