### ISSUE TITLE
Cleanup the pom.xml files from dependency exclusions and extract them to the strongbox-parent

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1096]
# Task Description

We have `pom.xml` files that have `<exclusions>`. These will have to be migrated to the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent/), where this makes sense.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by divyad1508** [comment]
Hi @carlspring ,

As per our discussion, I'll be taking up this task.

**Comment by carlspring** [comment]
Great! Thanks for looking into this! :)

**Comment by divyad1508** [comment]
I have commited the changes & raised pull requests in both springbox-parent & springbox. Following are the URL for the same.

[](https://github.com/strongbox/strongbox-parent/pull/9)

[](https://github.com/strongbox/strongbox/pull/1103)

Thanks!

**Comment by LeifBrooks** [comment]
I can take this task

**Comment by carlspring** [comment]
Okay @LeifBrooks !

**Comment by LeifBrooks** [comment]
Blocked by #1130

**Comment by carlspring** [comment]
Thanks for carrying out this clean up, @LeifBrooks! :)
