### ISSUE TITLE
Investigate non-deterministic NullPointerException at MavenIndexerSearchProviderTest.setUp(MavenIndexerSearchProviderTest.java:75)

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1097]
# Task Description

During Jenkins build we encountered 

```
[2019-03-07T01:40:39.162Z] [ERROR] Errors: 
[2019-03-07T01:40:39.162Z] [ERROR]   MavenIndexerSearchProviderTest.setUp:75->TestCaseWithMavenArtifactGenerationAndIndexing.createRepositoryWithArtifacts:127->TestCaseWithMavenArtifactGenerationAndIndexing.createRepositoryWithArtifacts:138->TestCaseWithMavenArtifactGenerationAndIndexing.generateArtifactsReIndexAndPack:255 ? NullPointer
02:40:39  [INFO] 
[2019-03-07T01:40:39.162Z] [ERROR] Tests run: 116, Failures: 0, Errors: 1, Skipped: 0
02:40:39  [INFO] 
[2019-03-07T01:40:39.162Z] [ERROR] There are test failures.
```

This problem is non-deterministic, most often non-reproducible.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carloshpb** [comment]
Can I try? I never did any contribution to any project at Github before, but I want to try this one,

**Comment by carlspring** [comment]
Hi Carlos,
Thanks for offering to help! Please, feel free to pick up this task!

**Comment by carlspring** [comment]
Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

**Comment by carloshpb** [comment]
Was it tested using the same procedures from the building guide? With or without the Docker?

**Comment by carlspring** [comment]
It was tested with:
```
mvn clean install -Dintegration.tests
```

And, yes, it does occur under Docker. You can try it with `strongboxci/alpine:jdk8-mvn-3.5`, if you like. Check [here](https://strongbox.github.io/developer-guide/building-the-code-with-docker.html) for more details.

**Comment by ptirador** [comment]
@carlspring : Now that this class has been migrated in PR #1370  to use new annotations in order to create repositories and artifacts (the method `setUp` was even deleted )... Should this be considered as solved?

**Comment by carlspring** [comment]
@ptirador / @fuss86 : I will close this, because now all the Maven tests have been migrated to the new annotations and this should no long be an issue. I don't think we've hit this issue lately, either.

@ptirador : Thanks for following up on this! :)
