### ISSUE TITLE
Investigate random test failures with ArtifactDirectoryLocatorTest

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1099]
# Task Description

We are getting the following randomly occurring test failure:

```
Building / testLocateDirectories – org.carlspring.strongbox.artifact.locator.ArtifactDirectoryLocatorTest
<1s
Error
expected: <true> but was: <false>
Stacktrace
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
at org.carlspring.strongbox.artifact.locator.ArtifactDirectoryLocatorTest.testLocateDirectories(ArtifactDirectoryLocatorTest.java:142)
```

We need to investigate and fix this.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by LeifBrooks** [comment]
@carlspring It looks like there might be an issue with the concurrent execution. When I change the execution parameter to @Execution(SAME_THREAD), it starts passing consistently.

**Comment by carlspring** [comment]
Hi @LeifBrooks ,

Then perhaps we need to run this test with `@Execution(SAME_THREAD)`. Would you like to create a pull request for this?

**Comment by LeifBrooks** [comment]
@carlspring Will do
