### ISSUE TITLE
Add instructions on how to build the code under Windows 7 and 10 in regards to long paths

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1100]
# Task Description

Building the code under Windows 7 and 10 causes similar errors to occur:

```
E:\strongbox>git diff strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/BaseLocalStorageProxyRepositoryExpiredArtifactsCleanerTest.java: Filename too long
strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/RetryDownloadArtifactWithPermanentFailureStartingAtSomePointTest.java: Filename too long
```

There are workarounds for Windows that could be used and we need to add instructions to our [wiki](strongbox.github.io) on how to do this.

Please, note that the documentation pages are located under the [strongbox-docs)(https://github.com/strongbox/strongbox-docs) project.

# Useful Links
  
* [Windows Maximum Path Length Limitation](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86
* Reporters:
  * @kalski

**Comment by msarfrazanwar** [comment]
I will do this. Do we know the solution to the problem ? and whats the format for the file?

**Comment by carlspring** [comment]
Hi @msarfrazanwar ,

Welcome to our project! I would recommend you join our [chat](https://chat.carlspring.org/).

As most of us are using Linux and aren't hitting any such issues, it would be great, if someone who has Windows could look into this and document the workarounds. Which version of Windows for you have?

**Comment by msarfrazanwar** [comment]
I am using windows 10. I will join the chat and then see where can I help.

**Comment by steve-todorov** [comment]
Hi @msarfrazanwar,

Thanks for your interest in our project and volunteering for this ticket! Our docs can be found at [strongbox/strongbox-docs](https://github.com/strongbox/strongbox-docs/blob/master/docs/developer-guide/building-the-code.md). The link is pointing to the specific page where these instructions should be located :)  

This should be added in the `Common Build problems` section with an error message from windows and possible solution(s) based on the windows version.

Shortly after creating a PR, `netlify` will deploy a live preview of the docs with your changes so you can use that if your dev environment does not have the necessary tools to run mkdocs.

**Comment by carlspring** [comment]
This issue is still open for testing under Windows 7.

@kalski : Would you like to try it out?

**Comment by kalski** [comment]
@carlspring I checked the changed docs and `git clone` before / after applying the setting - docs are fine, setting fixes the problem which I also reproduce.

**Comment by steve-todorov** [comment]
@kalski and @msarfrazanwar - thank you very much for confirming this works for win 7 and 10!

**Comment by carlspring** [comment]
Thanks for your help, guys! :)

**Comment by kalski** [comment]
Just a clarification - I checked W7.
