### ISSUE TITLE
Test the NPM support with yarn

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1119]
# Task Description

We need feedback on how well our NPM layout provider works with `yarn`.

You might find the [`strongbox-examples`](https://github.com/strongbox/strongbox-examples/) useful. Perhaps creating a similar example using `yarn` would be helpful.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by denizseaside82** [comment]
As we discussed yesterday, Martin, could you please assign this task to me? I will give it a try. Thanks :)

**Comment by carlspring** [comment]
Hi,

Please, feel free to pick this up!
