### ISSUE TITLE
Set up our documentation to work with Spring Boot + Springfox + Swagger

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1125]
# Task Description

Now that we've migrated to Spring Boot, we would like to use Springfox with our Swagger generation.

The REST API should be accessible via http://localhost:48080/docs/rest/api.html.

This task is a sub-task of #1123 and depends on #1124.

# Todo:

- [ ] [Update the docs](https://github.com/strongbox/strongbox-docs/edit/master/docs/user-guide/rest-api.md) when this task is completed.

# Useful Links

* https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by adavid9** [comment]
@carlspring I can take this one.

**Comment by carlspring** [comment]
Thanks, @adavid9 ! I'm assigning it to you then! :)

**Comment by carlspring** [comment]
@cbrianhill : would you mind updating the `strongbox-docs`, as described above? Thanks! :)
