### ISSUE TITLE
Upgrade the swagger-maven-plugin to 3.1.8, or higher

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1128]
# Task Description

We will need to upgrade the `swagger-maven-plugin` to `3.1.8`, or higher. This might have some implications, such as having to upgrade the Swagger dependencies.

The versions of the plugin and the associated dependencies will have to be defined in the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent/) and be used versionless in the respective `pom.xml` files.

This is a sub-task of #1123 and depends on #1124.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by yugander-krishan-singh** [comment]
@carlspring  I am looking into this issue.

**Comment by carlspring** [comment]
@cbrianhill : Is this now an obsolete task?

**Comment by carlspring** [comment]
Closing as obsolete! Thanks, @cbrianhill!
