### ISSUE TITLE
Re-work the MutableStorage to not use System.getProperties, but the Spring Boot Environment instead

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1129]
# Task Description

As a continuation of #1023, we need to re-work the `MutableStorage` class to not use `System.getProperties` to work out the `basedir` of the respective storage.

The folllowing code should be dropped/re-worked:

```
public void initDefaultBasedir(String id)
{
    //TODO: we should rework this to use SpringBoot environment instead of `System.getProperty`
    String storagesBaseDir = System.getProperty("strongbox.storage.booter.basedir");
    Assert.notNull(storagesBaseDir, "System property `strongbox.storage.booter.basedir` should be configured.");
        
    Path basedirPath = Paths.get(storagesBaseDir);
    basedir = basedirPath.resolve(id).toString();
}
```

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by vikss** [comment]
I am checking this.

**Comment by carlspring** [comment]
Hi @vikss ,

Thanks for looking into this! Would you like to join our [chat channel](https://chat.carlspring.org/) as well?

**Comment by vikss** [comment]
This is up for grabs.
