### ISSUE TITLE
ParallelDownloadRemoteArtifactTest is not idempotent

### ISSUE THREAD

**Issue by symposion** [strongbox/strongbox#1141]
# Task Description

When running the tests for `strongbox-storage-maven-layout-provider`, you have to clean between each run, because the tests are not idempotent. I believe that there are several tests within the package `org.carlspring.strongbox.providers.repository` that are guilty of this, but the one that I've looked at most is `ParallelDownloadRemoteArtifactTest`. This uses the proxy repository for maven-central and requests an apache commons jar from multiple threads. It first tests that the jar does not exist on the local filesystem (under `strongbox-vault`), then runs its tests, and then checks that the file now exists locally. It doesn't clean up after itself, so obviously this test fails the initial check the next time it is run.

I'm not clear what the best practice ought to be here. Should there be a test-specific repository created that is then deleted after the test completes? It would seem that using a shared, global repository in a way that has persistent side-effects on disk - even if they are somehow cleaned up subsequently - is a recipe for collisions with other tests in the future.

# Acceptance Test

* [ ] Building the code and running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by marregui** [comment]
Hi, 

I would like to have a look at this issue, if nobody else is.

Thank you

**Comment by marregui** [comment]
Pull request: https://github.com/strongbox/strongbox/pull/1200 
Turned out to be rather trivial.

**Comment by carlspring** [comment]
Thanks, @marregui! :)
