### ISSUE TITLE
org.xml.sax.SAXParseException: XML document structures must start and end within the same entity

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1142]
# Task Description

We are occasionally seeing the following random test failure:

```
javax.xml.bind.UnmarshalException
at org.carlspring.strongbox.storage.repository.RepositoryTest.testMarshallAndUnmarshallStrongboxConfiguration(RepositoryTest.java:113)
Caused by: org.xml.sax.SAXParseException: XML document structures must start and end within the same entity.
at org.carlspring.strongbox.storage.repository.RepositoryTest.testMarshallAndUnmarshallStrongboxConfiguration(RepositoryTest.java:113)
Standard Output
21:49:43.642 21-03-2019 | INFO | kJoinPool-1-worker-0 | s.t.s.r.TestRepositoryManagementApplicationContext | Test Repository [storage0/r1] locked.
21:49:43.642 21-03-2019 | INFO | kJoinPool-1-worker-0 | s.t.s.r.TestRepositoryManagementApplicationContext | Test Repository [storage0/r2] locked.
```

We need to investigate and fix this.

# Related Tasks

* This test has been disabled in the `master` until #965 has been fixed. @ptirador , @fuss86 : If no one has fixed it by then, (or if you haven't fixed in on your branch), could you please pick this up?

* This task may somehow be related to #1105 (unconfirmed).

# Acceptance Test

* [ ] Building the code and running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
It seems Jenkins is still unhappy with this running under Windows.

**Comment by sbespalov** [comment]
@carlspring this seems other issue

**Comment by Andrewg945** [comment]
I am running a blog post and receiving this message

org.xml.sax.SAXParseException: XML document structures must start and end within the same entity

Can anyone help out with this?   I am not a coder

**Comment by carlspring** [comment]
I don't think your issue is related to this one (if we're talking about this code base), you're probably seeing this somewhere else.
Also, this project is no longer under development.
