### ISSUE TITLE
UI: Implement routing management module

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1143]
## Task description

We need to create a new ng module called `routing-management` which should have the following pages:

1. List all existing [Artifact Routing Rules](https://strongbox.github.io/user-guide/artifact-routing-rules.html)
2. Add / Edit page from where you can update the route

## Listing routes page

The listing of the routes should look like `localhost:4200/admin/users` - a table with the following columns:

* URL Pattern (i.e. `*./org/carlspring/strongbox*`)
* Rule type - either `accept` or `denied`
* Storage Id - if empty it should display `any`
* Repository Id - if empty it should display `any`
* "Actions column" - should have a an `edit` and `delete` icons. 
  * When you click the `delete` icon - it should bring a modal which asks for confirmation and upon confirmation it should send a request to the backend to delete the pattern using the `uuid`.
  * The `edit` icon should be a `routerLink=....` which points to the edit page

## Add / Edit page

This page should be the same for both cases. It should have a form which has the following fields:

* URL Pattern - required field, must not be null
* Type - required field, select with two options - `accept` and `deny`
* Ordered list of group repositories 

### Ordered list of group repositories

There is an example of this at `http://localhost:4200/admin/storages/public/maven-group/update`.
This is a list of group repositories which can be selected in an ordered manner. The code from the storage component is not re-usable at this moment. You can either copy/paste it or create a shared component which can be used in both cases.

## Additional notes

* The backend controller which is responsible for the routing management is located [here](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/RoutingConfigurationController.java). You can check it out to see what are the endpoints. 
* Follow the structure the [other modules](https://github.com/strongbox/strongbox-web-ui/tree/master/src/app/modules) have (i.e. `user-management`, `settings-management`, etc)
* Create a service which handles the interaction with the backend

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov

**Comment by LeifBrooks** [comment]
I can take this task

**Comment by carlspring** [comment]
Thanks for offering to help, @LeifBrooks ! :)

**Comment by LeifBrooks** [comment]
Hey @fuss86! Would you mind looking over this first PR whenever you have a few minutes?
