### ISSUE TITLE
Make all Artifact Generators implement the ArtifactGenerator interface

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1145]
# Task Description

Currently we have following Artifact Generator classes:
* [x] `NpmPackageGenerator` ( #1294 )
* [x] `NugetPackageGenerator` ( #1295 )
* [x] `MavenArtifactGenerator` ( [#1161](https://github.com/strongbox/strongbox/pull/1161/files#diff-4b3b4bc5d7d8f083159e61a288e2d201R62) )
* [x] `PypiArtifactGenerator` ( #1298 )

We need to make all this classes implement the `org.carlspring.strongbox.artifact.generator.ArtifactGenerator` interface.

The implementation should provide adapter logic between the `ArtifactGenerator` contract and concrete generator class.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by yugander-krishan-singh** [comment]
@sbespalov, @carlspring I would like to work on this issue.

**Comment by carlspring** [comment]
Hi,

Please, felt free to pick it up and to join our 
[chat channel](https://chat.carlspring.org/).

**Comment by carlspring** [comment]
@yugander-krishan-singh , you can have a look at #1161 and do the same for the npm and nuget generators.

**Comment by carlspring** [comment]
@yugander-krishan-singh 

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Kind regards,

Martin

**Comment by carlspring** [comment]
Done! :)

Thanks to all of you who helped! :)
