### ISSUE TITLE
Add documentation on how to get the project working in Eclipse

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1149]
# Task Description

Most of us are using IntelliJ where there are no extra settings required. Developers using Eclipse seem to need more steps in order to configure things in their IDE. We should add a section (or, if necessary, a separate page) for this in the [`strongbox-docs`](https://github.com/strongbox/strongbox-docs/).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by kalski** [comment]
@carlspring can you please assign me this one? All the issues I found with eclipse are fixed now so I can document how to setup the project there now.
