### ISSUE TITLE
Test our RPM distribution and update our docs on how to use it

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1151]
# Task Description

We recently started publishing an RPM distribution and we need to be properly tested and have the steps on how to install it documented.

# Tasks

The following tasks will need to be carried out:
* [x] Test the RPM `strongbox-distribution`.
* [x] Document the steps on how to install the RPM.

# Task Relationships

This task is a follow-up of #840.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by michiboo** [comment]
Hi I would like to try tackle this issue!

**Comment by carlspring** [comment]
Hi @michiboo,

Thanks for offfering to help! We need multiple people to test it and provide feedback, as well as to help polish our documentation!

@cbrianhill has also offered to help with this.

@michiboo, feel feel to join our 
[chat channel](https://chat.carlspring.org/) to discuss things further.

**Comment by cbrianhill** [comment]
After testing, noted one issue, which was fixed with https://github.com/strongbox/strongbox/pull/1239.  Have just added some docs to explain how to use the RPM via https://github.com/strongbox/strongbox-docs/pull/19.

**Comment by carlspring** [comment]
@cbrianhill ,

Would you mind also updating our wiki, as necessary? Thanks! :)

**Comment by carlspring** [comment]
Thank you very much! :)
