### ISSUE TITLE
Replace application.properties by yaml equivalent

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1167]
# Task Description

See also https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml

# Acceptance Test

* [ ] Building the code and running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Task Relationships

This task is a follow-up of #965 (#1056).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by sudhs22** [comment]
Can I take this up?

**Comment by carlspring** [comment]
Hi @sudhs22 ,

Go ahead and please feel free to join our [chat channel](https://chat.carlspring.org/)! :)

**Comment by sudhs22** [comment]
Hi, I have done my changes (converted the application.properties to application.yml), ran the maven with all Tests, started the application. 
- Is there any test I have to do other than ones mentioned above?
- I am unaware of how to proceed with GIT check in and push for this project. If anyone can point me to any document or link, it would be great.

Not sure if I should have buzzed it here on in chat channel. Thanks.

**Comment by carlspring** [comment]
Hi,

You will have to fork the project and push to your own fork. Hen you need to open a pull request against our project. As suggested, you can get more help on our channel.

**Comment by carlspring** [comment]
I have added a description section for the acceptance testing.

**Comment by sudhs22** [comment]
thanks @carlspring
