### ISSUE TITLE
Drop Role#repository field

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1170]
# Task Description

We should drop the `repository` field from the following classes:

* `org.carlspring.strongbox.authorization.domain.Role`
* `org.carlspring.strongbox.authorization.dto.RoleDto`
* `org.carlspring.strongbox.forms.RoleForm`

This field is currently unused and demands unnecessary attention from the developers.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by prbobba** [comment]
I can look into. I hope the acceptance criteria is the builds and Integration Tests passing?

**Comment by prbobba** [comment]
PR #1172
