### ISSUE TITLE
Drop privileges from authorization configuration

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1171]
# Task Description

We should drop the `privileges` field from the following classes:

- `org.carlspring.strongbox.authorization.dto.AuthorizationConfigDto`
- `org.carlspring.strongbox.authorization.domain.AuthorizationConfig`

It will also affect `strongbox-authorization.yaml`/`strongbox-authorization.xml`.

@carlspring I don't see any benefit from keeping this field. How do you want to use these privileges ? Currently, we are not able to use them in any form and we should drop them because it may cause confusions.

If you agree, please take the `on hold` label off from this task. 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
@sbespalov , any thoughts on this?

**Comment by carlspring** [comment]
@sbespalov , if you're okay with this, perhaps @evrimnurcelik could look into it as well, as she recently did #1138 and it might be a good task for her. Could you please confirm?
