### ISSUE TITLE
Fix the typo in the NpmArtifactCoordinates

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1177]
# Task Description

Fix the typo in the `NpmArtifactCoordinates.caclulatePackageId` and correct it to `NpmArtifactCoordinates.calculatePackageId`. This is probably used in a few other places, so correct them as well.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by bfalter** [comment]
PR: https://github.com/strongbox/strongbox/pull/1178
