### ISSUE TITLE
Implement PyPi package distribution metadata

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1179]
# Task Description

We need to implement the PyPi metadata as specified [here](https://packaging.python.org/specifications/core-metadata/). The implementation of this metadata will have to check the validity of the data, as described in the specification.

The implementation should be based on the `pypi-layout-provider` branch.

# Task Relationships

This is a sub-task of #807.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by sainalshah** [comment]
I would like to take up this issue. Can I confirm whether the scope of this issue is to validate PyPi metadata only?

**Comment by carlspring** [comment]
@sainalshah ,

Great! Thanks for offering to help!

Well, I hope that is indeed all. Give it a go and let us know how it works out. Please, feel free to join our [chat channel](https://chat.carlspring.org/) for more details.

**Comment by sainalshah** [comment]
@carlspring I couldn't find the pypi-layout-provider branch. Is it deleted?

**Comment by carlspring** [comment]
@sainalshah ,

The branch has already been merged into the `master`. You can find the layout provider there. It's a work in progress.

**Comment by sainalshah** [comment]
@carlspring 
Noted, thanks. What about the strongbox-web-integration-tests? Is it applicable for this task? Please advise.

**Comment by carlspring** [comment]
It is relevant, yes. This is where the [`strongbox-web-integration`](https://github.com/strongbox/strongbox-web-integration-tests) are located.
