### ISSUE TITLE
Implement a PyPi version validator

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1180]
# Task Description

We need to implement version validators for PyPi.

For details on the PyPi spec for versions, check [here](https://www.python.org/dev/peps/pep-0440/).

For examples of existing version validators in Strongbox, check [here](https://strongbox.github.io/knowledge-base/artifact-coordinate-validators/artifact-coordinate-validators.html) and [here](https://strongbox.github.io/knowledge-base/artifact-coordinate-validators/artifact-coordinate-validators-maven.html).

Proper test cases would be required to illustrate that this works as expected.

# Task Relationships

This is a sub-task of #807 .

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by SergeyHydra** [comment]
@carlspring Hello! If you don't mind, I want to take it.

**Comment by carlspring** [comment]
Hi @SergeyHydra,

Sounds great to me! Please join our [chat channel](https://chat.carlspring.org/) for more details and help! Thanks!

**Comment by AngelChristianPimentelNoriega** [comment]
Hello!, is this feature still available?
Thanks

**Comment by carlspring** [comment]
Hi @AngelChristianPimentelNoriega ,

Yes, this is still up for grabs. Does is sound like something you can implement? Please join our [chat channel](https://chat.carlspring.org/) for more details and help! Thanks!

**Comment by carlspring** [comment]
@sainalshah ,

Would you perhaps like to look into this...?

**Comment by sainalshah** [comment]
Sure, I'm working on this task.

**Comment by carlspring** [comment]
Thanks for picking it up! :)
