### ISSUE TITLE
Drop the /greet resource

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1183]
# Task Description

In the past, we has some tests using the `/greet` path in the layout provider controllers. We need to remove these methods from the controllers and tests.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by akhil10x5** [comment]
Hi! I would like to fix this.

**Comment by theomails** [comment]
Hi all,
I'm just starting to work on this issue.

The following controllers are impacted:

1. MavenArtifactController.java
2. NpmArtifactController.java
3. NugetArtifactController.java

And also the Rest Client:

1. RestClient.java

Shall I remove the `greet` path from the `controllers` and the `rest client`? Or only the `controllers` for now?
