### ISSUE TITLE
Drop the deprecated validateAndStore method from the ArtifactManagementService

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1184]
# Task Description

We need to drop the `@Deprecated` method `validateAndStore(String storageId, String repositoryId, String path, InputStream is)` from the `ArtifactManagementService` and replace all usages of it with `validateAndStore(RepositoryPath repositoryPath, InputStream is)`:
```
    @Deprecated
    @Transactional
    public long validateAndStore(String storageId,
                                 String repositoryId,
                                 String path,
                                 InputStream is)
            throws IOException,
                   ProviderImplementationException,
                   NoSuchAlgorithmException,
                   ArtifactCoordinatesValidationException
    {
        RepositoryPath repositoryPath = repositoryPathResolver.resolve(storageId,
                                                                       repositoryId,
                                                                       path);

        return validateAndStore(repositoryPath, is);
    } 
```

Also, the replacement method no longer throws a `NoSuchAlgorithmException`, so that should be removed from the list of thrown exceptions.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by akhil10x5** [comment]
Hi, I would like to take this up.

**Comment by carlspring** [comment]
Hi,

Feel free to do so! :)

**Comment by akhil10x5** [comment]
PR #1186
