### ISSUE TITLE
Get rid of the Hash and NuspecFile in our Nuget layout provider implementation

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1226]
# Task Description

After absorbing JNuGet in #1131, we need to do a bit of a clean up and remove the dependency on some of the original classes.

# Tasks

The following tasks will need to be carried out:
* [ ] Drop the need for the `Hash` class
* [ ] Drop the need for the `NuspecFile` class

# Task Relationships

This task:
* Is a sub-task of: #1215
* Depends on:  #1131

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by kalski** [comment]
>     * Drop the need for the `Hash` class

is already removed with #1131.

**Comment by carlspring** [comment]
Great! Any others to tick off the list?

**Comment by kalski** [comment]
That's the only one left:

> Drop the need for the `NuspecFile` class

Can you ellaborate what do you want to do with this file ? I see that it is mainly xml binding to the Nuspec from the Nupkg file specification.

**Comment by sbespalov** [comment]
@carlspring it seems both classes was already dropped so we can probably close this.

**Comment by carlspring** [comment]
@sbespalov / @kalski : If both of these have been removed, I will close it. @kalski , could you please confirm?

**Comment by carlspring** [comment]
@sbespalov / @kalski : Could you please confirm, if this task can be closed? Thanks! :)

**Comment by sbespalov** [comment]
> @sbespalov / @kalski : Could you please confirm, if this task can be closed? Thanks! :)

I confirm once again :)

**Comment by carlspring** [comment]
Thanks, @sbespalov !
