### ISSUE TITLE
Swagger documentation is not working under strongbox-distribution

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1230]
# Task Description

After merging #1124 we noticed that it works only when you start it via `spring-boot:run` but doesn't work in the `strongbox-distribution`. This needs to be investigated and fixed.

Steps to reproduce:

```
$ mvn clean install
$ cd strongbox-web-core && mvn spring-boot:run
$ curl -I http://localhost:48080/docs/rest/api.html (Status code 200, works fine)
```
---
```
$ mvn clean install
$ cd strongbox-distribution/target && \
  unzip strongbox-distribution-1.0-SNAPSHOT.zip && \ 
  ./strongbox-distribution-1.0-SNAPSHOT/strongbox-1.0-SNAPSHOT/bin/strongbox console
$ curl -I http://localhost:48080/docs/rest/api.html (Status code 404, not working)
```

**Comment by steve-todorov** [comment]
@cbrianhill let me know if you would like to have a go at this task so I can assign it to you :)

**Comment by carlspring** [comment]
Assigning it @cbrianhill , as he's our expert on this! :)

**Comment by cbrianhill** [comment]
Yup, @carlspring, I'll take care of this.
