### ISSUE TITLE
Investigate more dynamic options to import Spring contexts than how're using the @Import annotation

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1247]
# Task Description

At the moment, we're using the `@Import` to import other configuration contexts. This means that we need to (currently) hard-code the config contexts for the layout providers, (for example). This is not really dynamic and we should explore alternatives to doing the following:

```java
@Configuration
@ComponentScan({ "com.carlspring.strongbox.controllers",
                 "org.carlspring.strongbox.controllers",
                 "org.carlspring.strongbox.validation",
                 "org.carlspring.strongbox.web",
                 "org.carlspring.strongbox.mapper",
                 "org.carlspring.strongbox.utils",
                 "org.carlspring.strongbox.actuator",
                 "org.carlspring.logging" })
@Import({ CommonConfig.class,
          StrongboxSecurityConfig.class,
          StorageApiConfig.class,
          EventsConfig.class,
          Maven2LayoutProviderConfig.class, // Import this in some more dynamic way
          NugetLayoutProviderConfig.class,  // Import this in some more dynamic way
          NpmLayoutProviderConfig.class,    // Import this in some more dynamic way
          PypiLayoutProviderConfig.class,   // Import this in some more dynamic way
          RawLayoutProviderConfig.class,    // Import this in some more dynamic way
          StorageCoreConfig.class,
          UsersConfig.class,
          SecurityConfig.class,
          ClientConfig.class,
          CronTasksConfig.class,
          SwaggerConfig.class})
@EnableCaching(order = 105)
@EnableWebMvc
public class WebConfig
{
   ...
]
```

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Task Relationships

This task relates to: #807 , #817 , #829 , #872 , #845.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by kalski** [comment]
We could use [ImportSelector](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ImportSelector.html) this way:

1. Implement in our layout configs a new marker interface - say `LayoutProviderConfig`. Like this:

`Maven2LayoutProviderConfig implements LayoutProviderConfig`

2. Create a `LayoutProviderConfigsImportSelector`, implementing `ImportSelector` to select all available `LayoutProviderConfig`s through `Reflections`. Here is [an example of how to write an ImportSelector](https://www.logicbig.com/how-to/code-snippets/jcode-spring-framework-importselector.html)

3. Then where we need dynamic import of `@Configuration`s, such as in `WebConfig`, we just import the `LayoutProviderConfigsImportSelector` instead of the concrete `LayoutProviderConfig`s.

We could then enhance our `ImportSelector` even more - we could pass it config interface to check for. 

We can name it `ConfigImplementationImportSelector` and have an `@ImportImplementations` annotation to specify which `@Configuration` implementations to select. So given we already have `LayoutProviderConfig`:

```
public class ConfigImplementationImportSelector implements ImportSelector
{

    @Override
    public String[] selectImports(AnnotationMetadata importingClassMetadata)
    {
        Map<String, Object> attributesMap = importingClassMetadata.getAnnotationAttributes(
                                                                                           ImportImplementations.class.getName(),
                                                                                           false);
        AnnotationAttributes attributes = AnnotationAttributes.fromMap(attributesMap);

        Class<?>[] interfaces = attributes.getClassArray("value");
        
        Reflections configReflections = new Reflections("org.carlspring.strongbox.config");
        
        return Arrays
                .stream(interfaces)
                .flatMap(i -> configReflections.getSubTypesOf(i).stream())
                .map(c -> c.getName())
                .toArray(length -> new String[length]);
    }

}

...
/**
 * Indicates one or more {@link Configuration @Configuration} classes implementing interfaces to scan.
 * 
 * Allows more flexibility than {@link Import @Import} by specifying interfaces implemented by
 * {@link Configuration @Configuration} classes to be imported.
 */
@Import(ConfigImplementationImportSelector.class)
public @interface ImportImplementations
{
    Class<?>[] value (); 
}

...
@Import({ ...
//          Maven2LayoutProviderConfig.class,
//          NugetLayoutProviderConfig.class,
//          NpmLayoutProviderConfig.class,
//          RawLayoutProviderConfig.class,
          .....})
@ImportImplementations({ LayoutProviderConfig.class })
public class WebConfig
...
```

**Comment by carlspring** [comment]
By the looks of this great example, I'd say you've already done most of the task. Would you like to handle the task?

**Comment by sbespalov** [comment]
@carlspring I thinks we should better try to do this with Spring Boot [Auto-configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-auto-configuration.html). Also there is something similar to Java SPI in Spring Boot, so we can have `META-INF` for every Layout Provider module which will define this "SPI" for this module.

**Comment by carlspring** [comment]
@sbespalov , I believe this is what @SergeyHydra was suggesting on our chat channel, right...?

**Comment by faissalwise** [comment]
@carlspring , I thinks the simplest way to do is with Spring Boot Auto-configuration. We can manage this through component scanning ,if we add ```@SpringBootApplication(scanBasePackages = {"org.carlspring.strongbox","org.carlspring.logging"} ``` in the root of StrongboxSpringBootApplication so all the annoted classes will be picked up by Spring’s component scanning and instantiated as a bean in the Spring application context. 

We can use WebConfig as below : 
```
@EnableCaching(order = 105)
@EnableWebMvc
@Configuration
public class WebConfig
```
and StrongboxSpringBootApplication

```
@SpringBootApplication(scanBasePackages = {"org.carlspring.strongbox","org.carlspring.logging"},exclude = { DataSourceAutoConfiguration.class,
        HibernateJpaAutoConfiguration.class })
public class StrongboxSpringBootApplication
```

**Comment by sbespalov** [comment]
> @sbespalov , I believe this is what @SergeyHydra was suggesting on our chat channel, right...?

@carlspring it looks much similar of what I mean

@SergeyHydra can you please provide some details of how it can be applied to our project?

**Comment by SergeyHydra** [comment]
@sbespalov @carlspring my idea consist of creating some starter with configurations or starters for each conf  of layout providers. So for score we will need only inject dependency in pom and configurations will be import.

**Comment by sbespalov** [comment]
@carlspring would you mind assigning this task for @SergeyHydra ?

**Comment by carlspring** [comment]
Hi,

@sbespalov : Thanks for following up on this and for clarifying the approach that should be followed.

@SergeyHydra : Could you please, proceed with implmenting it? Thanks! :)

(Github only allows us to assign tasks to members of our teams. In order to become a member of the OSS team, you will need to implement a few tasks and to contribute on a more regular basis. This is just a formality -- you can begin working on the task. @SergeyHydra : Could you please remind me, if you've signed the ICLA...?).

**Comment by SergeyHydra** [comment]
pr ready: https://github.com/strongbox/strongbox/pull/1349

**Comment by sbespalov** [comment]
@carlspring this probably should be closed

**Comment by carlspring** [comment]
Thanks!
