### ISSUE TITLE
Upgrade to spring-boot >= 2.1.4.RELEASE

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1254]
# Task Description

We need to upgrade to Spring Boot >= `2.1.4.RELEASE`.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Task Relationships

This task relates to: #1130 (and should later on be re-applied there).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by faissalwise** [comment]
Hi ,

Can I take this up?

**Comment by ptirador** [comment]
Hi, I'd like to take this if there's no problem.

**Comment by ptirador** [comment]
Okay, I've just realized that PR was created: https://github.com/strongbox/strongbox-parent/pull/20
@carlspring, please take a look.

**Comment by carlspring** [comment]
@ptirador : Would you like to test and approve it?

**Comment by ptirador** [comment]
I've just tested it, but I have no permissions to do that  in `strongbox-parent`.

**Comment by carlspring** [comment]
Can you try it locally?

**Comment by ptirador** [comment]
I've tried all steps locally, but what I meant is that I can't approve it.

**Comment by carlspring** [comment]
Oh, okay, thanks for taking a look!
