### ISSUE TITLE
Upgrade the version of Jetty that we use to 9.4.18.v20190425

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1255]
# Task Description

We need to upgrade to Jetty >= `9.4.18.v20190425`.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Task Relationships

This task relates to: #1254 , #1130 (and should later on be re-applied there).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by faissalwise** [comment]
Hi ,

Can I take this up?
