### ISSUE TITLE
Fix the "loggingPath_IS_UNDEFINED" issue in the strongbox-web-core

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1261]
# Task Description

When you build the `strongbox-web-core` and run `mvn spring-boot:run` in this module, you will notice a `loggingPath_IS_UNDEFINED` directory is being created. It appears that the property is not being set correctly. This needs to be investigated and fixed.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by sainalshah** [comment]
@carlspring I can work on this issue

**Comment by carlspring** [comment]
@sainalshah :

Feel free to pick it up!

**Comment by sainalshah** [comment]
@carlspring I am not able to replicate the issue with latest codebase. Can I have more information on replicating this issue?

**Comment by carlspring** [comment]
What are the steps you've followed?

**Comment by BartoszDabek** [comment]
Hi. Can I take this?

**Comment by carlspring** [comment]
Hi, @BartoszDabek !

Go for it! Also, feelnfree to join our [chat channel](https://chat.carlspring.org/) for help and more details.

**Comment by carlspring** [comment]
It seems this has become obsolete. Thanks to everyone who had a look at it.
