### ISSUE TITLE
Upgrade com.mchange:c3p0 to version 0.9.5.4 or higher

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1263]
# Task Description

We are affected by [SNYK-JAVA-COMMCHANGE-174481](https://app.snyk.io/vuln/SNYK-JAVA-COMMCHANGE-174481). In order to resolve it, we need to upgrade `com.mchange:c3p0` to version `0.9.5.4` or higher in the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent).

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by akhil10x5** [comment]
PR: https://github.com/strongbox/strongbox-parent/pull/21

**Comment by carlspring** [comment]
@akhil10x5 ,

I believe there's more to this than just adding a dependency to the `<dependencyManagement/>` section of the `strongbox-parent`. You'll need to also add an exclusion for the older version used in `quartz` and quite likely it will make sense to upgrade that dependency as well.

Then, all `pom.xml`-s defining a dependency to `quartz` will need to have the `c3p0` dependency right above it, in order to override it.

**Comment by akhil10x5** [comment]
Hi @carlspring 

after adding the c3p0 dependency in parent pom.xml, executed mvn depedency:tree command and here is the output i got 

[INFO] +- org.quartz-scheduler:quartz:jar:2.3.0:compile
[INFO] | +- com.mchange:c3p0:jar:0.9.5.4:compile
[INFO] | +- com.mchange:mchange-commons-java:jar:0.2.11:compile
[INFO] | - org.slf4j:slf4j-api:jar:1.7.25:compile

As the output shows older version of c3p0 got overridden with the newer version, so do we still have add exclusion explicitly? Pls suggest

**Comment by carlspring** [comment]
If it picked up the newer version, then that's all that's needed! Thanks! :)

**Comment by akhil10x5** [comment]
The latest available quartz is v2.3.1 (http://central.maven.org/maven2/org/quartz-scheduler/quartz/2.3.1/quartz-2.3.1.pom)
which has a dependency c3p0 with version 0.9.5.3 (http://central.maven.org/maven2/org/quartz-scheduler/quartz/2.3.1/quartz-2.3.1.pom)
If we upgrade quartz then it still would not serve our purpose of getting c3p0 to version 0.9.5.4
Any suggestion?

**Comment by carlspring** [comment]
* Upgrade to the newest `quartz` in the `strongbox-parent` 
* Define a dependency `exclusion` under `quartz` for `c3p0`
* Explicitly define a dependency to the latest `c3p0` where `quartz` is used
