### ISSUE TITLE
Upgrade the maven-* and plexus-* dependencies to the latest in maven-commons

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1264]
# Task Description

We depend heavily on our [`maven-commons`](https://github.com/carlspring/maven-commons/) for our implementation of the Maven layout provider. However, our transitive dependencies for `maven-*` and `plexus-*` are quite old and need to be brought up-to-date.

Please, note that:
* The work for this will have to be done in the [`maven-commons`](https://github.com/carlspring/maven-commons/)
* The version of the `maven-commons` in the [strongbox-parent](https://github.com/strongbox/strongbox-parent) will have to be bumped to the next snapshot.
* There might need to be some changes to the code as well.

Here's the snyk.io report:

> Directory Traversal
> Vulnerable module: org.codehaus.plexus:plexus-utils
> Introduced through: org.carlspring.maven:maven-commons@1.4
> Detailed paths and remediation
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-builder-support@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-artifact-manager@2.2.1 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-plugin-api@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-plugin-registry@2.2.0 › org.codehaus.plexus:plexus-container-default@1.0-alpha-9-stable-1 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-profile@2.2.0 › org.codehaus.plexus:plexus-container-default@1.0-alpha-9-stable-1 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-artifact-manager@2.2.1 › org.codehaus.plexus:plexus-container-default@1.0-alpha-9-stable-1 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-profile@2.2.0 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-plugin-api@3.3.9 › org.eclipse.sisu:org.eclipse.sisu.plexus@0.3.2 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-builder-support@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-builder-support@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings-builder@3.3.9 › org.apache.maven:maven-builder-support@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings-builder@3.3.9 › org.sonatype.plexus:plexus-sec-dispatcher@1.3 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-repository-metadata@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-plugin-api@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-plugin-api@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-plugin-api@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-artifact-manager@2.2.1 › org.apache.maven:maven-repository-metadata@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings-builder@3.3.9 › org.apache.maven:maven-settings@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-plugin-api@3.3.9 › org.eclipse.sisu:org.eclipse.sisu.plexus@0.3.2 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.eclipse.sisu:org.eclipse.sisu.plexus@0.3.2 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-plugin-api@3.3.9 › org.eclipse.sisu:org.eclipse.sisu.plexus@0.3.2 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings-builder@3.3.9 › org.apache.maven:maven-settings@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-profile@2.2.0 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-repository-metadata@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-settings@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-repository-metadata@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings-builder@3.3.9 › org.sonatype.plexus:plexus-sec-dispatcher@1.3 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings-builder@3.3.9 › org.apache.maven:maven-builder-support@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.sonatype.plexus:plexus-sec-dispatcher@1.3 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-builder-support@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.codehaus.plexus:plexus-container-default@1.0-alpha-9-stable-1 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-plugin-api@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings-builder@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-artifact-manager@2.2.1 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-plugin-api@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.apache.maven:maven-plugin-registry@2.2.0 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.eclipse.sisu:org.eclipse.sisu.plexus@0.3.2 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-plugin-api@3.3.9 › org.eclipse.sisu:org.eclipse.sisu.plexus@0.3.2 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-aether-provider@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-artifact-manager@2.2.1 › org.apache.maven:maven-repository-metadata@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-repository-metadata@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.sonatype.plexus:plexus-sec-dispatcher@1.3 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model-builder@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-settings-builder@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-dependency-tree@2.1 › org.apache.maven:maven-project@2.2.0 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-core@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-plugin-api@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-plugin-api@3.3.9 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.sonatype.sisu:sisu-inject-plexus@1.4.2 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven.shared:maven-common-artifact-filters@3.0.1 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-model@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-artifact-manager@2.2.1 › org.codehaus.plexus:plexus-container-default@1.0-alpha-9-stable-1 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-artifact-manager@2.2.1 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-core@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-artifact@3.3.9 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Introduced through: org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT › org.carlspring.maven:maven-commons@1.4 › org.apache.maven:maven-artifact-manager@2.2.1 › org.codehaus.plexus:plexus-utils@3.0.22
> Remediation: No remediation path available.
> Vulnerable functions
> org/codehaus/plexus/util/Expand.extractFile()
> Overview
> Codehaus Plexus is a collection of components used by Apache Maven.
> 
> Affected versions of this package are vulnerable to Directory Traversal.
> 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by Gcolon021** [comment]
@carlspring I would like to claim this issue?

**Comment by carlspring** [comment]
Hi @Gcolon021,

Would you like to join our [chat channel](https://chat.carlspring.org/) first?

**Comment by Gcolon021** [comment]
Thanks for the response @carlspring. I joined the chat channel.

**Comment by carlspring** [comment]
Closing as obsolete.
