### ISSUE TITLE
Add Bazel dependency formatter for Maven artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1270]
# Task Description

We would like to add support for copy-pasteable dependencies for [Bazel](https://www.bazel.build/) to be used in the search engine. The format is outlined [here](https://docs.bazel.build/versions/master/be/workspace.html#maven_jar).

# Tasks

* [ ] Implement `BazelDependencyFormatter`.
* [ ] Implement a test case for it that checks things with different combinations of Maven artifact coordinates (see `MavenArtifactCoordinates` for more details) -- with, or without classifiers, different packaging types, etc.

# Classes of Interest

* `DependencySynonymFormatter`
* `CompatibleDependencyFormatRegistry`

# Existing Implementations For Maven Artifacts

The following could serve as examples of how this has been implemented for other build tools:
* `IvyDependencyFormatter` / `IvyDependencyFormatterTest`
* `GradleDependencyFormatter` / `GradleDependencyFormatterTest`
* `LeiningenDependencyFormatter` / `LeiningenDependencyFormatterTest`
* `MavenDependencyFormatter` / `MavenDependencyFormatterTest`
* `SBTDependencyFormatter` / `SBTDependencyFormatterTest`

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by Declan-Young** [comment]
I have read the tasks and understand what is required. Could I please work on this issue?

**Comment by carlspring** [comment]
Hi @Declan-Y ,

Feel free to proceed! :)
