### ISSUE TITLE
Add Apache Buildr dependency formatter for Maven artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1271]
# Task Description

We would like to add support for copy-pasteable dependencies for [Apache Buildr](https://buildr.apache.org/) to be used in the search engine. The format is outlined [here](https://buildr.apache.org/artifacts.html).

# Tasks

* [ ] Implement `BuilderDependencyFormatter`.
* [ ] Implement a test case for it that checks things with different combinations of Maven artifact coordinates (see `MavenArtifactCoordinates` for more details) -- with, or without classifiers, different packaging types, etc.

# Classes of Interest

* `DependencySynonymFormatter`
* `CompatibleDependencyFormatRegistry`

# Existing Implementations For Maven Artifacts

The following could serve as examples of how this has been implemented for other build tools:
* `IvyDependencyFormatter` / `IvyDependencyFormatterTest`
* `GradleDependencyFormatter` / `GradleDependencyFormatterTest`
* `LeiningenDependencyFormatter` / `LeiningenDependencyFormatterTest`
* `MavenDependencyFormatter` / `MavenDependencyFormatterTest`
* `SBTDependencyFormatter` / `SBTDependencyFormatterTest`

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by ogryniuk** [comment]
Hello @carlspring ,
I have read the task and understand what needs to be done. I would like to do it if nobody took it yet.
Cheers :)

**Comment by carlspring** [comment]
Hi @ogryniuk ,

Feel free to proceed! Thanks!
