### ISSUE TITLE
Fix typo in the UiController

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1286]
# Task Description

Fix the typo in `intexWithRoute` to `indexWithRoute`:
```
public class UiController implements ErrorController
{

    @GetMapping(path = { "/**", "/error" }, produces = { MediaType.TEXT_HTML_VALUE })
    public String intexWithRoute(HttpServletResponse response)
```

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by ptirador** [comment]
Hi, I'd like to take this up.

**Comment by carlspring** [comment]
Go for it!
