### ISSUE TITLE
Investigate the storage.openFiles.limit OrientDB messages that we're seeing

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1289]
# Task Description

We are seeing the following seemingly benign (warning?) message a lot lately:
```
18:55:00.454 23-05-2019 | DEBUG | t (/127.0.0.1:59914) | unknown.jul.logger | Reached maximum of opened files 513 (max=512), closed 1 files. Consider to raise this limit by increasing the global setting 'storage.openFiles.limit' and the OS limit on opened files per processor
```

This needs to be investigated and a fixed.

# Task Relationships

This task might potentially be related to #1120 and we might have to upgrade to a newer version of OrientDB.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by Sorcecoder** [comment]
After reading a little in the Orient manual and docs i think the quick fix might be to simply set the value higher in the config orientdb-server-config.xml but i am not sure if that wont repeat if the new higher value is reached due to not closing the files, but i dont have enough background informations on what exactly is happening with the files

**Comment by carlspring** [comment]
Hi @Sorcecoder ,

Would you like to play around with it and try to fix it?

**Comment by ogryniuk** [comment]
Hi @carlspring ,
I sent you a new info about this warning in the chat. 
In a nutshell, previously from my Linux configuration the warning used to appear from time to time. Now it disappeared completely

**Comment by Twb3** [comment]
This is probably related to the running user's ulimit of maximum number of open file descriptors.  You can check it with ulimit -n

**Comment by MuraliSRao** [comment]
Is this still an issue?

**Comment by carlspring** [comment]
No. I will close it, thanks!
