### ISSUE TITLE
Make the NpmArtifactGenerator implement the ArtifactGenerator interface

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1294]
# Task Description

As part of #1145, we need to refactor the `NpmArtifactGenerator` to implement the `ArtifactGenerator`. This will require re-working some of the code in the generator, as well as some of the tests.

# Task Relationships

This task:
* Is a sub-task of: #1145
* Relates to: #1295

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by ogryniuk** [comment]
Hi there @carlspring ,
Could I look into this issue for a couple of days?

**Comment by carlspring** [comment]
Hi @ogryniuk ,

Please, feel free to do so!

**Comment by ogryniuk** [comment]
This issue is free since now. Anyone is welcome to pick it up

**Comment by bamarch** [comment]
I will pick up this issue

**Comment by carlspring** [comment]
Thanks, @bamarch ! :)

**Comment by bamarch** [comment]
not working on this - @carlspring from rocketchat it looks like Oleksandr is working on this

**Comment by evilmopey** [comment]
Can I try to solve #1294?

**Comment by bamarch** [comment]
Before, I only got as far as speccing out the issue:

—————————————

- rename NpmPackageGenerator to NpmArtifactGenerator and have it implement the ArtifactGenerator interface

- update docs / tests as needed

MavenArtifactGenerator is done already https://github.com/strongbox/strongbox/pull/1161/files#diff-4b3b4bc5d7d8f083159e61a288e2d201R62 

Implementing ArtifactGenerator:

1) add the methods from the ArtifactGenerator i.e. generateArtifact() 
2) when calls are made to generateArtifact, they should then call NpmPackageGenerator#buildPackage 

—————————————

I am working on another issue now, and it seems Oleksandr still did not claim this on GH, so I think it’s open

**Comment by evilmopey** [comment]
Where is the NpmArtifactGenerator? I looked through the code and could not find it.

P.S. I am new to the open source community.

**Comment by carlspring** [comment]
@evilmopey ,

Please, leave this task to @bamarch.

**Comment by carlspring** [comment]
The original name of the class is `NpmPackageGenerator`, but it should be renamed to `NpmArtifactGenerator` for consistency.
