### ISSUE TITLE
Make the NugetArtifactGenerator implement the ArtifactGenerator interface

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1295]
# Task Description

As part of #1145, we need to refactor the `NugetArtifactGenerator` to implement the `ArtifactGenerator`. This will require re-working some of the code in the generator, as well as some of the tests.

# Task Relationships

This task:
* Is a sub-task of: #1145
* Relates to: #1294

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by vikss** [comment]
I would like to take this.

**Comment by carlspring** [comment]
@vikss ,

Feel free to give it a go! :)

**Comment by carlspring** [comment]
@vikss ,

@ptirador will take this task.

**Comment by ptirador** [comment]
Hi, I have one problem.

Looking into the class `NugetPackageGenerator` (which I will rename to `NugetArtifactGenerator`), it has this method:
```
public void generateNugetPackage(String id,
                                 String versionString,
                                 String... dependencyList)
```

When I find the usages of this method, the last parameter, `dependencyList`, is never passed. The important thing is, the `ArtifactGenerator` interface which has to be implemented by this class, has these methods:
```
Path generateArtifact(String id,
                      String version,
                      int size)
    throws IOException;

    
Path generateArtifact(URI uri,
                      int size)
    throws IOException;
```

These methods don't use that `dependencyList` parameter. I'm not very expert in NuGet, but what do I need to do in this case?

Any ideas? @sbespalov @fuss86 @carlspring @steve-todorov

**Comment by vikss** [comment]
@ptirador 
I had the same doubt until I took a look at this - https://github.com/strongbox/strongbox/pull/1161/files#diff-4b3b4bc5d7d8f083159e61a288e2d201R62
See if it helps.

**Comment by ptirador** [comment]
Hi @vikss:

Yes, I was looking at that class too, but that's not resolving my issue... or do you mean that `public void generate(String gavtc, String packaging, String... versions)` is not being used but `public void generate(Artifact artifact)` does?

**Comment by vikss** [comment]
@ptirador,
I think the overridden methods can call the generate method without this parameter. Better I let them answer it (@sbespalov @fuss86 @carlspring @steve-todorov).

**Comment by sbespalov** [comment]
@ptirador this `dependencyList` parameter used within `s-w-i-t` (btw, you should rename generator class there as well).

anyway, within this task we can not use this parameter, just delegate `ArtifactGenerator` method calls without `dependencyList`
