### ISSUE TITLE
Make the PypiArtifactGenerator implement the ArtifactGenerator interface

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1298]
# Task Description

As part of #1145, we need to refactor the `PypiArtifactGenerator` to implement the `ArtifactGenerator`.

# Task Relationships

This task:
* Is a sub-task of: #1145
* Relates to: #1294 , #1295 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by Firstmol** [comment]
You can close this issue. The feature was done in https://github.com/strongbox/strongbox/pull/1291/files

**Comment by carlspring** [comment]
Implemented by @Firstmol.
