### ISSUE TITLE
Create an NpmTestRepository annotation

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1301]
# Task Description

As part of our on-going efforts to re-work our tests, so that they're simpler and easier to parallelize an in continuation of our recent work on getting test annotations for the easier generation of test repositories and artifacts, we need to implement an NPM-specific annotation for test repositories. Please, refer to the [documentation](https://strongbox.github.io/developer-guide/writing-tests.html) for more details on how this is implemented. At the moment, we only have these annotations for Maven.

# Tasks

* [ ] Implement an `NpmTestRepository` annotation.
* [ ] Update the [documentation](https://strongbox.github.io/developer-guide/writing-tests.html).

# Task Relationships

This task:
* Relates to: #1165, #1198 , #1219 , #1302 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by LeifBrooks** [comment]
I can take this task

**Comment by carlspring** [comment]
Great! Please, proceed! :)
