### ISSUE TITLE
Create a NugetTestArtifact annotation

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1304]
# Task Description

As part of our on-going efforts to re-work our tests, so that they're simpler and easier to parallelize an in continuation of our recent work on getting test annotations for the easier generation of test repositories and artifacts, we need to implement an NuGet-specific annotation for test artifacts. Please, refer to the [documentation](https://strongbox.github.io/developer-guide/writing-tests.html) for more details on how this is implemented. At the moment, we only have these annotations for Maven.

# Tasks

* [ ] Implement an `NugetTestArtifact` annotation.
* [ ] Update the [documentation](https://strongbox.github.io/developer-guide/writing-tests.html).

# Task Relationships

This task:
* Relates to: #1294 , #1165, #1198 , #1219 , #1303 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
@ptirador ,

Would you like to look into this as well?

**Comment by ptirador** [comment]
Sure! Count me in!

**Comment by ptirador** [comment]
@carlspring: I think I need to implement #1295 first.

**Comment by carlspring** [comment]
Okay, feel free to pick it up.

**Comment by ptirador** [comment]
@carlspring/@sbespalov, I have a question:
While creating the annotation for NuGet, what's exactly the id? Could you give me an example?
```
@Documented
@Retention(RUNTIME)
@Target({PARAMETER, ANNOTATION_TYPE})
@TestArtifact(generator = NugetArtifactGenerator.class, strategy = NugetArtifactGeneratorStrategy.class)
public @interface NugetTestArtifact
{

    /**
     * {@link Storage} ID.
     */
    @AliasFor(annotation = TestArtifact.class)
    String storageId() default "storage-nuget";

    /**
     * {@link Repository} ID.
     */
    @AliasFor(annotation = TestArtifact.class)
    String repositoryId() default "";

    /**
     * The artifact identificator (ex. ???).
     */
    @AliasFor(annotation = TestArtifact.class)
    String id() default "";

    @AliasFor(annotation = TestArtifact.class)
    String resource() default "";    
    
    /**
     * The {@link NugetArtifactCoordinates} versions.
     */
    @AliasFor(annotation = TestArtifact.class)
    String[] versions() default {};
    
    /**
     * NuGet artifact packaging.
     */
    String packaging() default "nupkg";

}
```

**Comment by carlspring** [comment]
This would be the `id` of the package. Have a look at the `NugetArtifactCoordinates` class for more details.
