### ISSUE TITLE
Drop maven-commons

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1322]

**Comment by ptirador** [comment]
What about the issue #1264? I guess that it must be closed in this case.

**Comment by fuss86** [comment]
Thanks @ptirador for heads up ! I changed #1264 label to "on hold" .

**Comment by carlspring** [comment]
Correct! @ptirador , please don't work on it, if you've started looking into it.

**Comment by ptirador** [comment]
> Correct! @ptirador , please don't work on it, if you've started looking into it.

Don't worry about it, I hadn't started yet.

**Comment by carlspring** [comment]
Good, thanks!
