### ISSUE TITLE
Make the `MavenIndexerSearchProviderTest` to use `@MavenRepository` and `@MavenTestArtifact` annotations

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1323]
# Task Description

We need to make the `MavenIndexerSearchProviderTest` to be safe within concurrent execution and  follow the [Writing tests](https://strongbox.github.io/developer-guide/writing-tests.html) guide.

# What need to be done
1. Rework test methods to use injected `Reposiutory` and `Path` instances as method parameters according to current `MavenIndexerSearchProviderTest.setUp()` logic.
2. Drop the `MavenIndexerSearchProviderTest.setUp()` method

# Task Relationships

This task:
* Relates to: #1165

# Useful Links
* [Test Repositories](https://strongbox.github.io/developer-guide/writing-tests.html#test-repositories)
* [Layout specific Test Artifacts](https://strongbox.github.io/developer-guide/writing-tests.html#layout-specific-test-artifacts)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by vikss** [comment]
I will take this.

**Comment by vikss** [comment]
I am starting to work on it.

**Comment by carlspring** [comment]
Great! Thank you!

**Comment by ogryniuk** [comment]
Good day @vikss :)
Are you still interested in this issue?

**Comment by carlspring** [comment]
@ogryniuk ,

I believe that it's safe for you to take it. Please, proceed! Thanks!

**Comment by ogryniuk** [comment]
Hi @sbespalov ,
This issue turned out to be too challenging. Maybe you could advise on why the heading of the method below fails to load the ApplicationContext? :

    @ExtendWith({RepositoryManagementTestExecutionListener.class, ArtifactManagementTestExecutionListener.class})
    @Test
    public void shouldBeCapableToSearchByPartialSha1Checksum(TestInfo testInfo,
                                                             @MavenRepository(repositoryId = REPOSITORY_RELEASES_WITHOUT_CLASSNAMES_INDEXED,
                                                                              setup = MavenIndexedRepositorySetup.class)
                                                             Repository repositoryWithoutClassNamesIndexed,
                                                             @MavenTestArtifact(classifiers = {"org.carlspring:properties-injector",
                                                                                               "1.8"})
                                                             Path repositoryArtifact)
{
...
}

**Comment by carlspring** [comment]
You're using the `MavenTestArtifact` annotation incorrectly.

This:
```
@MavenTestArtifact(classifiers = {"org.carlspring:properties-injector", "1.8"})
```

Should be something like:
```
@MavenTestArtifact(groupId = "org.carlspring", artifactId = "properties-injector" , version = "1.8", classifiers = { "javadoc", "sources" })
```

Could you please have a look at the [Maven Artifact Coordinates](https://strongbox.github.io/developer-guide/layout-providers/maven-2-layout-provider.html#artifact-coordinates) in the wiki.

**Comment by ogryniuk** [comment]
@carlspring

**Comment by ogryniuk** [comment]
@carlspring 
Thanks

**Comment by ogryniuk** [comment]
To @sbespalov and everyone concerned,

From now on the issue is free and anyone is welcome to take it

**Comment by ptirador** [comment]
Related to #1165.

**Comment by vikss** [comment]
I will take it back.

**Comment by carlspring** [comment]
Okay! Don't give up! :)

**Comment by vikss** [comment]
All,

I cannot find the time to work on it right now. Feel free to grab it. If it's open, I will try to catch it in the next 2 weeks.

**Comment by carlspring** [comment]
This has already been handled by @ptirador as part of #1370  for #1165 .
