### ISSUE TITLE
Incorrect parsing in PypiArtifactCoordinates

### ISSUE THREAD

**Issue by Firstmol** [strongbox/strongbox#1333]
<h1>Task Description</h1>

In `PypiArtifactCoordinates` supports two forms:
1. `{artifactName}-{artifactVersion}.tar.gz`
2. `{artifactName}/{artifactVersion}/{artifactName}-{artifactVersion}.tar.gz`

But I got parsing error when I call `parse` method with param `test-1.tar.gz`. It happend because I pass version with one digit, also, there are can be version forms with letters(0.1.0a1 and the like)

<h1>Task Relationships</h1>

This issues:
- https://github.com/strongbox/strongbox/issues/811
- https://github.com/strongbox/strongbox/issues/809

**Comment by carlspring** [comment]
I have been thinking about this a lot.

It seems that we will have to make it possible to support multiple artifact coordinates for layout providers.

What do you propose?

**Comment by Firstmol** [comment]
Hm, what do you mean by multiple artifact coordinates? I think, currently it happens because there is semantic version with strict version format. We can leave it at that, but then we will strict version format as d.d.d.

**Comment by carlspring** [comment]
@anki2189 ,

Is this something that we can now close?

**Comment by anki2189** [comment]
@carlspring Yes , we can close this , it was fixed in https://github.com/strongbox/strongbox/pull/1633

**Comment by carlspring** [comment]
Thanks for confirming!
