### ISSUE TITLE
Using PypiCoordinates for both wheel and source packages

### ISSUE THREAD

**Issue by Firstmol** [strongbox/strongbox#1342]
# Task description

Currently, we have two package type for pypi artifact:
- source packages (`.tar.gz` extension)
- wheel packages (`.whl` extension and additional params in the name)

And for every package type we have separate coordinates class, but difference between them is not very big and we can use one coordinates class. Also, it also makes it easier working with artifacts.

# Task Relationships

This tasks relates to #807

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
@Firstmol ,

What's the status of this task? If it's not yet implemented, would you like to walk @SergeyHydra through what needs to be done and either pair up, or guide him? Thanks! :)
