### ISSUE TITLE
Split-view UI scrolls when entering data

### ISSUE THREAD

**Issue by hajosc** [strongbox/strongbox#1354]
In split view, when entering data, e.g. a password, the UI keeps scrolling up/down by about 1/2 text line every time a character is typed. This only happens if before typing the data, the view on the right was scrolled all the way to the bottom.

**Comment by hajosc** [comment]
Deepest apologies. Looks like I’m in the wrong repository :-(

**Comment by steve-todorov** [comment]
No worries! Thanks for closing and commenting on this! I was a bit confused while checking my emails. :D
