### ISSUE TITLE
Make sure to set the iat property when issuing JWT

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1379]
# Task Description

We need to add the `iat` property when we issue JWT. This property stands for "Issued At" and contains the starting date and time from which the generated token is valid. This should be added in the [SecurityTokenProvider](https://github.com/strongbox/strongbox/blob/master/strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/security/SecurityTokenProvider.java#L71). You can use `setIssuedAtToNow()` which will set the time to `now`.

Make sure to add a test case which covers if a `JWT` generated with `iat` in the future is properly handled as `invalid`. 

# Useful Links

* [JWT](https://jwt.io)
* [RFC-7519](https://tools.ietf.org/html/rfc7519)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by Twb3** [comment]
Hey I attempted to tackle this and didn't post here first because it's my first contribution to an open source project.  Wasn't sure if I could get it done, but it was pretty straightforward.  Looking forward to feedback.
