### ISSUE TITLE
Implement partial downloads with multiple byte ranges

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1397]
# Task Description

At the moment, we only support single byte ranges. This means we only support resuming a download from a certain byte that was reached when the connection was terminated. We should add support for multiple byte ranges.

# Tasks

The following tasks will need to be carried out:
* [x] Implement the support for multiple byte ranges
* [x] Add tests

# Useful Classes

* `org.carlspring.strongbox.utils.ArtifactControllerHelper`
* `org.carlspring.strongbox.io.ByteRangeInputStream`

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by pyashwanthkumar** [comment]
I will pick up this issue

**Comment by carlspring** [comment]
Okay, good luck!

**Comment by ptirador** [comment]
Hi, can I take this?

**Comment by pyashwanthkumar** [comment]
I am not working on this issue anymore :)
