### ISSUE TITLE
Make the `ConfigurationResourceResolver` use the Spring environment properties instead of System properties

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1407]
# Task Description
Currently the `ConfigurationResourceResolver` uses `System.getProperty` to get the configuration files location. Within this task the `ConfigurationResourceResolver` should be reworked to resolve the configuration files locations from `Environment.getProperty()`.

# Task Relationships

This task:
* Relates to: SB-1286

**Comment by carlspring** [comment]
@sbespalov : Is this ready? If "yes", could you please close it? If "not", then could you please clarify what still needs to be done? Thanks! :)
