### ISSUE TITLE
Deployed artifacts with curl do not appear when browsing

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1418]
# Bug Description

When you create a new storage, raw repository and then deploy an artifact it does not appear in the directory listing / browsing. If, however, you deploy the same artifact to `storage-raw/raw-releases` it'll work just fine.

# Steps To Reproduce

* `mvn clean install -DskipTests`
* `cd strongbox-web-core`
* `mvn spring-boot:run`
* Go to `http://localhost:48080/admin/storages`
* Add a new storage & raw repository:
* Upload an artifact using curl:
```
curl -X PUT -u admin --data-binary ./strongbox-web-core/target/strongbox-web-core-1.0-SNAPSHOT.jar http://localhost:48080/storages/test-raw-storage/test-raw-repository/strongbox-web-core-1.0-SNAPSHOT.jar
```
* `http://localhost:48080/admin/storages/test-raw-storage/test-raw-repository`

# Expected Behavior

Should be listing the newly deployed artifacts.

# Environment

* Strongbox Version: `1.0-SNAPSHOT` f8aa5c5
* OS: Linux / Ubuntu

**Comment by steve-todorov** [comment]
@sbespalov I'm guessing this issue is probably related to some  `ArtifactEntry` records not being added?

**Comment by sbespalov** [comment]
@steve-todorov I will have a look

**Comment by sbespalov** [comment]
@steve-todorov the issue is that you probably need to enable "Directory Browsing" for repository.

![image](https://user-images.githubusercontent.com/22783811/62687012-15c48100-b9f0-11e9-952e-8c87cc6e710b.png)

**Comment by sbespalov** [comment]
@steve-todorov you agree to close it as false positive?

**Comment by steve-todorov** [comment]
Ahhh... Sorry I haven't had a chance to check it out but I think you're right. I didn't check the allow directory browsing checkbox. Let's close it. Thanks for looking into this!
