### ISSUE TITLE
java.lang.StackOverflowError on cancelled download request

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1430]
# Bug Description

When we cancel file download, `java.lang.StackOverflowError` occurs in logs.

# Steps To Reproduce

0. Run `strongbox`
1. Hit http://localhost:48080/storages/storage-common-proxies/maven-central/.index/nexus-maven-repository-index.gz in the browser (wait for the file if it's locked)
2. Cancel a running download
3. See `strongbox` logs

# Expected Behavior

Proper handle file download cancel request.

# Logs

https://gist.github.com/fuss86/f5fab07385f9e1ac89976ff1e17fae9a

# Environment

* Strongbox Version: 
```
{"strongbox":{"version":"1.0-SNAPSHOT","revision":"868626f3ec2f0616"}}
```
* Maven version (please provide the full output of `mvn --version`):
```
$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: C:\tools\apache-maven-3.5.0
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_161\jre
Default locale: pl_PL, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by BogdanSukonnov** [comment]
Hi. Can I take this?

**Comment by carlspring** [comment]
Hi!
Yes, please!

**Comment by BogdanSukonnov** [comment]
I'll catch the EOFException in OutputStream.write() and flush(). 

- Is the message `Output stream is closed. Possibly, user cancelled download.` good for debug?

- Should I change response status to `202 ACCEPTED` ? Or it will break something else and it better still be `200 OK`?

**Comment by carlspring** [comment]
@fuss86 : What would you advise?

**Comment by fuss86** [comment]
Hi @BogdanSukonnov , thanks for your interest :)

> I'll catch the EOFException in OutputStream.write() and flush().

Probably we should also check the cause `Caused by: java.io.IOException: Connection reset by peer `

> Is the message Output stream is closed. Possibly, user cancelled download. good for debug?

Yeah, sounds good. Alternatively we can say that `socket` has been closed.

> Should I change response status to 202 ACCEPTED ? Or it will break something else and it better still be 200 OK?

The `socket` has been closed, you are not able to send response status to this channel anymore.
