### ISSUE TITLE
Make all TestCaseWithRepository based tests to use @TestRepository and @TestArtifact annotations

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1431]
# Task Description

We need to complete test resources management refactoring and make all tests to use `@TestRepository` and `@TestArtifact` annotations (or layout specific shortcut annotations).

As a result we should get rid of `TestCaseWithRepository` class.

Please note, that this task could be done by multiple people as smaller pull requests fixing separate tests.

# Tasks

The following tests will need to be refactored:

**`strongbox-testing-storage`:**
* [ ] `TestCaseWithRepository`

**`strongbox-storage-api`:**
* [ ] `TestCaseWithRepositoryManagement`

**`strongbox-storage-maven-layout-provider`:**
* [ ] `ArtifactDirectoryLocatorTest`
* [ ] `ArtifactManagementServiceImplTest`
* [ ] `ArtifactMetadataServiceReleasesTest`
* [ ] `ArtifactMetadataServiceSnapshotsTest`
* [ ] `ArtifactOutputStreamTest`
* [ ] `BaseCronJobWithMavenIndexingTestCase`
* [ ] `BaseLocalStorageProxyRepositoryExpiredArtifactsCleanerTest`
* [ ] `BaseMavenGroupRepositoryComponentTest`
* [ ] `BaseMavenMetadataExpirationTest`
* [ ] `Maven2LayoutProviderTest`
* [ ] `MavenArtifactGeneratorTest`
* [ ] `MavenArtifactTest`
* [ ] `MavenChecksumServiceTest`
* [ ] `MavenDependencyFormatterTest`
* [ ] `MavenGroupRepositoryProviderTest`
* [ ] `MavenMetadataExpirationMultipleGroupCaseTest`
* [ ] `MavenMetadataExpirationProxyCaseTest`
* [ ] `MavenMetadataExpirationSingleGroupCaseTest`
* [ ] `MavenMetadataGroupRepositoryComponentOnAddTest`
* [ ] `MavenMetadataGroupRepositoryComponentOnDeleteTest`
* [ ] `MavenMetadataGroupRepositoryComponentOnUploadTest`
* [ ] `MavenRepositoryManagementServiceImplTest`
* [ ] `MavenTestCaseWithArtifactGeneration`
* [ ] `MockedRestArtifactResolverTestBase`
* [ ] `ParallelDownloadRemoteArtifactTest`
* [ ] `RepositoryGroupIndexCreatorSearchTest`
* [ ] `RepositoryHostedIndexCreatorSearchTest`
* [ ] `RepositoryHostedIndexCreatorTest`
* [ ] `RepositoryProxyIndexCreatorTest`
* [ ] `ResourcesBooterTest`
* [ ] `RetryDownloadArtifactWithPermanentFailureStartingAtSomePointTest`
* [ ] `RetryDownloadArtifactWithSingleFailureAtSomePointTest`
* [ ] `RetryDownloadArtifactWithUnsupportedRangeRequestTest`
* [ ] `TestCaseWithMavenArtifactGenerationAndIndexing`

**`strongbox-web-core`:**
* [ ] `AqlControllerTest`
* [ ] `ArtifactCoordinateValidatorsManagementControllerTest` 
* [ ] `BrowseControllerTest`
* [ ] `CleanupExpiredArtifactsFromProxyRepositoriesCronJobTestIT`
* [ ] `ClearTrashCronJobFromMaven2RepositoryTestIT`
* [ ] `DownloadRemoteMavenIndexCronJobTestIT`
* [ ] `MavenArtifactControllerTest`
* [ ] `MavenIndexControllerTest`
* [ ] `MavenMetadataManagementControllerTest`
* [ ] `MavenProxyRepositoryProviderTestIT`
* [ ] `MavenRestAssuredBaseTest`
* [ ] `MavenSearchControllerTest`
* [ ] `MergeMavenGroupRepositoryIndexCronJobTestIT`
* [ ] `PingControllerTest`
* [ ] `RawArtifactControllerTest`
* [ ] `RawArtifactControllerTestIT`
* [ ] `RawRestAssuredBaseTest`
* [ ] `RebuildMavenIndexesCronJobTestIT`
* [ ] `RebuildMavenMetadataCronJobTestIT`
* [ ] `RegenerateMavenChecksumCronJobTestIT`
* [ ] `RemoveTimestampedMavenSnapshotCronJobTestIT`
* [ ] `TrashControllerTest`
* [ ] `TrashControllerUndeleteTest`
* [ ] `WhenRepositoryIsAliveCleanExpiredArtifactsTestIT`
* [ ] `WhenRepositoryIsNotAliveDontCleanExpiredArtifactsTestIT`

# Task Relationships

This task:
* Is a follow-up of: #1083 , #1084.
* Relates to: #1165 

# Useful Links

* [Writing tests](https://strongbox.github.io/developer-guide/writing-tests.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by ptirador** [comment]
Hi! I'd like to pick this up.

**Comment by carlspring** [comment]
Great! Thanks! :)
