### ISSUE TITLE
RepositoryHostedIndexCreatorTest and MavenIndexCreatorTest fail on MacOS

### ISSUE THREAD

**Issue by cbrianhill** [strongbox/strongbox#1437]
# Bug Description

On master, as of commit https://github.com/strongbox/strongbox/commit/868626f3ec2f0616d5110d3c363780ebbcd67ada, the unit tests `RepositoryHostedIndexCreatorTest` and `MavenIndexCreatorTest` both fail on MacOS.

# Steps To Reproduce

1. `git clone git@github.com:strongbox/strongbox` on MacOS computer
2. `cd strongbox`
3. `mvn clean install`
4. Observe the two tests above may fail.  Failures will occur in each test

# Expected Behavior
All unit tests pass.

# Screenshots
N/A

# Environment

* Strongbox Version: commit 868626f3ec2f0616d5110d3c363780ebbcd67ada
* OS: MacOS
* Maven version (please provide the full output of `mvn --version`):
`Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T12:00:29-07:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_131, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac" `

* Browser (if related to UI): N/A

# Additional context 
The HFS+ filesystem does not support sub-second granularity in the mtime on files. APFS, the newer MacOS filesystem, does offer improved granularity. However there appears to be an issue in the JDK resulting in subsecond-granularity information not being available in the Java nio APIs. More information can be found at the following location:

http://mail.openjdk.java.net/pipermail/nio-dev/2017-December/004632.html

It appears that recent Travis-CI builds on the master branch have failed for unrelated reasons, but the Travis builds have not been successful since the introduction of 868626f3ec2f0616d5110d3c363780ebbcd67ada.

# Proposed Solution

https://github.com/strongbox/strongbox/pull/1435

# Useful Links
* http://mail.openjdk.java.net/pipermail/nio-dev/2017-December/004632.html

# Task Relationships

This bug:
* Is caused by: https://github.com/strongbox/strongbox/pull/702/files (new unit tests introduced in this PR rely on file mtime changing as a consequence of successive index operations)
* Relates to: 
* Depends on:

**Comment by fuss86** [comment]
Thanks @cbrianhill for great description and investigation !

Could you please check if we can change `Files.getLastModifiedTime(indexPath)` to `indexPath.toFile().lastModified()` ? Will it work ? So we would replace `java.nio` by `java.io` in these tests.

Horrible MacOS JDK bug :)

**Comment by cbrianhill** [comment]
Hi @fuss86 , unfortunately `File.lastModified()` suffers from the same problem: it doesn't return any subsecond granularity.  I haven't checked it, but supposedly Java 10 has this fixed.

**Comment by fuss86** [comment]
@sbespalov, @carlspring  what do you guys think ? Maybe we should skip this test for MacOS under some JDK ?

**Comment by sbespalov** [comment]
@cbrianhill @fuss86 As an option we can calculate and check the file checksum instead of modification time.

**Comment by carlspring** [comment]
@fuss86 : All our test cases should be able to run under all OS.

@sbespalov / @cbrianhill : I'm happy with both adding a `Thread.sleep(1000L);` and with the suggestion of re-calculating the checksum, so is it up to you Brian. This is just one test. An increase by a second won't be all that dramatic, to be honest.

**Comment by fuss86** [comment]
@carlspring, in my opinion, this is not a good way to handle it.

**Comment by cbrianhill** [comment]
@carlspring  @fuss86  I like the checksum idea.  Let me give this a try.  Can't think of a reason it shouldn't work.

**Comment by steve-todorov** [comment]
This has been fixed in #1435. Thanks to everybody! :)
