### ISSUE TITLE
Test fails due to JwtAuthenticationTest

### ISSUE THREAD

**Issue by Zernerus** [strongbox/strongbox#1438]
# Bug Description
Testing JwtAuthenticationTest.testJWTAuthShouldFailWithoutToken (which automatically occurs when running `mvn clean install`) on Windows 10 Pro fails with the following error:
```
JwtAuthenticationTest.testJWTAuthShouldFailWithoutToken:99 1 expectation failed.
JSON path error doesn't match.
Expected: Full authentication is required to access this resource
  Actual: Vollstõndige Authentifikation wird ben÷tigt um auf diese Resource zuzugreifen
```
Changing the system language to english fixes the error.

# Steps To Reproduce

1. Change system language to german
2. clone the repo
3. `cd strongbox`
4. `mvn test -Dtest=JwtAuthenticationTest#testJWTAuthShouldFailWithoutToken -pl strongbox-web-core`

# Expected Behavior
The test should not be dependant on system language and pass on other languages than english. 

# Environment

* Strongbox Version: 0d306ed374652714cd96a40b012e9df30b4f40e1
* OS:  Windows 10 Pro
* Maven version:
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: C:\apache-maven-3.5.0
Java version: 1.8.0_221, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_221\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
``` 

# Additional context
The error message is hardcoded into the test as the String variable UNAUTHORIZED_MESSAGE. This causes the test to fail if the error message isn't the original english error message. 

# Task Relationships

This bug:
* Is caused by: 
* Relates to: 
* Depends on:

**Comment by carlspring** [comment]
@Zernerus ,

Thanks for reporting this! Would you mind having a look at @ptirador 's pull request and trying it out? Thanks!
