### ISSUE TITLE
Investigate difference between testRegenerateArtifactChecksum and testRegenerateChecksumInRepository test cases in RegenerateMavenChecksumCronJobTestIT

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1442]
# Task Description
Currently there seems no difference between `testRegenerateArtifactChecksum` and `testRegenerateChecksumInRepository` test cases in `RegenerateMavenChecksumCronJobTestIT` test class. Probably we lost something during refactoring. We need to find out what was the initial difference and restore original logic for this test cases.

# Task Relationships

This task:
* Relates to: [PR #1434](https://github.com/strongbox/strongbox/pull/1434)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by ptirador** [comment]
The difference between these two methods is the use (or not) of `basePath` as a property for the Cron task configuration to resolve the repository/artifact path:

`org.carlspring.strongbox.services.impl.ChecksumServiceImpl.java`:
```
RepositoryPath repositoryBasePath = Optional.ofNullable(basePath)
                                                    .map(p -> repositoryPathResolver.resolve(repository, basePath))
                                                    .orElseGet(() -> repositoryPathResolver.resolve(repository));

ArtifactLocationGenerateChecksumOperation operation = new ArtifactLocationGenerateChecksumOperation();
operation.setBasePath(repositoryBasePath);
operation.setForceRegeneration(forceRegeneration);
```

- If `basePath` is NOT passed as a property (or with a null value), the operation to regenerate the checksum will use the repository path as its base path.

- If `basePath` is passed as a property, the operation to regenerate the checksum will use the artifact path as its base path.

**Comment by carlspring** [comment]
@pyashwanthkumar ,

Would you perhaps like to look into this? :)

**Comment by carlspring** [comment]
@ptirador , @sbespalov ,

Is this task obsolete, or does it need to be looked into?

**Comment by ptirador** [comment]
@carlspring: What I investigated is what I commented a few months ago. I don't think that we need to do something about this. I'd close it.

**Comment by carlspring** [comment]
@sbespalov : Are you happy with us closing this?

**Comment by sbespalov** [comment]
closing, thanks :)
