### ISSUE TITLE
Better StorageBooter lock release approach

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1457]
# Task Description

At the moment [StorageBooter.lockFile](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/booters/StorageBooter.java#L52) is acquired in the [StorageBooter.initialize()](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/booters/StorageBooter.java#L60) method and released in the [StorageBooter.removeLock()](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/booters/StorageBooter.java#L89) method. This is wrong because we have no guarantee that the lock will always be released (if the process stops unexpectedly for example). We need to improve it to release the lock in the `finally` block. Also we should use [Hazelcast ILock](https://docs.hazelcast.org/docs/3.11/javadoc/com/hazelcast/core/ILock.html) as a lock type.

# Useful Links

* https://docs.hazelcast.org/docs/3.11/javadoc/com/hazelcast/core/ILock.html

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by ykabusalah** [comment]
Can I take this?

**Comment by steve-todorov** [comment]
Sure @ykabusalah ! Feel free to pick it up :)

**Comment by fuss86** [comment]
Go ahead :)

**Comment by TheKeySpammer** [comment]
If @ykabusalah is not working on this can I take this issue

**Comment by carlspring** [comment]
@TheKeySpammer : Feel free to pick it up! Thank you!

**Comment by TheKeySpammer** [comment]
Pull request #1468
