### ISSUE TITLE
Implement different maven metadata expiration strategies

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1460]
# Task Description

`MavenMetadataExpiredRepositoryPathHandler` needs to be improved so that it supports different `expiration` strategies which need to be configurable per `maven repository`:

1. `ChecksumMetadataStrategy` - this is the current implementation and needs to be preserved (this should also be the default option)
2. `RefreshMetadataStrategy` - once the metadata cache `TTL` has occurred - retrieve the remote `maven-metadata.xml`. The `maven-metadata.xml` checksums need to be generated, because they might be out of sync (which can when the remote repository is a group repository)

Once in `MavenMetadataExpiredRepositoryPathHandler#handleExpiration` - the code must choose the "right" strategy based on the defined configuration. 

A new configuration called `metadataStrategy` field should be added under `MavenRepositoryConfigurationForm` which should accept only `checksum` or `refresh` as values. 

# Task Relationships

This task:
* Relates to: SB-1421

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by cbrianhill** [comment]
@steve-todorov, @carlspring , question on this:  how is the metadata cache TTL determined?  I'm probably missing something obvious, but I'm not understanding how I would determine if `maven-metadata.xml` has expired.  I see that the context of this is handling a `ProxyRepositoryPathExpiredEvent`, but would this mean that the `RefreshMetadataStrategy` should unconditionally fetch the metadata when handling the event, or should it check for expiration of the metadata in some other way?

**Comment by steve-todorov** [comment]
@cbrianhill ping - have you had a chance to work and complete on this? :)

**Comment by carlspring** [comment]
@cbrianhill ,

Any updates on this? (I remember you were working on it and had some progress...?).
