### ISSUE TITLE
Chocolatey installs, upgrades and searches fail when package name has hyphen.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [strongbox/strongbox#1462]
# Bug Description
Chocolatey has issues installing, searching, and upgrading packages that have a hyphen/dash in their name from Strongbox. Many, quite possibly a majority of packages on Chocolatey.org have a hyphen in their name as it is the recommended way to deal with a space in the name of the software rather than say a dot.

# Steps To Reproduce

1. Setup chocolatey to use strongbox as it's source.
2. Try to use `choco install`, `choco upgrade` or `choco search`  with a package name that has a hyphen.
3. Chocolatey fails to say the package is not found with the selected source(s)

# Expected Behavior

All packages work with strongbox and chocolatey

# Environment

* Strongbox Version: Version:1.0-SNAPSHOT, revision:bc987998f19ba183
* OS: Windows 10 1903 x64
* Also seen with strongbox running in docker

# Additional context 

Install requests from nuget.exe are similar to this, and work fine-
`0.0.0.0:48080/storages/public/nuget-group/FindPackagesById()?id='testing-2'&semVerLevel=2.0.0`
While install requests from chocolatey are formated like this and fail-
`0.0.0.0:48080/storages/public/nuget-group/Packages()?$filter=(tolower(Id)%20eq%20'testing-2')%20and%20IsLatestVersion`
Both are trying to install a packaged named `testing-2` which is on the server, nuget.exe successfully installs, but chocolatey fails. Chocolatey works fine installing from strongbox with packages names that do not have a hyphen, such as testing

I think the AQL included in Strongbox is not accepting the HTTP requests from Chocolatey as valid formating. If I try the chocolatey request in a web browser, it replies as such-
`{"error":"AQL syntax error at [1:24], cause [token recognition error at: '-']\nAQL syntax error at [1:25], cause [extraneous input '2' expecting ''']"}`

# Additional Info
* [Info on how setup chocolatey and strongbox](https://github.com/strongbox/strongbox-examples/pull/15)
* strongbox/strongbox-examples#15
* strongbox/strongbox#1113

# Classes And Resources Of Interest

* `strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/antlr4/org/carlspring/strongbox/nuget/filter/NugetODataFilter.g4`
* `org.carlspring.strongbox.nuget.filter.NugetODataFilterQueryParser`
* `org.carlspring.strongbox.nuget.filter.NugetODataFilterVisitorImpl`
* `org.carlspring.strongbox.nuget.filter.NugetODataQueryVisitor`

**Comment by carlspring** [comment]
I have updated the bug description with a list of classes and resources that are related to this behaviour. Most-likely, the grammar file will need to be slightly re-worked.
