### ISSUE TITLE
Language-related error for shouldRequireAuthenticationAccess method in PasswordEncoderControllerTest

### ISSUE THREAD

**Issue by ptirador** [strongbox/strongbox#1466]
# Bug Description

After merging PR #1465, the `shouldRequireAuthenticationAccess` method in `PasswordEncoderControllerTest` class fails if the system language is in German, as already happened in #1438. 

This is happening due to Spring Security uses a `messages_{language}.properties` file to translate some security error messages, being English as default language.

# Steps To Reproduce

1. Change system language to German.
2. Clone the repository.
3. `cd strongbox`
4. `mvn test -Dtest=PasswordEncoderControllerTest#shouldRequireAuthenticationAccess -pl strongbox-web-core`

# Expected Behavior
The test should not be dependant on system language and pass on other languages than English. 

# Environment

* Strongbox Version: 1.0-SNAPSHOT
* Strongbox Revision: f9af518a4304be51
* OS:  Ubuntu 19.04
* Maven version:
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /opt/apache-maven-3.6.0
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-27-generic", arch: "amd64", family: "unix"
``` 

# Additional context
The error message is hardcoded into the test as "`Full authentication is required`". This causes the test to fail if the error message isn't the original english error message. This should be fixed in the same way as PR #1439 

# Task Relationships

This bug:
* Is caused by: PR #1465
* Relates to: #1438 
* Depends on:

**Comment by steve-todorov** [comment]
Ahh... I didn't see this one coming. Thanks for reporting this @ptirador! Would you like to fix it or should I? :)

**Comment by ptirador** [comment]
Please, go ahead, all yours :)
