### ISSUE TITLE
OrientDb stores java.util.Date without time 

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1475]
# Bug Description

As described in the subject, `orientDb` stores `java.util.Date` without time. For example, once stored `org.carlspring.strongbox.domain.ArtifactEntry#created` is always at midnight.

# Steps To Reproduce

1. Run `org.carlspring.strongbox.services.impl.ArtifactEntryServiceTest` and watch the logs

# Expected Behavior

`org.carlspring.strongbox.domain.ArtifactEntry#created` and other `java.util.Date` fields should be stored in database with proper time

**Comment by evsikov** [comment]
Please assign this on me.

**Comment by carlspring** [comment]
@evsikov ,

Please, feel free to dig into this task and to join our [chat channel](https://chat.carlspring.org/).

**Comment by ykabusalah** [comment]
Can I try this?

**Comment by evsikov** [comment]
I am currently working on this issue.
