### ISSUE TITLE
Get rid of static Rest Assured context

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1476]
# Bug Description

Currently we have static Rest Assured context used within `strongbox-web-core` tests, which leads to issues related with Spring Application Context in the case of concurrent tests execution. The issue is that we have different instances of Spring Application Context within our tests and Rest Assured in turn uses this contexts while doing REST invocations. So while we have static Rest Assured context instance which replaced by every next context initialization and finally last initialized context always used.

# Steps To Reproduce

1. checkout [PR #954](https://github.com/strongbox/strongbox/pull/954)
2. execute `mvn test -T 4 -Dtest=LdapAuthenticatorConfigurationControllerTest#ldapConfigurationTestShouldFailWithInvalidConfiguration,PingControllerTest#shouldReturnPong -Psb` within `strongbox-web-core`
3.
```
08:26:09.850 26-09-2019 | ERROR | kJoinPool-1-worker-3 | s.c.c.s.l.LdapAuthenticatorConfigurationController | Failed to test LDAP configuration.
java.lang.ClassCastException: org.carlspring.strongbox.authentication.support.DisabledUserDetailsService cannot be cast to org.springframework.security.ldap.userdetails.LdapUserDetailsService
        at org.carlspring.strongbox.authentication.external.ldap.LdapAuthenticationConfigurationManager.lambda$testConfiguration$0(LdapAuthenticationConfigurationManager.java:67)
```
# Expected Behavior

```
BUILD SUCCESS
```

# Proposed Solution 
We need to make custom Rest Assured factory which instance will be related to current test execution. As an option it can be `ThreadLocal` instance.

# Useful links
* [RestAssuredTestExecutionListener](https://github.com/strongbox/strongbox/blob/master/strongbox-testing/strongbox-testing-web/src/test/java/org/carlspring/strongbox/rest/common/RestAssuredTestExecutionListener.java)

# Task Relationships

This bug:
* Relates to: [PR #954](https://github.com/strongbox/strongbox/pull/954)

**Comment by bono007** [comment]
Hi. I am an engineer at Indeed and we are doing Hacktoberfest. I am interested in hacking on `strongbox`. This looks like a great 1st intro ticket. 

Some background: I have been doing Java for quite a while now and have focused on Spring/Boot over the last 5 years. I will look for a "deeper" ticket to grab after this one.

**Comment by bono007** [comment]
After chatting more w/ @carlspring - I am going to take #1213 as @sbespalov is already heading out on this one.
