### ISSUE TITLE
npm publish is broken and will return 500 Server Error

### ISSUE THREAD

**Issue by pyashwanthkumar** [strongbox/strongbox#1490]
# Bug Description

Issuing the command below will return 500 server error:

`npm publish`

# Steps To Reproduce

1.  Clone this [repo](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-npm)
2. Execute the steps mentioned [here](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-npm#prepare-project-workspace)

# Expected Behavior

You should see the output mentioned [here](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-npm#prepare-project-workspace) after you execute `npm publish`

# Screenshots

![image](https://user-images.githubusercontent.com/18516640/65992122-9afe6c00-e45c-11e9-9371-503024adeff2.png)

# Help

[Our chat](https://chat.carlspring.org/)

Points of contact:

- @carlspring
- @sbespalov
- @fuss86
- @steve.todorov

**Comment by carlspring** [comment]
Actually, this is so by design. Proxy repositories should not allow you to deploy artifacts to them. They are simply proxies and their caches could be wiped out at any given time, thus, artifacts deployed to them would be lost.

**Comment by steve-todorov** [comment]
Ahh.. it looks like I did not pay attention to the repository you were deploying yesterday @pyashwanthkumar. Sorry. :)

**Comment by pyashwanthkumar** [comment]
Cool! NP!. Glad to know the issue :)
