### ISSUE TITLE
Use the built-in formatting in logging methods

### ISSUE THREAD

**Issue by ptirador** [strongbox/strongbox#1500]
# Task Description
Passing concatenated strings into a logging method can incur a needless performance hit because the concatenation will be performed every time the method is called, whether or not the log level is low enough to show the message.

Specifically, the built-in string formatting should be used instead of string concatenation.

As of SLF4J, in the presence of multiple parameters and if the last argument in a logging statement is an exception, then SLF4J will presume that the user wants the last argument to be treated as an exception and not a simple parameter.

**Noncompliant Code Example**

```
logger.debug("Something went wrong: " + message1 + " and this too: " + message2); // Noncompliant; string concatenation performed even when log level too high to show DEBUG messages


logger.info(String.format("Validate artifact with path [%s]", path));


catch(Exception e)
{
  logger.error("An exception occurred with message: " + message); // Noncompliant
  e.printstackTrace();  // Noncompliant
}
```
   
**Compliant Solution**
```

logger.debug("Something went wrong: {} and this too: {} ", message1, message2); // String formatting only applied if needed


logger.info("Validate artifact with path [{}]", path));


catch(Exception e)
{
   logger.error("An exception occurred with message: {}", message, e); // The SLF4J API supports parametrization in the presence of an exception, assuming the exception is the last parameter.
}

```

# Useful Links

* [SLF4J - Parameterized logging](https://www.tutorialspoint.com/slf4j/slf4j_parameterized_logging.htm)
* [SLF4J - Parameterized exception](https://www.slf4j.org/faq.html#paramException)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by raksit31667** [comment]
Pretty straightforward, can I work on this issue?

**Comment by carlspring** [comment]
Go for it!

**Comment by jjjimenez100** [comment]
@raksit31667 Hi, are you working on this one? If not, can I take it? :)

**Comment by raksit31667** [comment]
> @raksit31667 Hi, are you working on this one? If not, can I take it? :)

I'm working on it, it takes a village to complete all of them since there are lots of logs there :(

**Comment by raksit31667** [comment]
@carlspring Please kindly approve #1506, let me know if there are any concerns.
