### ISSUE TITLE
Update the documentation regarding tests and assertJ assertions

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1501]
# Task Description

Once we standardized tests assertions using [AssertJ](https://joel-costigliola.github.io/assertj/) we should amend the documentation related to `Writing tests` topic.

# Tasks

The following tasks will need to be carried out:
* [ ] Update https://strongbox.github.io/developer-guide/writing-tests.html page. Let people know we use [AssertJ](https://joel-costigliola.github.io/assertj/) for assertions in all modules except `strongbox-web-core` (and why we can't use  [AssertJ](https://joel-costigliola.github.io/assertj/) in `strongbox-web-core`)
* [ ] Update https://strongbox.github.io/developer-guide/junit-user-guide.html page. Update the `Assertions` paragraph and all others if necessary.

# Task Relationships

This task:
* Is a follow-up of: https://github.com/strongbox/strongbox/issues/1456

# Useful Links

* https://github.com/strongbox/strongbox-docs
* https://strongbox.github.io/developer-guide/writing-tests.html
* https://strongbox.github.io/developer-guide/junit-user-guide.html

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by fuss86** [comment]
@mslowiak would you mind picking up this task ?

**Comment by mslowiak** [comment]
> @mslowiak would you mind picking up this task ?

Yup, I will handle that
