### ISSUE TITLE
Add a Stackoverflow badge

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1507]
# Task Description

We'd like to add a badge for Stackoverflow in our `README.md` file (under the list of other badges at the top).

[This is the link](https://stackoverflow.com/tags/strongbox/) to our tag on Stackoveflow.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by iam-abbas** [comment]
I would like to take this up

**Comment by lunodesouza** [comment]
Please close this issue! :)

**Comment by carlspring** [comment]
Thanks for bringing it to my attention!
