### ISSUE TITLE
Create a jtwig extension which converts byte size into human readable size

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1529]
# Task Description

We need to create a jTwig extension which is capable for converting the byte size into a human readable string. Although the `byte size` should in most cases be a `Long` this is going to be used in the templates and the value might sometimes also be a `String`. If the value cannot be properly converted - it should return the same value.

The extension should be placed a new package called `org.carlspring.strongbox.jtwig.extensions`.

Example usage in the template:

```
# find directoryListing.twig.html in `strongbox-web-core

<td>{{ file.size | default("-") | humanReadableSize  }}</td>
```

To check your code:
1. [Start a Strongbox instance](https://strongbox.github.io/developer-guide/building-strongbox-using-strongbox-instance.html#starting-a-strongbox-instance) 
2. Download an artifact by going to `http://localhost:48080/storages/storage-common-proxies/carlspring/org/carlspring/maven/derby-maven-plugin/1.10/derby-maven-plugin-1.10.jar`
3. Browse the artifact by going to `http://localhost:48080/api/browse/storage-common-proxies/carlspring/org/carlspring/maven/derby-maven-plugin/1.10/`
4. The `Size` column should show the size in human readable format like `1.0 MB` instead of the `long` it usually shows.

# Useful Links

* [jTwig docs](http://jtwig.org/documentation/reference/web/spring-boot)
* [Byte size into human readable](https://stackoverflow.com/a/3758880/393805)

# Help
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by millimetha** [comment]
I´ll work on this issue

**Comment by steve-todorov** [comment]
Sure @millimetha! If you need help you can join our [chat](https://chat.carlspring.org)  :)

**Comment by anki2189** [comment]
@steve-todorov Is this still open?

**Comment by steve-todorov** [comment]
Yes, it looks like @millimetha hasn't had a chance to work on it so feel free to pick it up. :)

**Comment by carlspring** [comment]
Please, feel free to pick it up, @anki2189 ! :)
