### ISSUE TITLE
Make DirectoryListingService instances be managed by Spring Application Context

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1542]
# Task Description

Currently, we have inline instantiation of  `DirectoryListingServiceImpl` with different `baseUrl` parameters within `LoggingManagementController` and `BrowseController`. In this task we should re-work it to inject `DirectoryListingService` instances through Spring.

As an option we can use classifiers to have different instances of same `DirectoryListingService` interface.

# Tasks

The following tasks will need to be carried out:
* [ ] Create `org.carlspring.strongbox.config.DirectoryListingServiceConfig`  configuration with `DirectoryListingService` beans.
* [ ] Replace `DirectoryListingServiceImpl` instantiation with Spring Application Context managed beans injection.

# Task Relationships

This task:
* Is a follow-up of: #1046 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @sbespalov
  * @fuss86
  * @steve-todorov
  * @carlspring

**Comment by saratbeesa** [comment]
Dear @carlspring , 

May I work on this task ?

**Comment by carlspring** [comment]
Sure! Thanks for offering to help!
