### ISSUE TITLE
Add a dependency exclude for org.testng:testng

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1547]
# Task Description

We're not using `org.testng:testng` in this project, but it's coming as a transitive dependency via `org.codehaus.groovy:groovy-all@3.0.0-beta-3` › `org.codehaus.groovy:groovy-testng@3.0.0-beta-3` › `org.testng:testng@6.14.3`.

In term, this dependency has a vulnerabilty, as explained [here](https://app.snyk.io/vuln/SNYK-JAVA-ORGTESTNG-174823).

This will most-likely have to be fixed in:
* The [strongbox-parent](https://github.com/strongbox/strongbox-parent/)
* The [strongbox-proto-parent](https://github.com/strongbox/strongbox-proto-parent/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by sa160690** [comment]
Hi, can I do this as part of hacktoberfest?

**Comment by carlspring** [comment]
@patro1322 has already prepared a pull request for this.

**Comment by carlspring** [comment]
@patro1322: Have you checked, if this affects the `strongbox-web-integration-tests`?

**Comment by carlspring** [comment]
Thank you for your help, @patro1322 and congratulations on your first pull request! :)
