### ISSUE TITLE
Two test files are named wrong and don't pass

### ISSUE THREAD

**Issue by grantfar** [strongbox/strongbox#1557]
# Task Description
The tests in: `strongbox\strongbox-storage\strongbox-storage-layout-providers\strongbox-storage-nuget-layout-provider\src\test\java\org\carlspring\strongbox\cron\jobs`,  don't run because the files are named wrong. When renamed a lot of the tests fail.

# Tasks

The following tasks will need to be carried out:
* [ ] Rename the files to end in Test
* [ ] Fix tests that fail

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
@grantfar : Can this task be closed?

**Comment by grantfar** [comment]
@carlspring yes

**Comment by carlspring** [comment]
Thanks for confirming! :)
