### ISSUE TITLE
Document how to use Hazelcast Management Center for dev needs

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1581]
# Task Description

There is a tool called [Hazelcast management center](https://hazelcast.com/product-features/management-center/). It enables monitoring and management of nodes running Hazelcast. This includes monitoring the overall state of clusters, as well as detailed analysis and browsing of data structures in real time, updating map configurations, and taking thread dumps from nodes. 

We use Hazelcast for caching. It'd be helpful to have an instruction of how to setup [Hazelcast management center](https://hazelcast.com/product-features/management-center/) for `strongbox`.

From https://docs.hazelcast.org/docs/management-center/3.8.3/manual/html/Getting_Started.html
> If you have the open source edition of Hazelcast, Management Center can be used for at most 2 members in the cluster. 

Instruction should be written in https://github.com/strongbox/strongbox-docs (https://strongbox.github.io/)

# Task Relationships

This task:
* Relates to: https://github.com/strongbox/strongbox/issues/1513

# Useful links

* https://github.com/strongbox/strongbox-docs
* https://strongbox.github.io/

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by fuss86** [comment]
@mwvdev would you like to pick it up ?

**Comment by mwvdev** [comment]
> @mwvdev would you like to pick it up ?

Sure thing, I'll give it a shot. Might take me a bit because I'm a bit strapped for time these days.

**Comment by mwvdev** [comment]
I've added support for easily enabling Hazelcast management center in Strongbox as part of this issue.

**Comment by carlspring** [comment]
Great! Is there a pull request for it?

**Comment by mwvdev** [comment]
There will be one shortly, just finishing all the testing steps in the PR template :-)

**Comment by mwvdev** [comment]
@carlspring Documentation has been added in [this PR](https://github.com/strongbox/strongbox-docs/pull/68) and accompanying code has been added in [this PR](https://github.com/strongbox/strongbox/pull/1605).
