### ISSUE TITLE
Drop the INDEX field from the LayoutFileSystem

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1590]
# Task Description

We need to drop the `INDEX` field from the `LayoutFileSystem`, as this is specific only for the Maven layout provider. Perhaps a better place for this would be the `MavenRepositoryFeatures` class.

# Tasks

The following tasks will need to be carried out:
* [ ] Refactor the `LayoutFileSystem`, so that it no longer contains the `INDEX`.
* [ ] Make sure none of the other (non-Maven) layout providers are affected.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
@carlspring I am working on this task.
