### ISSUE TITLE
Investigate randomly failing test under Windows ([Operation [write:48] content size don't match.] )

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1591]
# Task Description

We need to investigate this exception that happens under Windows against our `master`:
```
Error
[Operation [write:48] content size don't match.] 
Expecting:
 <40000L>
to be equal to:
 <0L>
but was not.
Stacktrace
org.opentest4j.AssertionFailedError: 
[Operation [write:48] content size don't match.] 
Expecting:
 <40000L>
to be equal to:
 <0L>
but was not.
	at org.carlspring.strongbox.services.ArtifactManagementServiceImplTest.testConcurrentReadWrite(ArtifactManagementServiceImplTest.java:522)
```

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by sayeedkhannabil** [comment]
I would like to help on that. Can you help me on what I need to do?

**Comment by carlspring** [comment]
Hi @sayeedkhannabil ,

If you are able to reproduce it, then sure -- go for it! :)

Good luck and thanks!

**Comment by valiobojinov** [comment]
I digged a bit in the logs it is a java.nio.file.AccessDeniedException on a test rsource see the attached file. 
[1591-stacktrace.txt](https://github.com/strongbox/strongbox/files/4444267/1591-stacktrace.txt)

Given that it happens really rarely, and it does look as something within the Windows specific provider, I don't think it is an issue with the resource closure, but this could be a clue for further investigation in case of new failures

**Comment by carlspring** [comment]
Thanks for having a look! I suggest we come back to, if it ever re-occurs.

**Comment by carlspring** [comment]
Closing this issue, as it doesn't seem to be occurring anymore. (Will re-open it, if it does).
