### ISSUE TITLE
Investigate what test is creating the metadata resources under source directories and move them to a better place

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1599]
# Task Description

Investigate what test(s) are creating:
```
strongbox-web-core/src/test/resources/temp
strongbox-web-core/src/test/resources/temp/metadata-foo
strongbox-web-core/src/test/resources/temp/metadata-foo/META-INF
strongbox-web-core/src/test/resources/temp/metadata-foo-maven-plugin
strongbox-web-core/src/test/resources/temp/metadata-foo-maven-plugin/META-INF
strongbox-web-core/src/test/resources/temp/metadata-faa-maven-plugin
strongbox-web-core/src/test/resources/temp/metadata-faa-maven-plugin/META-INF
```
And make sure these test resources are not created under the source directories anymore, but in a more appropriate location under `target` instead, because test resources should not be generated under source directories, as they're temporary and will otherwise only litter the codebase.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by TJoker024** [comment]
I'm on it

**Comment by TJoker024** [comment]
@carlspring Hi ! Since i'm new on this project and i dont know the structure of the project yey, could you give me a few pointer on how i can generate these test ( i just finished installing the project and there is nothing in strongbox-we-core/src/test) and any int about what is creating these test? thank you !

**Comment by savaliyagautam** [comment]
@TJoker024 @carlspring  I have created pull request https://github.com/strongbox/strongbox/pull/1602

**Comment by carlspring** [comment]
Thanks, @savaliyagautam! Could you please sign the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?
