### ISSUE TITLE
Fix `ArtifactEntity.tags` TODO in `ArtifactEntryRepositoryTest.crudShouldWork()`

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1645]
# Bug Description

Collection type properties seems broken in `neo4j-ogm`. It should be fixed probably somewhere in `GremlinRequest`.

# Steps To Reproduce

1. Uncomment TODO in `ArtifactEntryRepositoryTest#crudShouldWork()`
2. Run the test
3. `ArtifactEntity.tags` contents will be not as expected.

# Task Relationships

This bug:
* Relates to: #1573

**Comment by sbespalov** [comment]
this seems no longer relevant, the `ArtifactEntity.filenames` property seems works fine in [Migrate Strongbox from OrientDB to JanusGraph #1676](https://github.com/strongbox/strongbox/pull/1676).

**Comment by steve-todorov** [comment]
Thanks for the update @sbespalov ! :)
