### ISSUE TITLE
Upgrade org.springframework:spring-webmvc to version 5.2.3 or higher

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1656]
# Task Description

We should upgrade `org.springframework:spring-webmvc` to version `5.2.3` or higher, in order to fix a cross-site request forgery (as explained [here](https://snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-542933)) and a reflected file download vulnerability (as explained [here](https://snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-542935)).

The dependency upgrade should be done in the [strongbox-parent](https://github.com/strongbox/strongbox-parent/) project.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by Rinita-De** [comment]
Hi @carlspring - can i take up the issue if no one else is working on it?

**Comment by carlspring** [comment]
Sure, feel free to dig into it! Thanks!

**Comment by Vatsalgarg1617** [comment]
Hey @carlspring - Can I also look into this issue?

**Comment by carlspring** [comment]
Sure, @Vatsalgarg1617 , feel free to look into it.

**Comment by Dhiraj072** [comment]
@carlspring I am also looking into this
