### ISSUE TITLE
"Out of service" storages can not be removed and zombie around

### ISSUE THREAD

**Issue by gretel** [strongbox/strongbox#1664]
# Steps To Reproduce

1. create a 'proxy repository'
2. set 'Status' to `Out of Service`
3. try to 'Delete Repository"
4. note the error message:
```
Failed to complete request /api/configuration/strongbox/storages/storage-nuget/chocolatey
[object Object]
```

# Expected Behavior

storage should get deleted.

# Environment

* Strongbox Version: `{"strongbox":{"version":"1.0-SNAPSHOT","revision":"eccd13064b1e3bfa"}}`
* OS: `adoptopenjdk/openjdk8:jdk8u232-b09-alpine`

**Comment by carlspring** [comment]
Thanks for reporting this! :)

**Comment by steve-todorov** [comment]
Thanks for reporting this! Is there any logs in Strongbox which you can share as well?

**Comment by carlspring** [comment]
@gretel : Is this only happening on the UI side of things? Does it work, if you try it through the REST API?

**Comment by gretel** [comment]
> @gretel : Is this only happening on the UI side of things? Does it work, if you try it through the REST API?

did only try using the `UI` for now

**Comment by gretel** [comment]
```
curl -i -H "content-type: application/json" -u "admin:secret" https://chocobox.doa.otc.hlg.de/api/configuration/strongbox/storages/storage-nuget/chocolatey
...
{"message":"Requested repository storage-nuget:chocolatey is out of service."}
```

**Comment by savaliyagautam** [comment]
@carlspring  `resloveArgument` in `org.carlspring.strongbox.web.RepositoryMethodArgumentResolver` is throwing `ServiceUnavailableException` if service status is other than `In Service`

```
final boolean inService = repository.isInService();
        if (!inService)
        {
            final String message = String.format(NOT_IN_SERVICE_REPOSITORY_MESSAGE, storageId, repositoryId);
            throw new ServiceUnavailableException(message);
        }
```

**Comment by carlspring** [comment]
@savaliyagautam ,

Could you please try it out and prepare a pull request with a proper test case, if this fixes it?

**Comment by steve-todorov** [comment]
@savaliyagautam you are correct. It looks like we are also missing a test case for the `RepositoryMapping` annotation. Would you like to add one (maybe something like the [CsrfTokenArgumentResolverTests](https://github.com/spring-projects/spring-security/blob/5.1.5.RELEASE/web/src/test/java/org/springframework/security/web/method/annotation/CsrfTokenArgumentResolverTests.java)). 

This annotation also needs to have an optional parameter `notInServiceRepositories = false (by default)` so it can be used at places such as the configuration since that restriction doesn't really matter there (but it does in the `/storages/**` segment)

**Comment by carlspring** [comment]
Hi @savaliyagautam ,

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by savaliyagautam** [comment]
@carlspring  I have already signed ICLA document and also I am part for chat channel.

**Comment by carlspring** [comment]
Sorry, you're right! It seems I have forgotten. Thanks for reminiding me! :)

**Comment by anki2189** [comment]
I am working on this task.

**Comment by gretel** [comment]
thanks!
