### ISSUE TITLE
Investigate and fix randomly failing tests

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1671]
# Bug Description

The `master` currently has a few randomly failing test cases which have been causing build failures:

1. `org.carlspring.strongbox.providers.repository.MavenProxyRepositoryProviderTestIT#whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist`
2. `org.carlspring.strongbox.cron.jobs.CleanupExpiredArtifactsFromProxyRepositoriesCronJobTestIT#expiredArtifactsCleanupCronJobShouldCleanupDatabaseAndStorage`
3. `org.carlspring.strongbox.providers.repository.WhenRepositoryIsAliveCleanExpiredArtifactsTestIT#expiredArtifactsCleanerShouldCleanupDatabaseAndStorage`

I have created a [gist](https://gist.github.com/steve-todorov/2092d58cf34084948b740166aec579eb) with the common failing test cases and their logs.

# Steps To Reproduce

In most cases you can reproduce it by doing `mvn clean install -Dintegration.tests` inside `strongbox/strongbox-storage/strongbox-storage-layout-providers` or `strongbox/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout`

**Comment by sbespalov** [comment]
I managed to reproduce `MavenProxyRepositoryProviderTestIT`, working on fixing it now.
