### ISSUE TITLE
Figure out how to deal with LDAP's  base64 encoded passwords

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1679]
# Task Description

In LDAP the `userPassword` attribute contains the hash of the password encoded as `base64` and the end result in LDAP will be something like this `{ALG}base64.encode(md5/sha1/bcrypt(mypassword))`. The `PasswordEncoder` in Spring, however, expects that the part after `{ALG}` is actually the `hash` which causes login failures. If you have saved the `userPassword` using [PasswordEncoderFactories.createDelegatingPasswordEncoder](https://docs.spring.io/spring-security/site/docs/5.2.x/api/org/springframework/security/crypto/factory/PasswordEncoderFactories.html) it will work just fine, but in all other cases it will fail since the the compared hashed strings won't match.

# Task Relationships

This task:
* Is a follow-up of: #1670, #1614

# Useful Links

* [RFC4519#userPassword](https://tools.ietf.org/html/rfc4519#section-2.41)
* [RFC3112](https://tools.ietf.org/html/rfc3112)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by sbespalov** [comment]
@steve-todorov @anki2189 is this task relevant?

**Comment by steve-todorov** [comment]
Yes it is, but I believe we can fix it in another way which we'd need to discuss first.

**Comment by sbespalov** [comment]
the suggestion is to make `DelegatingPasswordEncoder ` decorator that will try to base64 decode password if first match failed.

**Comment by steve-todorov** [comment]
I believe we can make it more reliable by simply using LDAP authentication bind which means to attempt to `bind` to the LDAP server as the user/password trying to login. This way the LDAP server will do the necessary checks for us and we won't have to worry about all the possible configuration variations you might have.

Maybe @sbespalov can share some thoughts on how to do this in our current code? (which are the classes responsible for this and if we can use spring to create a LDAP connection)

**Comment by carlspring** [comment]
@sbespalov / @steve-todorov ,

Could you guys please work on improving the desription of the task with:
* An improved clearer description
* Classes on interest
* Task list

Thanks!

**Comment by sbespalov** [comment]
Recently we discussed that there should be both LDAP authentication types available, which is bind and manager DN. We could also have it configurable so user could make it work as required for particular case. 
I think we should fix the manager DN authentication anyway. On the other hand it will take much less time then implementing bind authentication (which will also require some UI work as well). 
So my suggestion is to fix base64 encoding issue for manager DN case, this will allow us to have working LDAP authentication without any overheads.

**Comment by steve-todorov** [comment]
> So my suggestion is to fix base64 encoding issue for manager DN case, this will allow us to have working LDAP authentication without any overheads.

I agree with @sbespalov's suggestion - it should work in the short-term. The task list should be something like this:
* [StrongboxSecurityConfig.java] -
   * This class currently serves no purpose - maybe we should remove it?
   * The `passwordEncoder` part should be moved in [SecurityConfig.java] and refactored to use a custom version of `org.springframework.security.crypto.password.DelegatingPasswordEncoder` instead of the original one.
* Create a custom version of `org.springframework.security.crypto.password.DelegatingPasswordEncoder` which will attempt to `base64 decode` the password and finally delegate it to the password encoder.
* Write a unit test case for the `CustomDelegatingPasswordEncoder` to ensure it works properly 
  ```
  {ALG}md5/sha1/bcrypt(mypassword)
  {ALG}base64.encode(md5/sha1/bcrypt(mypassword))
  ```
* Write an integration test which tests with unboundid (some additional user records will need to be added in the testing `ldif` for this purpose)

@sbespalov is there anything I'm missing in the task list?

------

In the long term we should promote the `binding` authentication method and keep the password comparision for legacy/flexibility/compatibility reasons. This will be much more reliable because the entire authentication logic is handled by the LDAP server (i.e. credential comparision, password expiration, is the user active/banned/etc)

One more important note is - in Active Directory you cannot obtain the `userPassword` field at all (check [this][so-link], [official docs 1], [official docs 2]) They have a custom implementation which most likely uses LM hash or NTLM hash (similar to what they use for windows in the sam file). This means login will always fail in AD with the current implementation.


[SecurityConfig.java]: https://github.com/strongbox/strongbox/blob/f6f280c8e01fe32b8681b5f4f9dd8c9aee9e1d2d/strongbox-web-core/src/main/java/org/carlspring/strongbox/config/SecurityConfig.java
[StrongboxSecurityConfig.java]: https://github.com/strongbox/strongbox/blob/f6f280c8e01fe32b8681b5f4f9dd8c9aee9e1d2d/strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxSecurityConfig.java#L22


[so-link]: https://stackoverflow.com/questions/53104871/what-is-the-attribute-that-holds-encrypted-password-in-active-directory
[official docs 1]: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/f3adda9f-89e1-4340-a3f2-1f0a6249f1f8?redirectedfrom=MSDN
[official docs 2]: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6e803168-f140-4d23-b2d3-c3a8ab5917d2?redirectedfrom=MSDN

**Comment by sbespalov** [comment]
@steve-todorov thanks for update!
Purposed sub-tasks seems right in general, just one thing which I would slightly adjust:
> This class currently serves no purpose - maybe we should remove it?

this class purpose is for `@ComponentScan`  at most, so the `strongbox-security-api` module could scan the appropriate subpackages. Instead of removing this configuration class I would suggest to rename `org.carlspring.strongbox.config.SecurityConfig` to `org.carlspring.strongbox.config.WevSecurityConfig` to make naming more clear.

Everything else seems fine!

**Comment by steve-todorov** [comment]
Thanks for clarifying! I'll add another task related to this one with the description.

In that case - it'd be better to rename it to `StrongboxSecurityApiConfig` (following the module name), because otherwise it will leaves the false sense that it is the `WebSecurityConfig`, but in reality the entire web security configuration is under `strongbox-web-core` in the `SecurityConfig` class (we should maybe rename this to `WebSecurityConfig` to follow Spring's convention?)

**Comment by steve-todorov** [comment]
I'm closing this in favor of #1840 and #1841. Thanks for your help in clearing the specs @sbespalov ! :)
