### ISSUE TITLE
Test case for anonymous nuget list command

### ISSUE THREAD

**Issue by anki2189** [strongbox/strongbox#1685]
# Task Description
`s-w-i-t` has test case for `nuget list` command, it should be able to list packages without credentials.

# Task Relationships

This task:
* Relates to: https://github.com/strongbox/strongbox/issues/1662

# Useful Links

* https://github.com/strongbox/strongbox-web-integration-tests

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by steve-todorov** [comment]
That would be a great to have! Eventually when chocolatey/choco#1827 gets merged we should create a docker image with `choco` as well, since `choco` doesn't work very well with recent `mono` versions (which is why we don't have it in `s-w-i-t`)

**Comment by sbespalov** [comment]
@anki2189 thanks for the issue, I was thinking to do the same but you got ahead of me :+1:

**Comment by carlspring** [comment]
Hey guys,

chocolatey/choco#1827 has finally been merged! :)

**Comment by steve-todorov** [comment]
Awesome! :) 

@anki2189 I'm currently working on other tasks. Would you be interested in playing around with some docker? Essentially a new image based on [Dockerfile.alpine.jdk(8|11)-mvn3.6-mono5-nuget3.4](https://github.com/strongbox/ci-build-images/blob/master/images/alpine/jdk8/Dockerfile.alpine.jdk8-mvn3.6-mono5-nuget3.4) needs to be created. You can checkout [this](https://hub.docker.com/r/thinkco/chocolatey/dockerfile) image which is similar to what we'd need (but using `alpine`).

**Comment by anki2189** [comment]
Sure.

**Comment by ykabusalah** [comment]
Can I attempt this?

**Comment by steve-todorov** [comment]
Hi @ykabusalah , thanks for your interest in this task. @anki2189 are you working on this task right now? AFAIK you're working on #1709 only, right?

**Comment by anki2189** [comment]
Right @steve-todorov , I am working #1709. @ykabusalah feel free to pick this task. :)

**Comment by steve-todorov** [comment]
Thanks for confirming! @ykabusalah If you are still interested let me known so I can assign this task to you.

**Comment by anki2189** [comment]
@ykabusalah Are you working on this task ?

**Comment by carlspring** [comment]
@anki2189 ,

Feel free to pick it up.

**Comment by carlspring** [comment]
@anki2189 ,

Could this now be closed?

**Comment by anki2189** [comment]
Yes, we can close this now.

**Comment by carlspring** [comment]
Thanks for confirming! :)
