### ISSUE TITLE
feature request: allow arrow keys to navigate mac search results

### ISSUE THREAD

**Issue by rob3c** [strongbox/strongbox#1693]
I love the additional search flexibility in Strongbox now. Often my searches result in multiple results, as intended by my use of keywords/tags/etc.

I tend to prefer keyboard vs mouse interactions whenever possible on desktops, and it would be a nice additional tweak if we could use up/down arrows to select among search results instead of having to select them with the mouse.

Thanks in advance!

**Comment by steve-todorov** [comment]
Hi @rob3c, I believe you have opened issue in the wrong project :)

**Comment by rob3c** [comment]
oops - sorry! Google tricked me this time :-)

**Comment by steve-todorov** [comment]
No worries! Thanks for confirming! :)
