### ISSUE TITLE
Boot screen should actually countdown the remaining seconds until reconnect

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1694]
# Task Description

The `strongbox/strongbox-web-ui` can run independently from `strongbox/strongbox` during the development. When you start `strongbox-web-ui` via `npm start` or `ng serve` it becomes accessible at `localhost:4200`. When you hit that address you will see the "booting" screen which will try to connect to the backend at `localhost:48080` so it can report on the booting progress. 

Right now, if the UI cannot connect to the backend for some reason (i.e. it's down or is not ready to accept incoming requests) it will try to reconnect infinitely and will report a message saying how many seconds it will wait before retying.  

![image](https://user-images.githubusercontent.com/2303663/75832599-3d7d9b00-5dbf-11ea-9fe0-a2045b599c9b.png)

We need to make a timer to update the message on every second so that it would report `retrying in X-1` until it hits 0 or something interrupts the timer (like `this.destroy$`). This can be achieved using `rxjs`. Make sure to avoid memory leaks (i.e. use kill switch like `takeUntil`).

The main code for the booting screen is located in the [`boot-progress.service.ts`](https://github.com/strongbox/strongbox-web-ui/blob/c37138fd888ede6affaf32fc239a2ea7ed2808c1/src/app/modules/core/services/boot-progress.service.ts)

# Useful Links

* [rxjs](https://www.learnrxjs.io/learn-rxjs/operators/creation/interval)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov

**Comment by rljoia** [comment]
Hi, I'll try to solve this issue following the initial tip: "you can do it with rxjs (which is relatively the same as rxjava since your background is Java). Thanks!

**Comment by steve-todorov** [comment]
Hi @rljoia, any update on this task? :)

**Comment by rljoia** [comment]
Hi @steve-todorov ! I will start at this week. So many work on masters :-)

**Comment by steve-todorov** [comment]
Thanks for the update! :)

**Comment by rljoia** [comment]
@steve-todorov , I think I solved the issue. I will ask to Andre to test. After that, we will submit the change.
