### ISSUE TITLE
About the database's last synchronization time

### ISSUE THREAD

**Issue by dai640** [strongbox/strongbox#1700]
Can you add a function to the app, regarding the last synchronization time of the database, because sometimes network reasons may occur, the latest data is not synchronized in time, or the newly created database project is not synchronized, so you can clearly see Whether the last synchronization time of the data matches.
![1](https://user-images.githubusercontent.com/8486208/76392566-c9d62200-63ac-11ea-90d5-9ffc356bd199.jpg)

**Comment by steve-todorov** [comment]
Hey @dai640 ! I believe you have added an issue to the wrong project. :)
