### ISSUE TITLE
Implement option to not autohide entry when focus is switched to another application

### ISSUE THREAD

**Issue by ronaldl** [strongbox/strongbox#1720]
# Bug Description

Currently any open entries are automatically hidden when the focus is switched to another application. There are times when it would be useful to reference information in an entry (such as the notes field). It would be good to add an option to disable this behavior.

# Environment

* Strongbox Version: 1.13.7 (2901)
* OS: macOS 10.15.3

**Comment by carlspring** [comment]
Hi,

You've reported this to the wrong project
