### ISSUE TITLE
Re-work the ArtifactDirectoryLocatorTest to not replace the System.out

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1722]
# Task Description

We need to re-work the ArtifactDirectoryLocatorTest to not replace the System.out, as is affects other tests which are running in parallel and when it hijacks the output, the output of those tests becomes hidden.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by mv93** [comment]
can I work on this @carlspring ?

**Comment by carlspring** [comment]
Hi @mv93 ,

Yes, please! This would be very helpful! :)

**Comment by carlspring** [comment]
@mv93 ,

Any updae on this?

**Comment by carlspring** [comment]
There is no reasonable way to test this without doing a sizeable refactoring, just for the sake of testing the `ArtifactDirectoryLocator`. The need for this test has become obsolete. This is already being tested by various tests that invoke this sort of functionality transitively, such as, for example `ArtifactMetadataServiceReleasesTest` and `ArtifactMetadataServiceSnapshotsTest`.

I will simply remove this test.
