### ISSUE TITLE
Disable Handoff for clipboard

### ISSUE THREAD

**Issue by tobx** [strongbox/strongbox#1729]
When copying a password and "Handoff" is enabled the clipboard gets copied to other devices automatically. E.g. an iOS app can read the password after it has been copied on a Mac.

This should be disabled for security reasons. E.g. KeePassXC disables Handoff when copying passwords. At least an option to disable this would be good.

# Tasks

The following tasks will need to be carried out:
* [ ] Disable Handoff when copying from Strongbox

# Useful Links

* [Handoff](https://support.apple.com/en-us/HT209455)
* [KeePassXC](https://keepassxc.org)

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project.

**Comment by tobx** [comment]
Oh, I am sorry!

**Comment by carlspring** [comment]
No problem!
