### ISSUE TITLE
Add a "System Requirements" section to the "Getting Started" page

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1734]
# Task Description

We should improve our "Getting Started" page by adding a "System Requirements" section before the "Installation" steps.

The changes should be applied to the [strongbox-docs](http://github.com/strongbox/strongbox-docs/) project.

This [question](https://stackoverflow.com/questions/61157478/what-are-the-hardware-requirements-for-building-and-developing-strongbox/) was raised by @despoinasr on Stackoverflow.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by TheCakeIsNaOH** [comment]
I think this already exists at #483

**Comment by carlspring** [comment]
Thanks for pointing it out. I've closed the older task.
