### ISSUE TITLE
Fix ActuatorEndpointControllerTest

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1742]
# Task Description

We need to fix this test against the `issues/1649` branch.

The example of failed Jankins build is [here](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1676/105/tests)

# Task Relationships

This task:
* Is a sub-task of: #1649

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
Test `ActuatorEndpointControllerTest#testEndpointsWithAuthorizedUser` for parameter `/health` is failing becuase neo4j is not intialized when this test is trigged hence healthcheck for neo4j is failing resulting in `/health` endpoint failure.

Possible solution can be :

- Initialize Neo4j before test.

- Exclude neo4j from health check.

**Comment by anki2189** [comment]
There is one more failure for parameter `/health/db` as this url is gving 404 . Will try to find out reason for this, assumption is Cassandra DB is not discoverable.

**Comment by carlspring** [comment]
Should we really have a check for `Neo4J`? We're not using Neo4J, we're just using some of their OSS API-s.

**Comment by anki2189** [comment]
we don't have check for `Neo4j`. I believe it is automatically getting picked from classpath

**Comment by carlspring** [comment]
Interesting... Is there a way to disable it via a property?

**Comment by anki2189** [comment]
Yes, can be diabled using property `management.health.neo4j.enabled`

**Comment by carlspring** [comment]
Could you try, if disabling would solve this for us and open a pull request, if it does? Thanks! :)

**Comment by anki2189** [comment]
> Could you try, if disabling would solve this for us and open a pull request, if it does? Thanks! :)

Yes, working fine. Now, I am debugging why `/health/db` is not working

**Comment by sbespalov** [comment]
@anki2189 we shouldn't check `neo4j` health because we don't have the `neo4j` db. We only use `neo4j-ogm`. So could you please disable it?

**Comment by anki2189** [comment]
@carlspring We can close this issue.

**Comment by carlspring** [comment]
Thanks, @anki2189 ! :)
