### ISSUE TITLE
Fix NpmArtifactControllerTest.packageNameTestBadRequest

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1743]
# Task Description

We need to fix this test against the `issues/1649` branch.

The failed Jenkins build is [here](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1676/105/tests)

# Task Relationships

This task:
* Is a sub-task of: #1649

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
May I pick this?

**Comment by carlspring** [comment]
Please, proceed!

**Comment by anki2189** [comment]
This test is failing because `NpmArtifactCoordinates#setVersion` method is removed . This method was having Version validation, hence invalid package names test is failing.

**Comment by anki2189** [comment]
@carlspring We can close this issue.

**Comment by carlspring** [comment]
Thanks for looking into it! :)
