### ISSUE TITLE
Disable automatic JanusGraph schema creation

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1755]
# Task Description
We should use strict schema within definitions in `StrongboxSchema` class.

# Tasks

The following tasks will need to be carried out:
* [ ] Set the `schema.default = none` for JanusGraph instance within `EmbeddedJanusGraphWithCassandraServer` and `InMemoryJanusGraphServer`
* [ ] Enable all posible [Schema contstraints](https://docs.janusgraph.org/basics/schema/#schema-constraints) for Vertices, Edges and properties.

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: 
* Is a follow-up of: #1649
* Relates to:

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
@carlspring This issue can be closed.

**Comment by carlspring** [comment]
Thanks for your help! :)
