### ISSUE TITLE
error during building strongbox-npm-metadata on windows

### ISSUE THREAD

**Issue by gmlag** [strongbox/strongbox#1771]
[ERROR] Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:1.0.0-alpha4:generate (default) on project strongbox-npm-metadata-jackson: Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:1.0.0-alpha4:generate failed: Unrecognised URI, can't resolve this: file://C:buildsstrongbox-npm-metadata2strongbox-npm-metadata-jackson/target/generated-resources/META-INF/common.schema.json: For input string: "buildsstrongbox-npm-metadata2strongbox-npm-metadata-jackson" -> [Help 1]

**Comment by gmlag** [comment]
I don't know how to create a pull request, so here is a fix:
[1771.txt](https://github.com/strongbox/strongbox/files/4623886/1771.txt)

**Comment by carlspring** [comment]
Hi @gmlag ,

Thanks for reporting this!

Could you please paste the complete output of your `mvn --version`? What version of Windows are you running this on?

You can also have a look at these links:
* https://strongbox.github.io/developer-guide/getting-started.html
* https://strongbox.github.io/developer-guide/git/rebase-vs-merge.html

In order to create a pull request, you need to fork the repository and fix it in a branch in your repository and then open a pull request against our repository once it's done.

@sbespalov : How do you find the proposed fix?

**Comment by sbespalov** [comment]
I would wait for PR to say something :)

**Comment by gmlag** [comment]
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)                                                                                                                 Maven home: C:\builds\APPS\apache-maven-3.6.3\bin\..                                                                                                                          Java version: 1.8.0_232, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-8\jre                                                                                Default locale: en_GB, platform encoding: Cp1252                                                                                                                              OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by gmlag** [comment]
replaceAll method treat strings as regexp's, so it won't work for windows paths.
but changing replaceAll() -> replace() doesn't solve all the problems and to make it work on all platform it's better to use standard class to build file URI, instead of manual string construction

**Comment by carlspring** [comment]
I would strongly recomment upgrading to the latest versions of Maven 3.x and JDK8.

**Comment by gmlag** [comment]
https://github.com/strongbox/strongbox-npm-metadata/pull/13

**Comment by carlspring** [comment]
@gmlag ,

Thanks for reporting this and for proposing a fix! This was fixed differently by @AricMonary in #1932 (via strongbox/strongbox-parent#119).
