### ISSUE TITLE
ios app store loads incorrect version of strongbox

### ISSUE THREAD

**Issue by sevmamba** [strongbox/strongbox#1778]
# Bug Description
ios app store loads incorrect version of strongbox
Describe the bug/issue you have.

# Steps To Reproduce

1. on an ios device with 9.3.6 (latest version for ipad 2), delete the strongbox app
2. on apple device go to app store, select "purchased", then "strongbox"
3. device asks if you want to download old version, click yes.
4. then dowloaded version is strongbox 1.48.5 which is not compatible with ios 9.3.6

# Expected Behavior

# Screenshots

# Environment

* Strongbox Version: 
* OS: 
* Maven version (please provide the full output of `mvn --version`):
* Browser (if related to UI): 

# Additional context 

# Proposed Solution 

# Known Workarounds 

# Useful Links 

* [link1]()
* [link2]()
* [link3]()

# Task Relationships

This bug:
* Is caused by: 
* Relates to: 
* Depends on:

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project. I assume you're referring to the strongbox-password-safe/Strongbox project. I'm therefore closing this bug report.

Kind regards,

Martin
