### ISSUE TITLE
Reduce the Gremlin query complexity for ArtifactCoordinates hierarchy queries

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1787]
# Task Description

`ArtifactCoordinates` stored in DB as `GenericArtifactCoordinates` vertex which is connected with one of the particular `ArtifactCoordinates` type vertices throught `Extends` edge. There could be seven of such vertices:
- `RawArtifactCoordinates`
- `MavenArtifactCoordinates`
- `NpmArtifactCoordinates`
- `NugetArtifactCoordinates`
- `PypiArtifactCoordinates`
- `RpmArtifactCoordinates`

The persistence implementation of such inheritance provided by `EntityUpwardHierarchyAdapter` class. Another part of persistence inheritance implementation is that each `ArtifactCoordinates` entity class and vertex in which it is stored corresponds to particular `LayoutArtifactCoordinatesAdapter` implementation, so currently we have seven of such implementations. The `EntityUpwardHierarchyAdapter` goes from `GenericArtifactCoordinates` vertex upward by hierarchy to fold vertices and edges into entity class instance. After passing the `Extends` edge it iterates throught all `LayoutArtifactCoordinatesAdapter`s to find the one that supports the vertex label following by `Extends`. In Gremlin this is  `__.choose(..)` clause with two branches like below:
```
    private EntityTraversal<Vertex, E> chainUpward(String nodeLabel,
                                                   EntityTraversal<Vertex, E> nodeTraversal,
                                                   EntityTraversal<Vertex, E> upwardTraversal)
    {
        return __.<Vertex, E>choose(t -> nodeLabel.equals(t.label()),
                                    __.map(nodeTraversal),
                                    upwardTraversal);
    }
```
- the `nodeLabel` is current vertex label following by `Extends`
- the `nodeTraversal` is one of the `LayoutArtifactCoordinatesAdapter`s traversal
- the `upwardTraversal` will be the same `choose` with another `LayoutArtifactCoordinatesAdapter`s traversal

So we have 14 branches in Gremlin to fold concrete `ArtifactCoordinates` entity class and while working on performance it was noticed that such branches affects a lot on Gremlin query execution time, even if only one branch will be executed in real time.

To reduce the amount of such branches we could choose one target `LayoutArtifactCoordinatesAdapter` class based on what `ArtifactCoordinates` class we expect during the artifact download request. This could be done same was as `LayoutProvider` selected and based on `LayoutProvider` we have at runtime we could get the corresponding `LayoutArtifactCoordinatesAdapter`.

# Task Relationships

This task:
* Is a sub-task of: #1754 
* Relates to: #1676

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by steve-todorov** [comment]
I'm closing this task since it's now merged! Thanks for this!
