### ISSUE TITLE
StrongBox crashes immediately

### ISSUE THREAD

**Issue by HongmouZhang** [strongbox/strongbox#1794]
# Bug Description

Today I have updated to the newest version of strongbox (1.48.13), but I cannot use it at all, the software crashes immediately after I launch it, and tried several times and restart my iphone, doesn't work. My phone is iphone 11 pro, IOS version is 13.5.1.

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project. I assume you're referring to the [strongbox-password-safe/Strongbox project](https://github.com/strongbox-password-safe/Strongbox). I'm therefore closing this bug report.

Kind regards,

Martin
