### ISSUE TITLE
strongbox-checks.xml dtd is not defined.

### ISSUE THREAD

**Issue by AkshayBabbar** [strongbox/strongbox#1821]
# Bug Description
strongbox-checks.xml dtd is not defined properly.
It is not pointing to valid checks.

# Steps To Reproduce

1. Clone Repo.
2. mvn clean install
3. Repo check

# Expected Behavior
DTD should be defined.

# Environment

* OS: Windows 10
* Maven version (please provide the full output of `mvn --version`):3.6.0
* Browser (if related to UI): NA

**Comment by carlspring** [comment]
> # Bug Description
> strongbox-checks.xml dtd is not defined properly.

How should it be defined?

> It is not pointing to valid checks.

What checks are invalid Could you be more specific?

> # Steps To Reproduce
> 1. Clone Repo.
> 2. mvn clean install
> 3. Repo check

What do you mean by repo check?

> # Expected Behavior
> DTD should be defined.

As per my understanding, these are checkstyle rules (which we're currently not using). What DTD do you need to define? These are in the XML file. I'm not sure I get what you're trying to explain, so it would be great, if you could try to go into more detail.

> # Environment
> * OS: Windows 10
> * Maven version (please provide the full output of `mvn --version`):3.6.0
> * Browser (if related to UI): NA

**Comment by AkshayBabbar** [comment]
I am not sure what is the correct but,

"http://www.puppycrawl.com/dtds/configuration_1_3.dtd" is not referencing anything.
Do let me know if this has to be handled or not.

**Comment by carlspring** [comment]
I don't believe this is an issue. If you have evidence this isn't so, please feel free to provide it and make your case. I am closing it for now.
