### ISSUE TITLE
Upgrade Jetty from 9.4.18.v20190429 to 9.4.31.v20200723

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1848]
# Task Description

We need to upgrade Jetty from version `9.4.18.v20190429` to `9.4.31.v20200723`.

Please, note that you might need to override some of the `spring-boot` Jetty-related dependencies.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Useful Commands

To check the dependency tree:

```
mvn dependency:tree
```

Usually, it's more convenient to output the results to a file, so that it's searchable:

```
mvn dependency:tree > dep.tree
```

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by MadisonReese** [comment]
GHC

**Comment by carlspring** [comment]
@MadisonReese ,

Feel free to proceed and good luck! :)

**Comment by rsuroju** [comment]
I would like to work on this, if anyone has not taken up this task.

**Comment by carlspring** [comment]
@madisonreese: Are you still looking into this?

**Comment by vivekmthr** [comment]
Hey, if no one has touched this yet could I try it?

**Comment by carlspring** [comment]
Hey @vivekmthr ! Go for it!

**Comment by ptirador** [comment]
Hi @carlspring! Can I work on this?

**Comment by carlspring** [comment]
Hi, Pablo!

Yes, please! And... yeah it needs to be upgraded to the latest one.
