### ISSUE TITLE
Remove the net.sf.ehcache:ehcache-core dependency from the strongbox-parent and all strongbox modules

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1849]
# Task Description

We are no longer using EHCache. However, we still seem to have the dependency in both the [strongbox-parent] and [strongbox] modules. These dependencies need to be removed.

# Tasks

The following tasks will need to be carried out:
* [ ] Drop the dependency from the [strongbox-parent] project and check, if this causes any issues.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc).

# Useful Links

* Check our article on [how to upgrade dependencies and plugins], as the process you will need to follow is roughly the same.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by VanessaSingh** [comment]
Hey @carlspring @sbespalov @steve-todorov , 

I am GHC attendee. Can I take up this issue?

**Comment by carlspring** [comment]
Hi @VanessaSingh ,

Yes, please! Thanks for looking into it! :)

**Comment by VanessaSingh** [comment]
I have removed net.sf.ehcache:ehcache-core dependency (https://github.com/strongbox/strongbox-parent/blob/master/pom.xml#L429). Should I also remove ehcache from systemPropertyVariables (https://github.com/strongbox/strongbox-parent/blob/master/pom.xml#L186) ?

**Comment by carlspring** [comment]
Yes, absolutely! Thank you! :)

**Comment by steve-todorov** [comment]
Hmm - could you check if `ehcache.disk.store.dir` is not being used in the strongbox/strongbox project? If not - it's probably safe to remove.

**Comment by carlspring** [comment]
All references in the code to `ehcache` should be safe to remove. Also, if you could do a:
```
mvn dependency:tree > dep.tree
```
and check for any transitive `ehcache` dependencies that could be excluded via the `strongbox-parent`, that would be highly appreciated! :+1:

**Comment by carlspring** [comment]
@VanessaSingh ,

Are you still looking into this?

**Comment by sbespalov** [comment]
I would like to work on it if no one mind
