### ISSUE TITLE
Upgrade our slf4j dependencies from 1.7.24 to 1.7.30

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1850]
# Task Description

We need to upgrade our slf4j dependencies from `1.7.24` to `1.7.30`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by Baibhab97** [comment]
Hi @carlspring , I would like to take this up. Please assign it to me. I will raise the PR after 1st October.

**Comment by carlspring** [comment]
Hi @Baibhab97 ,

Thanks for offering to help! If no one else has picked it up during the Grace Hopper Celebration (Opensource Day), which will be on October 1st, then feel free to look into it.

**Comment by shravyags** [comment]
Hello! I am a Grace Hopper attendee. Can I work on this?

**Comment by steve-todorov** [comment]
Sure you can @shravyags! :)
