### ISSUE TITLE
Upgrade org.apache.httpcomponents:httpclient from 4.5 to 4.5.12

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1851]
# Task Description

We need to upgrade `org.apache.httpcomponents:httpclient` from `4.5` to `4.5.12`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by ratisaxena** [comment]
Can I pick this up ?

**Comment by steve-todorov** [comment]
Sure! :)

**Comment by ratisaxena** [comment]
Facing the following issue when running the integration tests `mvn clean install -Dintegration.tests` . However the test passes when ran individually.
```
[ERROR] connectionsReleasedTest  Time elapsed: 0.169 s  <<< ERROR!
javax.ws.rs.ProcessingException: Error closing message content input stream.
        at org.carlspring.strongbox.service.impl.ProxyRepositoryConnectionPoolConfigurationServiceImplIT.connectionsReleasedTest(ProxyRepositoryConnectionPoolConfigurationServiceImplIT.java:67)
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 48; received: 0)
        at org.carlspring.strongbox.service.impl.ProxyRepositoryConnectionPoolConfigurationServiceImplIT.connectionsReleasedTest(ProxyRepositoryConnectionPoolConfigurationServiceImplIT.java:67)
```

**Comment by ptirador** [comment]
Hi @carlspring,

After investigating a little, I've realized that this error is provoked due to a bug with Jersey dependency, which should be updated from `2.23.1` (Jun, 2016) to the latest `2.32` (Sep, 2020). I've just tried in my local environment and integration tests pass. Should we create an issue for this?

**Comment by carlspring** [comment]
Hi @ptirador ,

That's fantastic! So, what would that mean? You'll fix the Jersey issue separately and then this @ratisaxena 's pull request will be merged?

**Comment by ptirador** [comment]
Yes @carlspring , that's what I meant.

**Comment by carlspring** [comment]
Okay, great! Thanks! :)

Let me know when I should merge things.

**Comment by carlspring** [comment]
Hi @ratisaxena !

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by carlspring** [comment]
@ratisaxena ,

Could you please re-test this now? You might have to [rebase your code](https://strongbox.github.io/developer-guide/git/rebase-vs-merge.html).

**Comment by carlspring** [comment]
@ptirador ,

Would you like to follow-up on this?

**Comment by ptirador** [comment]
@carlspring, sure! Assign it to me.

**Comment by carlspring** [comment]
Beat you to it :)

(Thanks! :) )
