### ISSUE TITLE
Upgrade our hamcrest dependencies from 1.3 to 2.2

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1853]
# Task Description

We need to upgrade our `hamcrest` dependencies from `1.3` to `2.2`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to: #1852 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by ptirador** [comment]
Hi @carlspring! Can I take this one?

**Comment by carlspring** [comment]
Hi Pablo!

Yes, please!

**Comment by carlspring** [comment]
Fixed by @ptirador in strongbox/strongbox-parent#87.
