### ISSUE TITLE
Upgrade our Quartz dependencies from 2.3.0 to 2.3.2

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1855]
# Task Description

We need to upgrade our Quartz dependencies from `2.3.0` to `2.3.2`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by AkshayBabbar** [comment]
Can I try this?

**Comment by AkshayBabbar** [comment]
is this already done?

`<version.quartz>2.3.2</version.quartz>`

I can see this in Strongbox-parent pom.xml. Please let me know... :)

**Comment by carlspring** [comment]
Yes, please! :)

**Comment by carlspring** [comment]
Thanks for flagging this! I will close it.

**Comment by AkshayBabbar** [comment]
Please close it if you can under my name in so that it can be shown in Hacktober Fest Progress if possible?
Thanks for the help.

Regards,
Akshay Babbar

**Comment by AkshayBabbar** [comment]
Hi Please close this with the label -> "hacktoberfest-accepted"

Thanks, Team.

**Comment by carlspring** [comment]
There is no need for this. This is not a pull request, but an issue and it won't count towards your efforts for #hackroberfest. For more details, please check [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

**Comment by AkshayBabbar** [comment]
Ok Cool np thanks for informing :)
