### ISSUE TITLE
Upgrade our awaitility dependencies from 3.1.2 to 4.0.3

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1856]
# Task Description

We need to upgrade `awaitility dependencies from `3.1.2` to `4.0.3`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to: #1852 , #1853 , #1854 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by kosuruvarunkumar** [comment]
Hi, I would like to pick this up.

**Comment by carlspring** [comment]
Hi @kosuruvarunkumar ,

Feel free to look into it! Thanks for offering to help! :)
