### ISSUE TITLE
Upgrade our swagger dependencies from 1.5.18 to 1.6.2

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1857]
# Task Description

We need to upgrade our swagger dependencies from `1.5.18` to `1.6.2`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by roshinisebastian** [comment]
@carlspring @sbespalov @steve-todorov I am GHC attendee. May I work on this issue?

**Comment by tanvimehta** [comment]
Is this issue available to be worked on? If so, I'd like to give it a shot

**Comment by carlspring** [comment]
Implemented by @roshinisebastian via strongbox/strongbox-parent#85.

**Comment by carlspring** [comment]
@tanvimehta : Would you like to maybe pick another task? Thanks! :)
