### ISSUE TITLE
Upgrade commons-codec:commons-codec from 1.11 to 1.15

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1859]
# Task Description

We need to upgrade `commons-codec:commons-codec` from `1.11` to `1.15`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to: #1847 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by DLambros91** [comment]
I will look into this upgrade.

**Comment by steve-todorov** [comment]
@DLambros91 are you from GHC? :)

**Comment by DLambros91** [comment]
@steve-todorov I am not, just an interested open-source contributor. If being from GHC is a requirement, you may ignore the previous message

**Comment by steve-todorov** [comment]
Thanks for your reply! The GraceHopperOSD labeled issues are only for participants in the Grace Hopper Celebration. If nobody takes this task today you can work on it tomorrow. :)

**Comment by steffisbootcampdrive** [comment]
Hello! I am with GHC. I will take this issue.

**Comment by carlspring** [comment]
Great to have you, @steffisbootcampdrive! 

Feel free to pick it up and good luck! :)

**Comment by steffisbootcampdrive** [comment]
Hello, just checking in. I looked through all of the parent folders and files and I was unable to locate a specifically commons-codec version 1.11 to update and test. I did locate commons-beanutils. Commons-codec may be a dependency located within another dependency package, perhaps commons-beanutils, I see another person has https://github.com/strongbox/strongbox/issues/1847. Would it be alright for me to work on this one as I have located this? Is there any additional information specifically for commons-codec available regarding this project specifically, I will search for this, but any assistance in locating it within the code to then update would be appreciated. Also, what is the deadline for this?

**Comment by carlspring** [comment]
Hi @steffisbootcampdrive ,

You are welcome to pick this up. What I'd do, if I were you, would be to do a:
```
mvn dependency:tree > dep.tree
```

**Comment by carlspring** [comment]
@steffisbootcampdrive ,

Any updates on this?

**Comment by flaix** [comment]
`commons-codec` is a transitive dependency only brought in from `org.apache.httpcomponents:httpclient`. It is currently (with the httpclient already upgraded to 4.5.13) at version 1.13.

**Comment by carlspring** [comment]
Thanks! Could you please try overriding the one from the `org.apache.httpcomponents:httpclient` and use the latest version of the `commons-codec`? I remember there was some vulnerability being reported by snyk.io which is why I raised this, (if I recall correctly, and it was over a month ago).

**Comment by flaix** [comment]
I can do that if you really want to, but apart from [Snyk listing](https://snyk.io/vuln/SNYK-JAVA-COMMONSCODEC-561518) this as a minor vulnerability of Information Exposure in the Base32 codec, this is already fixed in 1.13.

**Comment by carlspring** [comment]
Okay. In this case we can close this task. Thanks for looking into it! :)

**Comment by carlspring** [comment]
@flaix ,

Feel free to join our [chat channel](https://chat.carlspring.org/) where we could discuss some other tasks that you might be interested in help out with.
