### ISSUE TITLE
Upload commons-fileupload:commons-fileupload from 1.3.3 to 1.4

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1860]
# Task Description

We need to upgrade `commons-fileupload:commons-fileupload` from `1.3.3` to `1.4`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to: #1847 , #1859 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by psharma14** [comment]
Can I pick this up @carlspring ? :)

**Comment by carlspring** [comment]
Yes, please! Go for it! :)

**Comment by flaix** [comment]
Is this moving forward?

**Comment by carlspring** [comment]
@flaix ,

No, it isn't, so please, feel free to pick it up! :)

**Comment by flaix** [comment]
@carlspring , wasn't that commons-collections?

Anyhow, this should be ready for review if I understood the directions correctly.

**Comment by carlspring** [comment]
Ah, yes, you're right. You can pick that one too, if you like. :)
