### ISSUE TITLE
Upgrade commons-io:commons-io from 2.5 to 2.8.0

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1861]
# Task Description

We need to upgrade `commons-io:commons-io` from `2.5` to `2.8.0`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to: #1847 , #1859 , #1860

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by Puneethkumarck** [comment]
@carlspring I see bunch of issues related to library upgrades shall i take those upgrade for strongbox parent and test in child projects and raise pull request. as you mentioned in other issue i will wait for today GHC OSD to finish , if not done planning to pick this up tomorrow. Any comments?

**Comment by carlspring** [comment]
Hi @Puneethkumarck ,

Sounds good to me! Just wait for GHC OSD to finish today, (October 1st), and, if not taken, go for it! :)

Also, please feel free to join our [chat channel](https://chat.carlspring.org/).

**Comment by Puneethkumarck** [comment]
@carlspring shall i pick this ? if yes could you please assign me?

**Comment by carlspring** [comment]
Hi,

Please, feel free to pick this up! :)

**Comment by flaix** [comment]
This looks like it could use a push. I'll prepare a PR.

**Comment by carlspring** [comment]
Thanks, @flaix ! :)
