### ISSUE TITLE
Upgrade from commons-collections:commons-collections:3.2.2 to org.apache.commons:commons-collections4:4.4

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1862]
# Task Description

We need to upgrade `commons-collections:commons-collections:3.2.2` to `org.apache.commons:commons-collections4:4.4`. Please, note that this will probably require code changes as well.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to:  #1847 , #1859 , #1860, #1861 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by shiylxinsse** [comment]
GHC, @carlspring please assign to me this task. thank you!

**Comment by carlspring** [comment]
Hi @shiylxinsse ,

Feel free to pick it up and dig into it!

**Comment by steve-todorov** [comment]
Hey @shiylxinsse - did you perhaps forget to push your changes or maybe you are no longer interested in this task? :)

**Comment by shiylxinsse** [comment]
@steve-todorov my apologies for the late response. I'm working on it and will send a PR soon. I also noticed that the commons-collections have already been replaced with commons-collections4 in [issue-1262 PR](https://github.com/strongbox/strongbox-parent/commit/a9c01d1d5ca4fa1c09f771d933b15af9786e280b). This PR will be a minor release upgrade.

**Comment by carlspring** [comment]
Thanks for double-checking and looking into this!
I'm looking forward to seeing your pull requests! :)

**Comment by flaix** [comment]
I suggest you rename the issue to reflect that it is only an upgrade from version 4.3 to 4.4 of commons-collections4, to reflect the change properly and prevent confusion.

I'll give you a pull request for this to get things moving again.
