### ISSUE TITLE
Upgrade the maven-surefire-plugin and maven-failsafe-plugin to 3.0.0-M5

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1870]
# Task Description

We need to upgrade both plugins to version to version `3.0.0-M5`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by Someshbose** [comment]
Hi @carlspring  I want to work on this upgrade. Also need some help on testing.

**Comment by ariffebr** [comment]
kindly check this PR https://github.com/strongbox/strongbox-parent/pull/86

**Comment by ecawlfield** [comment]
Hey, is this one still up for grabs?

**Comment by carlspring** [comment]
Yes, @ecawlfield ! Please, feel free to pick it up! :)
