### ISSUE TITLE
We need to upgrade the maven-jar-plugin from 3.0.2 to 3.2.0

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1872]
# Task Description

We need to upgrade the `maven-jar-plugin` from `3.0.2` to `3.2.0`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by yuhanzz** [comment]
Hi @carlspring, I'm a GHC attendee. Can I work on this one?

**Comment by steve-todorov** [comment]
Sure! :)
