### ISSUE TITLE
Upgrade the org.codehaus.mojo:build-helper-maven-plugin from 1.9.1 to 3.2.0

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1874]
# Task Description

We need to upgrade the `org.codehaus.mojo:build-helper-maven-plugin` from `1.9.1` to `3.2.0`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by mknutsen79** [comment]
Hello I am a WSU student and would like to take this one

**Comment by liooh** [comment]
Hi, I am working in the task

**Comment by carlspring** [comment]
@liooh ,

I believe @mknutsen79 is already looking into it. Would you mind picking another one of our tasks?

**Comment by liooh** [comment]
What other task do you suggest?
