### ISSUE TITLE
Upgrade the maven-source-plugin from 2.2.1 to 3.2.1

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1875]
# Task Description

We need to upgrade the `maven-source-plugin` from `2.2.1` to `3.2.1`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by bmsbharathi** [comment]
@carlspring Can I work on this?

**Comment by steve-todorov** [comment]
@bmsbharathi Are you from GHC ?

**Comment by bmsbharathi** [comment]
@steve-todorov I am not from GHC

**Comment by carlspring** [comment]
@bmsbharathi ,

Thanks for offering to help!

All the Grace Hopper OSD 2020 tasks are marked with the label `GraceHopperOSD`, please avoid these today (the 1st of October, unless you are a participant in the event). If these are not implemented by tomorrow, then feel free to pick them up.

For more details, you can join our [chat channel](https://chat.carlspring.org/) where we can discuss what other tasks might be of interest to you. Thanks! :)

**Comment by Superbbbb** [comment]
Hi I am a GHC participant. Can I work on this issue?

**Comment by carlspring** [comment]
Hi @Superbbbb ,

Yes, please feel free to pick this up! :)

**Comment by mknutsen79** [comment]
I see this one is open again, may I take this on?

**Comment by carlspring** [comment]
Thank you, @Superbbbb ! Congratulations on your first pull request! :)
