### ISSUE TITLE
Upgrade the maven-enforcer-plugin from 3.0.0-M1 to 3.0.0-M3

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1876]
# Task Description

We need to upgrade the `maven-enforcer-plugin` from `3.0.0-M1` to `3.0.0-M3`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by MrunalRajput** [comment]
Hello! I am a Grace Hopper attendee. I would like to take this one.

**Comment by steve-todorov** [comment]
Feel free! :)

**Comment by wiltonoliveira** [comment]
Hello is the task still open? I would like to try.

**Comment by carlspring** [comment]
Ola @wiltonoliveira ! :)

Yeah, I believe @MrunalRajput is still working on it. Would you mind picking up another one of our tasks and joining our [chat channel](https://chat.carlspring.org/)?

@MrunalRajput : Would you mind confirming? I believe you still had to provide a test pull request agains the `strongbox` projec.

**Comment by wiltonoliveira** [comment]
No problem! Thank you

**Comment by carlspring** [comment]
@wiltonoliveira ,

Please, feel free to pick any other task. Thanks! :)
