### ISSUE TITLE
Upgrade the org.jacoco:jacoco-maven-plugin from 0.8.2 to 0.8.6

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1878]
# Task Description

We need to upgrade the `org.jacoco:jacoco-maven-plugin` from `0.8.2` to `0.8.6`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by cunhazera** [comment]
I can take care of it

**Comment by carlspring** [comment]
@cunhazera ,

Thanks for offering to help!

This particular task is mainly for an event that we're hosting today with the Grace Hopper Celebration Open Source Day. Would you mind holding off for day (if no one picks it up during the event, it's yours), (or picking a non-dependency/plugin upgrade task)? For more details, you can join our [chat channel](https://chat.carlspring.org/) where we can discuss what other tasks might be of interest to you. Thanks! :)

**Comment by cunhazera** [comment]
@carlspring thanks for the response. No worries at all :)
Maybe this one (https://github.com/strongbox/strongbox/issues/1873) would be better?

**Comment by tanvimehta** [comment]
I am a GHC OSD participant. I would like to work on this task

**Comment by carlspring** [comment]
Hi @tanvimehta ,

Yes, please! Go for it! :)

**Comment by carlspring** [comment]
> @carlspring thanks for the response. No worries at all :)
> Maybe this one (#1873) would be better?

Join our [chat channel](https://chat.carlspring.org/) and we'll find you something! :)

**Comment by sulemangit** [comment]
I see there is a merge (Issue#1878) , is it still open for work ??
