### ISSUE TITLE
Attach local .m2 in the docker-compose container

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1882]
# Task Description

On some occasions you would want to do `docker-compose up` to do a quick build.
However, the current `docker-compose.yaml` file in strongbox/strongbox does not contain the local `.m2` which might lead to exceptions like
```
strongbox-from-web-core_1 | [FATAL] Non-resolvable parent POM for org.carlspring.strongbox:strongbox-masterbuild:1.0-SNAPSHOT: Failure to find org.carlspring.strongbox:strongbox-parent:pom:1.0-issue-1877-upgd-dep-SNAPSHOT in http://repo.carlspring.org/content/groups/carlspring was cached in the local repository, resolution will not be reattempted until the update interval of carlspring has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 8, column 13
```

An example fix is available here:
https://github.com/strongbox/strongbox-web-integration-tests/blob/master/sbt/docker-compose.yml

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by hirva10** [comment]
Can I take this up?
