### ISSUE TITLE
UI breaks for storages on some resolutions

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1887]
# Bug Description

The Storage page has some issues when displaying under some resolutions like `2560 x 1600`.

# Screenshots

![Snip20201001_105](https://user-images.githubusercontent.com/2303663/94879105-f5634b80-0467-11eb-8e9e-f82a3b82de20.png)

**Comment by pavluchenko** [comment]
Hi, could you assign this issue to me, please? I want to fix it

**Comment by carlspring** [comment]
Hello @pavluchenko ,

Feel free to pick this up! :)

**Comment by jain13tushar** [comment]
Hi @carlspring and @steve-todorov ,

I tried to build your project and I'm getting build failure after properly checking the settings.xm

![image](https://user-images.githubusercontent.com/41324499/94990502-48d5b680-059a-11eb-8999-d9fa81e90039.png)

Can you please help me with the build ?

Regards,
Tushar

**Comment by steve-todorov** [comment]
@jain13tushar thanks for your interest! However, this task is assigned to @pavluchenko. Can you check another one? 

As for your build issue - check the developer guide in our docs: https//strongbox.carlspring.org . You likely are hitting either the long path issue in windows or are using jdk > 8. Join our [chat](https://chat.carlspring.org) for help.

**Comment by carlspring** [comment]
@pavluchenko ,

Any updates on this?

**Comment by raw-letisso** [comment]
Hi everyone, i tried to reproduce this bug but it did not. Is this bug still actual?

**Comment by carlspring** [comment]
Hi @raw-letisso ,

Under what resolutions did you try it?

**Comment by raw-letisso** [comment]
@carlspring 
am, i install window resizer in chrome extensions and tried in there

**Comment by carlspring** [comment]
Under what resolutions? Also, have you tried actually changing to that resolution as well?

**Comment by raw-letisso** [comment]
in settings screen resolution is 1920x1080
No, i didn't try change actually

**Comment by carlspring** [comment]
Well, the resolution under which this is known to happen is 2560 x 1600.

**Comment by steve-todorov** [comment]
Hey @raw-letisso, yes this issue is indeed active. You can try with resolutions which are lower than like `1280x768` maybe? I was able to reproduce it a while ago using `Ctrl ++` to zoom the page.

**Comment by raw-letisso** [comment]
Thank you @steve-todorov 
Yes, then i increase zoom of page some visual problems stats to appear
then i decrease zoom nothing, and that's why i was confused
