### ISSUE TITLE
Remove the version from the env vars used in strongbox-web-integration-tests and ci-build-images

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1905]
# Task Description

The [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests) project depends on these environment variables to work:

```
# S-W-I-T expects these environment variables to be set.
ENV NUGET_V3_VERSION=$NUGET_VERSION
ENV NUGET_V3_PATH=$NUGET_PATH
ENV NUGET_V3_EXEC="mono ${NUGET_PATH}"
```

We need to remove the `V3` part from the environment variable so that it becomes:
```
ENV NUGET_VERSION=X.Y.Z
ENV NUGET_PATH=/x/y/z
ENV NUGET_EXEC=mono ${NUGET_PATH}
```

This change is necessary to allow for different major versions to  be used without the needing of code changes.

# Tasks

The following tasks will need to be carried out:
* [ ] Replace environment usages in [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests)
* [ ] Replace environment usages in [ci-build-images](https://github.com/strongbox/ci-build-images)  (`Dockerfile`s and scripts)

# Task Relationships

This task:
* Relates to:  #1829 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov

**Comment by j4ckofalltrades** [comment]
@steve-todorov I'd like to take this on. Can you assign this issue to me? Thanks.

**Comment by steve-todorov** [comment]
I've merged your other change in the master branch. Feel free to start working on this :)

**Comment by j4ckofalltrades** [comment]
Cool, thank you.
