### ISSUE TITLE
Upgrade our Jersey dependencies from 2.23.1 to 2.32

### ISSUE THREAD

**Issue by ptirador** [strongbox/strongbox#1910]
# Task Description

We need to upgrade our `jersey` dependencies from `2.23.1` to `2.32`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* It's dependent of: #1851 

# Useful Links

* [Migrating to Jersey 2.32](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/migration.html#mig-2.26)

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by liooh** [comment]
Hi, I'm interested in working on this task, can it be part of the issues for hacktoberfest?

**Comment by carlspring** [comment]
Hi @liooh ,

Pablo is already working on a fix for this. Would you like to pick another task and to join our [chat channel](https://chat.carlspring.org/) where we can discuss what other tasks you could pick?
