### ISSUE TITLE
Upgrade the maven-dependency-plugin from 3.1.1 to 3.1.2

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1941]
# Task Description

We need to upgrade `maven-dependency-plugin:3.1.1` to version `3.1.2`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by SolangeUG** [comment]
Hi @carlspring ,
If that is alright with you, I can take this one, as it's very similar to the [one I just completed][1].

[1]: https://github.com/strongbox/strongbox/issues/1871

**Comment by carlspring** [comment]
Hey, @SolangeUG !

I actually did this one earlier in strongbox/strongbox-parent#127.

**Comment by SolangeUG** [comment]
Cool, thanks! I will pick up another one! 😄

**Comment by carlspring** [comment]
Thanks and sorry about that! I've sent you a few you might be interested in in the chat.
