### ISSUE TITLE
Upgrade Travis CI to use JDK 8 >= 222

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1956]
# Task Description

Since we are now enforcing JDK versions, we need to upgrade our `.travis.yml` setup so it uses a MacOS instance which has JDK 8 >= update 222 so that the build can pass.

Check [strongbox/strongbox-parent#pom.xml](https://github.com/strongbox/strongbox-parent/blob/master/pom.xml#L425)

# Task Relationships

This task:
* Relates to: #1864, #1865

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring 
  * @steve-todorov

**Comment by j4ckofalltrades** [comment]
@steve-todorov 

I can take a look at this. Not sure how I can test it out though...

**Comment by steve-todorov** [comment]
@j4ckofalltrades if you fork the project, you should be able to setup Travis to run builds for your fork. Normally you'd add your fork from the [Dashboard](https://travis-ci.com/dashboard) or by [syncing your account](https://travis-ci.com/account/repositories). It should directly pickup the `.travis.yml` file and start a build but first you need to have the fork repository registered in Travis (and then unregister it when you are done) :)
