### ISSUE TITLE
Upgrade our mkdocs-material docker image to the latest 6.x version and fix any potential issues

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1957]
# Task Description

Upgrade our mkdocs docker image to the latest [mkdocs-material - 6.1.4](https://github.com/squidfunk/mkdocs-material) version.
The `Dockerfile` is located in our [strongbox/ci-build-images](https://github.com/strongbox/ci-build-images/blob/master/images/mkdocs/Dockerfile.mkdocs) repository.

# Tasks

The following tasks will need to be carried out:
* [ ] Upgrade our mkdocs docker image to [mkdocs-material - 6.1.4](https://github.com/squidfunk/mkdocs-material). 
* [ ] Check if the design is not broken after the changes (netlify automatically deploys a live preview upon each PR/push; or you can use the `docker-compose` to start the new image locally)

# Useful Links

* [Material for MkDocs Changelog](https://squidfunk.github.io/mkdocs-material/changelog/#614-_-november-7-2020)
* [Material for MkDocs Documentation](https://squidfunk.github.io/mkdocs-material/getting-started/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov

**Comment by Suiiyush** [comment]
May I work on this issue?

**Comment by carlspring** [comment]
Hi @Suiiyush ,

Thanks for offering to help! Feel free to pick this up! :)

**Comment by steve-todorov** [comment]
It looks like @sroopsai has already created a PR for this which seems to be complete. @Suiiyush could you please pick another task to avoid duplicating PRs?

**Comment by Suiiyush** [comment]
Yeah no problem

**Comment by Rprabudeva** [comment]
I would like to contribute this one

**Comment by carlspring** [comment]
@Rprabudeva ,

Thanks for offering, but, as you can see above, there's already someone working on it. Would you mind picking up another task?
