### ISSUE TITLE
MavenProxyRepositoryProviderTestIT failing test cases

### ISSUE THREAD

**Issue by j4ckofalltrades** [strongbox/strongbox#1958]
# Task Description

Fix the failing test cases in MavenProxyRepositoryProviderTestIT

- whenDownloadingArtifactMetadaFileShouldAlsoBeResolved()
- whenDownloadingArtifactDatabaseShouldBeAffectedByArtifactEntry()
- whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist()
- testMavenCentral()

Error logs:

```java
whenDownloadingArtifactMetadaFileShouldAlsoBeResolved()
...
java.io.IOException: Unreadable response for org/carlspring/properties-injector/1.1/properties-injector-1.1.jar. Response status is 401
at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:76)

---

whenDownloadingArtifactDatabaseShouldBeAffectedByArtifactEntry()

java.io.IOException: Unreadable response for org/carlspring/properties-injector/1.6/properties-injector-1.6.jar. Response status is 401
at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:76)

---

whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist()
...
java.io.IOException: Unreadable response for javax/interceptor/javax.interceptor-api/1.2.2/javax.interceptor-api-1.2.2.jar. Response status is 401
at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:76)

---

testMavenCentral()
...
java.io.IOException: Unreadable response for org/carlspring/maven/derby-maven-plugin/maven-metadata.xml. Response status is 401
at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:76)
```

# Other info

[Travis build log](https://travis-ci.org/github/j4ckofalltrades/strongbox/builds/743618927)

JDK version:
```
$ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```

# Task Relationships

This task:
* Relates to: #1956 

# Useful Links

* [Related Travis-CI build](https://travis-ci.org/github/j4ckofalltrades/strongbox)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by j4ckofalltrades** [comment]
This seems like a permissions issue for the repo at [repo.spring.io](https://repo.spring.io/libs-release/org/carlspring/) which returns a HTTP 401 error.

I'm able to access the [Maven Central repo](https://repo1.maven.org/maven2/org/carlspring/) without any issues.

**Comment by carlspring** [comment]
The https://repo.spring.io/ repositories now appear to expect you to be logged in. This seems to be some recent change.

@j4ckofalltrades : Could you please try using one of Google's mirrors (for example the EU one) like this: https://storage-download.googleapis.com/maven-central/index.html, or, even better try accessing it via Bintray? (I don't have the exact URL, but I know that JFrog are mirroring Maven Central.

**Comment by j4ckofalltrades** [comment]
That did the trick and the Travis CI build's also passing now. I've updated the linked pr in #1956.

**Comment by carlspring** [comment]
Awesome! I'm glad it worked! :)
