### ISSUE TITLE
Make the controllers use constants instead of hard-coded values for the HTTP response codes

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1978]
# Task Description

There are many places across the controllers where the numeric response codes are hard-coded like this:

```java
    @ApiResponses(value = { @ApiResponse(code = 200, message = "The list was returned."),
                            @ApiResponse(code = 500, message = "An error occurred.") })
```

We should use constants for these.

The controllers are located under `strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers`.

# Tasks

The following tasks will need to be carried out:
* [ ] Find which class to use these contants from (`org.springframework.http.HttpStatus`?).
* [ ] Refactor the code to use constants, instead of hard-coded ones.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by bhargav-khalasi** [comment]
@carlspring I am interested in working on this issue. Let me know when can I start working on the same.

**Comment by sainup** [comment]
@carlspring I am interested too if anyone isn't working on it. I would very much like to help as I am beginner and it would help me with learning. Thank you!

**Comment by anishansu100** [comment]
@carlspring  I am interested as well as for it would be good starting point for me to learn as a beginner while gain experience in the open source environment

**Comment by shaxxs** [comment]
Hello, since anyone started this task, I take it, it would be done in an hour :)

**Comment by carlspring** [comment]
Thanks and good luck!

**Comment by brendoncheung** [comment]
Hello, I'm trying to work on this and is this even possible? I kept getting the error that the value must be a constant

**Comment by steve-todorov** [comment]
Hi @shaxxs and everybody involved!

We are sorry but it looks like this task will introduce more problems than it will actually fix (i.e. make the code much harder to read and possibly add conflicts by using wrong imports). Therefore we'll be marking this as `won't fix` and closing the task and the PR submitted by @shaxxs. Apologies for this!

Thanks for your time and contribution!
