### ISSUE TITLE
Fix `Port 48080 was already in use.`

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1983]
# Bug Description

Strongbox distribution fails with `Port 48080 was already in use.`

# Steps To Reproduce

1. Run distribution with `./bin/strongbox console`
2. Startup process failed with following exception: 
```
Web server failed to start. Port 48080 was already in use.
```
# Task Relationships

This bug:
* Relates to:  #1676

**Comment by steve-todorov** [comment]
Thanks for fixing this! Closing. :)
