### ISSUE TITLE
Unable to clone repository on Windows - filename too long error

### ISSUE THREAD

**Issue by GligorAvram** [strongbox/strongbox#1991]
# Bug Description

When I tried to clone the repository on Windows 7 and 10 I receive some "filename too long" errors.

# Steps To Reproduce

1. Use IntelliJ or Git to clone the repository on Windows

# Expected Behavior
Cloning git successful 

# Screenshots
![strongbox bug](https://user-images.githubusercontent.com/23247516/118855330-55670f00-b8de-11eb-8b7b-78c20c776943.png)

# Environment
Windows 7 & 10

* Strongbox Version: n/a
* OS: Windows 7 & 10
* Maven version (please provide the full output of `mvn --version`): n/a
* Browser (if related to UI):  n/a

**Comment by steve-todorov** [comment]
Thanks for submitting this issue, but I'm afraid you haven't read the [developer guide](https://strongbox.github.io/developer-guide/building-the-code.html#common-build-problems). This is not a bug and is not something we can fix. It's a Windows issue.
