### ISSUE TITLE
Please add support for yandex OTP

### ISSUE THREAD

**Issue by realtonyig** [strongbox/strongbox#1992]
# Task Description
Recently, keepass plugin KeePassOTP added the support for yandex OTP.  Is it possible that strongbox adds the same feature?

# Tasks

The following tasks will need to be carried out:
* [ ] Task 1
* [ ] Task 2
* [ ] Task 3

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: 
* Is a follow-up of: 
* Relates to:

# Useful Links

* [KeePassOTP](https://github.com/Rookiestyle/KeePassOTP/releases)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project. I assume you're referring to the [strongbox-password-safe/Strongbox project](https://github.com/strongbox-password-safe/Strongbox). I'm therefore closing this bug report.

Kind regards,

Martin

**Comment by realtonyig** [comment]
Hi Martin,

Oh, I'm so sorry for the mistake. 
I've posted it to the right place. Thank you.

Best Regards,
Tony

**Comment by carlspring** [comment]
No problem! :)
