### ISSUE TITLE
Feature request: Password (not PIN code numbers)

### ISSUE THREAD

**Issue by belinsky874** [strongbox/strongbox#1997]
~Hello! I am strongly considering to take the plunge on the pro app, but I would like the PIN code to also have a password option, not just numbers.~

~If you plan to include this in the future, may I ask how long it would take to make a feature like this? No rush of course but I am curious if it will be easier because the app already has PIN numbers.~

Sorry, wrong repo!

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project. I assume you're referring to the [strongbox-password-safe/Strongbox project](https://github.com/strongbox-password-safe/Strongbox). I'm therefore closing this bug report.

Kind regards,

Martin
