### ISSUE TITLE
Strongbox 1.16.13 crashes when creating a new password entry

### ISSUE THREAD

**Issue by ryanberckmans** [strongbox/strongbox#1999]
# Bug Description

Describe the bug/issue you have.

Since new UI/big update, create any new entry, click apply changes or click "generate password", hard crash. Macbook Air M1 latest update

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project. I assume you're referring to the [strongbox-password-safe/Strongbox project](https://github.com/strongbox-password-safe/Strongbox). I'm therefore closing this bug report.

Kind regards,

Martin

**Comment by ryanberckmans** [comment]
Thank you

**Comment by carlspring** [comment]
No problem! :)
