### ISSUE TITLE
UX: Create New Record --> Create New Account

### ISSUE THREAD

**Issue by elharo** [strongbox/strongbox#2000]
# Bug Description

The tooltip on the key icon says "Create New Record"

Describe the bug/issue you have.

This has two problems:

1. The corresponding menu item is "Create New Entry" (not record)
2.  "Record" is not a term understood by non-developer end users. "Entry" is only marginally better.

Both should probably be "Create New Account". Perhaps someone can think of a better word here than "Account" but "Record" should definitely be changed. 

# Steps To Reproduce
Mouse over the key

# Expected Behavior

# Screenshots

![image](https://user-images.githubusercontent.com/1005544/177161871-8556daa6-400d-42b6-8105-b48cb19a6cea.png)

# Environment

Mac OS X 10.14

* Strongbox Version: 
* OS: 

1.17.1

* [link1]()
* [link2]()
* [link3]()

# Task Relationships

This bug:
* Is caused by: 
* Relates to: 
* Depends on:

**Comment by nilanjanH** [comment]
@elharo - I am new to OSS & would like to work on this issue.
Thanks.

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project. I assume you're referring to the [strongbox-password-safe/Strongbox project](https://github.com/strongbox-password-safe/Strongbox). I'm therefore closing this bug report.

Kind regards,

Martin
