### ISSUE TITLE
Have a title displayed other than the db name

### ISSUE THREAD

**Issue by amund-ersland** [strongbox/strongbox#2002]
In e.g. keepassxc, it is possible to name the database, and thereby have the name displayed in the tab. If no name is given, the filename is displayed. As far as I can see,  the title is the same as the db name (without .kdbx). 

It would be nice to be able to set the name of db explicetly.

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project. I assume you're referring to the [strongbox-password-safe/Strongbox project](https://github.com/strongbox-password-safe/Strongbox). I'm therefore closing this bug report.

Kind regards,

Martin

**Comment by amund-ersland** [comment]
ah I see, sorry, thank you for pointing it out
