### ISSUE TITLE
Native macOS Universal AutoFill leaving the 'password' field blank on some websites

### ISSUE THREAD

**Issue by seakrebel** [strongbox/strongbox#2007]
# Bug Description

Native macOS (Universal) AutoFill leaving the 'password' field blank despite having everything correctly configured.
While it works fine on some other websites, there are still many where the AutoFill is broken.
I understand some websites don't have the optimal HTML forms that would be easily recognized by password managers, but this is something else, because it works with the Apple Passwords app.

# Steps To Reproduce

1. Create an entry in Strongbox for e.g. https://jack-wolfskin.de with an username/password combination for testing
2. Turn on AutoFill for Strongbox and Strongbox only (both in System Settings on macOS and Strongbox > Database)
3. Make sure AutoFill 'User names and passwords' is enabled in Safari.
4. Go to e.g. https://jack-wolfskin.de and try to AutoFill username and password

# Expected Behavior

Expected would be as in Apple Passwords, if you do the following:

1. Create an entry in Apple Passwords for e.g. https://jack-wolfskin.de with an username/password combination for testing
2. Turn on AutoFill for Passwords and Passwords only in System Settings
3. Make sure AutoFill 'User names and passwords' is enabled in Safari.
4. Go to e.g. https://jack-wolfskin.de and try to AutoFill username and password

# Screenshots

https://github.com/user-attachments/assets/961186f4-0081-4a53-abe1-f81add432bee

# Environment

* Strongbox Version: com.markmcguill.strongbox [1.60.23 (5648)-P]
* OS: MacOS Version 15.0.1 (Build 24A348)

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project. I assume you're referring to the [strongbox-password-safe/Strongbox project](https://github.com/strongbox-password-safe/Strongbox). I'm therefore closing this bug report.

Kind regards,

Martin
