### ISSUE TITLE
Implement a validator which only accepts lowercase artifactId-s

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#365]
This validator should be applicable for Maven repositories. It should check that the `artifactId` component of the `path` is lowercase.

For more information, check the `strongbox-storage-api` module under the `org.carlspring.strongbox.storage.validation` package.

This task is similar to #366.

**Comment by Matthew-Kwan** [comment]
Hi, this is my first time attempting to help out with a project on github. I would like to get a better understanding of this problem so I can help you fix it as well as fix #366. I'm looking at ArtifactsOperationsValidator.java right now and I'm not sure what I have the freedom to do or what exactly it is I should be doing. Particularly what the artifactId component of the path is. Any help would be appreciated!

**Comment by carlspring** [comment]
Hi!

Thanks for offering to help !

If you decide to pick this task, I would recommend that you also pick #366, as these two tasks aalmost the same.
Have a look at [this](https://github.com/strongbox/strongbox/blob/2fd5ad3562e84bc8535da7932cde4eb2fb05a8ad/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/storage/validation/version/VersionValidator.java) and the classes implementing and using it in order to get a rough idea of how things work.

Let me knowLet we know,, if you have any questions.

I would recommend that you create your own fork and work with a branch based on that.

**Comment by Matthew-Kwan** [comment]
Thanks for the tips Martin! I'll take a look at both the links you sent. I'll attempt to resolve the issue in my fork sometime soon this week.

**Comment by Matthew-Kwan** [comment]
Hi Martin,

I had a question. Am I supposed to create a new java file to implement this validator or add on to an existing file?

Thanks!

Mattthew

**Comment by carlspring** [comment]
Hi,

You will have to create a new one.

**Comment by carlspring** [comment]
Under the strongbox-maven-layout-provider module.

**Comment by carlspring** [comment]
@Matthew-Kwan ,

BTW, you may want to join our [chat](https://gitter.im/strongbox/strongbox).

**Comment by carlspring** [comment]
@Matthew-Kwan,

@dinesh19aug is already working on these two validators in #410 . Perhaps you would like to pick another task?

**Comment by carlspring** [comment]
Implemented in #416.
