### ISSUE TITLE
Implement a validator which only accepts lowercase groupId-s

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#366]
This validator should be applicable for Maven repositories. It should check that the `groupId` component of the `path` is lowercase.

For more information, check the `strongbox-storage-api` module under the `org.carlspring.strongbox.storage.validation` package.

This task is similar to #365.

**Comment by dinesh19aug** [comment]
Opened a pull request. @carlspring  Please review if it looks good, I will add a vlaidator for #365 as well

**Comment by carlspring** [comment]
Implemented in #416.
