### ISSUE TITLE
Rename the 'repository.config.xml' property to 'strongbox.config.xml'

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#367]
Currently, all the project's properties are prefixed with `strongbox.*` and this is the only property in the that does not conform with the convention.

Tasks:
* The code of the project will have to be scanned for occurrences of this and they should be replaced.
* Building and executing the following projects should pass:
  * [strongbox](https://github.com/strongbox/strongbox/)
  * [strongbox-webapp](https://github.com/strongbox/strongbox-webapp/)
  * [strongbox-assembly](https://github.com/strongbox/strongbox-assembly/)
* Updated the [Application Properties](https://github.com/strongbox/strongbox/wiki/Application-Properties) page.

**Comment by IIEleniII** [comment]
Hello @carlspring . I'm new to GitHub and i'd like to help with the issue you opened.
But first i'd like to ask a few questions to see if i understood correctly.
1.You want to replace  strongbox-any method it has with the conventional one?
2.What is the name of the  conventional one?
Looking forward to yr reply=)

**Comment by carlspring** [comment]
@IIEleniII ,

You will have to have a look at the code and search for the `repository.config.xml` property, in order to find all the places it's used and replace them. This could be both in source and resource files.

Does this answer your question?
Kind regards,

Martin

**Comment by IIEleniII** [comment]
Yes! Thank you for the detailed answer!
I would like to do that.
Is next Sunday OK for me to finish?

**Comment by carlspring** [comment]
Sure, take your time.

**Comment by Matthew-Kwan** [comment]
Hi, just wondering but has this been completed yet?

**Comment by carlspring** [comment]
Implemented by @sanket407 in #439.
