### ISSUE TITLE
Add ICLA links to all strongbox projects pointing to the one in the strongbox project

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#368]
Just copy the ICLA.md file from this project into all of the projects in this organization.

**Comment by adityasrini** [comment]
I can work on this! It's been open for a while and I feel that this is too straightforward to not work on!

**Comment by steve-todorov** [comment]
Nobody seems to be working on this so it's yours! :)

**Comment by syakubov** [comment]
I take it that this still needs to be done?

**Comment by brunocriado** [comment]
Hey,

I'm reviewing some *good first issue* tickets and looks like we can close that one once we have some repo that was archived. 

Thoughts?

**Comment by carlspring** [comment]
This task is obsolete. Thanks!
