### ISSUE TITLE
Replace the implementation="file-system" with data-store="file-system" + package renaming

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#371]
* Replace the `implementation="file-system"` with `data-store="file-system"`.
* Replace the `org.carlspring.strongbox.providers.storage` with `org.carlspring.strongbox.providers.datastore`.

**Comment by PradnyaBora** [comment]
I  have started working on this issue

**Comment by carlspring** [comment]
Hi!

Great! Thanks!

Let me know, if you need any help!

**Comment by PradnyaBora** [comment]
I made changes but how do I do build to test.

**Comment by carlspring** [comment]
Have you checked the [wiki](https://github.com/strongbox/strongbox/wiki)? More specifically, the [Building the code](Building the code) page? Please, have a look at the wiki. I believe it should have more than enough to get you started.

**Comment by carlspring** [comment]
@PradnyaBora ,

Have you been able to build the code?

**Comment by carlspring** [comment]
@PradnyaBora ,

Any update on this?

**Comment by PradnyaBora** [comment]
I committed 7 files today but it is showing 105 files changes in my fork. I am not understanding. Also my changes were not reflected.
Kindly help.

**Comment by carlspring** [comment]
@PradnyaBora ,

I appreciate your efforts, but if you would like to contribute to projects on Github, you will have to learn how to use Git, Github and how forks and pull requests work.

Your fork needs to be in sync with ours. In your case your `master` will have to be in sync with ours. Then you need to commit and push to your fork. Once you're done and the code compiles and the tests pass, you can create a pull request in order to get your changes accepted into our `master`.

**Comment by carlspring** [comment]
Fixed in #400 and #402.
