### ISSUE TITLE
Upgrade org.springframework:* to >= 5.0.2.RELEASE

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#403]
Upgrade the standard Spring dependencies to >= `5.0.2.RELEASE`.

Make sure that:
- The project still builds
- The tests are still passing

The version is controlled via the `strongbox-parent/pom.xml`.

(This should not include the `spring-data` and `spring-security-*` ones).

**Comment by deannaji** [comment]
Hi there,
I'm trying to build the original project on my machine first, but I'm still facing an error in (strongbox:commons) module. I'm using:
- Java 1.8
- Maven 3.3.9

The log:
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Strongbox: Commons 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ strongbox-commons ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ strongbox-commons ---
[INFO] ShortRevision tag detected. The value is '16'.
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify --short=16 HEAD"
[INFO] Working directory: C:\OITdevEnv\home\Java-development\strongbox-home\strongbox-master\strongbox-commons
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Strongbox: Parent .................................. SUCCESS [  0.096 s]
[INFO] Strongbox: Resources [Common] ...................... SUCCESS [  0.861 s]
[INFO] Strongbox: Resources [Storage API] ................. SUCCESS [  0.063 s]
[INFO] Strongbox: Resources [Storage] ..................... SUCCESS [  0.000 s]
[INFO] Strongbox: Resources [Web] ......................... SUCCESS [  0.190 s]
[INFO] Strongbox: Resources ............................... SUCCESS [  0.000 s]
[INFO] Strongbox: Data Service ............................ SUCCESS [  2.085 s]
[INFO] Strongbox: Commons ................................. FAILURE [  0.297 s]
[INFO] Strongbox: Configuration ........................... SKIPPED
[INFO] Strongbox: Metadata [Maven API] .................... SKIPPED
[INFO] Strongbox: Event API ............................... SKIPPED
[INFO] Strongbox: Authentication API ...................... SKIPPED
[INFO] Strongbox: Client .................................. SKIPPED
[INFO] Strongbox: Testing [Core] .......................... SKIPPED
[INFO] Strongbox: Security API ............................ SKIPPED
[INFO] Strongbox: User Management ......................... SKIPPED
[INFO] Strongbox: Authentication Provider [Default] ....... SKIPPED
[INFO] Strongbox: Authentication Support .................. SKIPPED
[INFO] Strongbox: Authentication Provider [LDAP] .......... SKIPPED
[INFO] Strongbox: Authentication Providers ................ SKIPPED
[INFO] Strongbox: Authentication Registry ................. SKIPPED
[INFO] Strongbox: Security ................................ SKIPPED
[INFO] Strongbox: Storage [Core] .......................... SKIPPED
[INFO] Strongbox: Testing [Storage] ....................... SKIPPED
[INFO] Strongbox: Storage [API] ........................... SKIPPED
[INFO] Strongbox: Cron [API] .............................. SKIPPED
[INFO] Strongbox: Cron [Tasks] ............................ SKIPPED
[INFO] Strongbox: REST Client ............................. SKIPPED
[INFO] Strongbox: Storage [Maven Layout Provider] ......... SKIPPED
[INFO] Strongbox: Storage [Nuget Layout Provider] ......... SKIPPED
[INFO] Strongbox: Testing [Web] ........................... SKIPPED
[INFO] Strongbox: Testing ................................. SKIPPED
[INFO] Strongbox: Storage [NPM Layout Provider] ........... SKIPPED
[INFO] Strongbox: Storage [P2 Layout Provider] ............ SKIPPED
[INFO] Strongbox: Web Core ................................ SKIPPED
[INFO] Strongbox: Cron [REST] ............................. SKIPPED
[INFO] Strongbox: Cron .................................... SKIPPED
[INFO] Strongbox: Storage Layout Providers ................ SKIPPED
[INFO] Strongbox: Storage ................................. SKIPPED
[INFO] Strongbox: Masterbuild ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.905 s
[INFO] Finished at: 2017-12-19T11:10:14-08:00
[INFO] Final Memory: 45M/407M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project strongbox-commons: Cannot get the revision information from the scm repository :
[ERROR] Exception while executing SCM command. Error while executing command. Error while executing process. Cannot run program "git" (in directory "C:\OITdevEnv\home\Java-development\strongbox-home\strongbox-master\strongbox-commons"): CreateProcess error=2, The system cannot find the file specified
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :strongbox-commons

Can you please help me build the project?

Thanks
Dean

**Comment by carlspring** [comment]
You need to have the git binary on your PATH variable.

**Comment by carlspring** [comment]
Implemented by @epidemia .
