### ISSUE TITLE
Upgrade the logging dependencies to the latest

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#405]
We need to upgrade the versions of the following dependencies to their latest compatible versions:
* `org.slf4j:jcl-over-slf4j:${version.jcl}`
* `org.slf4j:jul-to-slf4j:${version.jcl}`
* `ch.qos.logback:logback-core:${version.logback}`
* `ch.qos.logback:logback-classic:${version.logback}`

Make sure that:
* The project still builds
* The tests are still passing

The version is controlled via the `strongbox-parent/pom.xml`.

**Comment by epidemia** [comment]
#442 You can close this issue.

**Comment by carlspring** [comment]
Thanks a lot for this!
