### ISSUE TITLE
Upgrade the version of Jetty to >= 9.4.8.v20171121

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#407]
We need to upgrade to the latest version of Jetty.

Make sure that:
* The project still builds
* The tests are still passing

The version is controlled via the `strongbox-parent/pom.xml`.

The webapp can be executed using:

```
mvn clean install
cd strongbox-web-core
mvn clean package -Pjetty-block
```

If Jetty is starting the webapp correctly, then things should be alright. To test things, try accessing:
http://localhost:48080/configuration/strongbox/xml with `admin`/`password` -- an XML with the configuration of the server should be presented, upon successful login.

**Comment by sanket407** [comment]
Started working on this !

**Comment by sanket407** [comment]
Expecting to finish in a day !

**Comment by carlspring** [comment]
Great! Thanks!

**Comment by carlspring** [comment]
Relates to #421 , #422.
