### ISSUE TITLE
Upgrade org.apache.httpcomponents:* to >= 4.5.4

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#408]
We need to upgrade to the latest version of Jetty.

Make sure that:
* The project still builds
* The tests are still passing

The version is controlled via the `strongbox-parent/pom.xml`.

**Comment by dinesh19aug** [comment]
Created a pull request with #366 fix. Updated the version to 4.5.4. The tests were successful.

**Comment by dinesh19aug** [comment]
Rolled back changes. The change builds fine(all test cases pass) on my machine but fails in Jenkins

**Comment by carlspring** [comment]
BTW, you may want to join our [chat](https://gitter.im/strongbox/strongbox).

**Comment by carlspring** [comment]
@dinesh19aug,

BTW, you may want to join our [chat](https://gitter.im/strongbox/strongbox).

**Comment by carlspring** [comment]
Blocked by https://github.com/jersey/jersey/issues/3629.

**Comment by carlspring** [comment]
There is now a `4.5.5`.

**Comment by carlspring** [comment]
@ptirador,

Would you like maybe to look into this?

**Comment by ptirador** [comment]
Yeah, sure! I'll look into it.

**Comment by carlspring** [comment]
Fixed by @ptirador! :)
