### ISSUE TITLE
Fix error 500 response when calling the REST API for a non-existing directory in a Maven repository

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#418]
**Steps to reproduce**
1. Compile the project (https://github.com/strongbox/strongbox/wiki/Building-the-code#building)
2. Run jetty server (https://github.com/strongbox/strongbox/wiki/Building-the-code#running-jetty-in-blocked-mode)
3. Visit for example http://localhost:48080/storages/storage-common-proxies/maven-central/pl/fuss/

**Problem**
See StackTrace at https://gist.github.com/fuss86/df8bdc5454d6e5da7e4fbf6a34f5cf4c

**Expected result**
404 HTTP response

**Comment by carlspring** [comment]
Resolved in #463 by @sanket407.
