### ISSUE TITLE
Fix error 500 response when calling the REST API for a non-existing artifact in a non-existing directory in a Maven repository

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#419]
**Preface**
Similar to #418 

**Steps to reproduce**
1. Compile the project (https://github.com/strongbox/strongbox/wiki/Building-the-code#building)
2. Run jetty server (https://github.com/strongbox/strongbox/wiki/Building-the-code#running-jetty-in-blocked-mode)
3. Visit for example http://localhost:48080/storages/storage-common-proxies/maven-central/pl/fuss/mummy.jar

**Problem**
See StackTrace at https://gist.github.com/fuss86/6dc5a586064d0224042e1ca947c42cde

**Expected result**
404 HTTP response

**Comment by carlspring** [comment]
Resolved in #463 by @sanket407.
