### ISSUE TITLE
Fix error 500 response when calling the REST API for an invalid artifact in an existing directory in a Maven repository

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#420]
**Similar to**
#418 and #419 

**Steps to reproduce**
1. Compile the project (https://github.com/strongbox/strongbox/wiki/Building-the-code#building)
2. Run jetty server (https://github.com/strongbox/strongbox/wiki/Building-the-code#running-jetty-in-blocked-mode)
3. Visit 2 locations one by one:
* http://localhost:48080/storages/storage-common-proxies/maven-central/org/carlspring/maven/derby-maven-plugin/1.8/derby-maven-plugin-1.8.jar
* http://localhost:48080/storages/storage-common-proxies/maven-central/org/carlspring/maven/derby-maven-plugin/1.8/derby-maven-plugin-5.0.jar

**Problem**
See StackTrace at https://gist.github.com/fuss86/6bc6b1071b452588075a31776e044317

**Expected result**
404 HTTP response

**Comment by carlspring** [comment]
Resolved in #463 by @sanket407.
