### ISSUE TITLE
Update jetty to version >= 9.4.7.v20170914

### ISSUE THREAD

**Issue by sanket407** [strongbox/strongbox#422]
We need to upgrade to the latest version of Jetty.

Make sure that:

* The project still builds
* The tests are still passing
* The version is controlled via the strongbox-parent/pom.xml.

The webapp can be executed using:

```
mvn clean install
cd strongbox-web-core
mvn clean package -Pjetty-block
```

If Jetty is starting the webapp correctly, then things should be alright. To test things, try accessing:
http://localhost:48080/configuration/strongbox/xml with admin/password -- an XML with the configuration of the server should be presented, upon successful login.

Note : Jetty 9.4.7 and 9.4.8 builds the web app correctly. The tests pass too. The issue is that the Jetty server does not start at the end for deploying web app. Note that jetty v9.4.8 requires maven 3.5.0.

**Comment by carlspring** [comment]
Relates to #421.

**Comment by deannaji** [comment]
Hi,
Can I  try working on this?

Thanks
Dean

**Comment by carlspring** [comment]
Sure, you can give it a go!

**Comment by samsony17** [comment]
@carlspring  Is this still an issue? Based on my observations I was able to view the server configuration XML after logging into http://localhost:48080/api/configuration/strongbox
