### ISSUE TITLE
When uploading a new Maven artifact, if it's an archive (jar, war, zip, etc) add it's classes to the index

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#427]
The Maven 2.0 layout provider uses the [Maven Indexer](https://github.com/strongbox/strongbox/wiki/Maven-Indexer), in addition to OrientDB as it's place for storing useful information about the artifacts.

We need to be able to keep a record of the `.class` files discovered in the common Maven archive formats (`jar`, `war`, etc).

What needs to be done:
* Make sure classes are added to the Lucene (Maven Indexer) local index
* Make it possible to use the `MavenIndexerSearchProvider` to search by `class`
* Implement test cases
  * Generate a test jar with several class files on it (via your tests)
  * Add the artifact to the Maven Indexer local index
  * Search for the class and assert there are results which match the criteria

The code for this will have to be placed under the `strongbox/strongbox-storage/strongbox-storage-providers/strongbox-maven-layout-provider` module.

See also:
* [Searching](https://github.com/strongbox/strongbox/wiki/Searching)
* [Artifact Coordinates](https://github.com/strongbox/strongbox/wiki/Artifact-Coordinates)
* [Maven Metadata](https://github.com/strongbox/strongbox/wiki/Maven-Metadata)
* Maven Indexer:
  * [Strongbox: Maven Indexer](https://github.com/strongbox/strongbox/wiki/Maven-Indexer)
  * [Apache Maven Indexer sources](https://github.com/apache/maven-indexer/)
* [MavenArtifactGenerator](https://github.com/strongbox/strongbox/blob/ea5adb6fd348bb963e5a8e6cae2200e591df74d8/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/MavenArtifactGenerator.java)
* [TestCaseWithMavenArtifactGeneration](https://github.com/strongbox/strongbox/blob/f012b02b8fc10bbe0219ce77209770cf343e4d1e/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/TestCaseWithMavenArtifactGeneration.java)

**Comment by sanket407** [comment]
Working on this !
Expected time of completion : A week !

**Comment by carlspring** [comment]
@fuss,

Please, remind me, did you implement this already? If so, please close the issue.

**Comment by fuss86** [comment]
Yes, we can close it.
