### ISSUE TITLE
Create integration tests that resolve artifacts from Strongbox using NPM

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#433]
We need to add integration tests (in the [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests/) project) that resolve and deploy artifacts using NPM.

There's a ["Hello, World!"](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-npm/) application that we've already created for illustrating how to configure NPM to work with Strongbox.

The tests should be invoked in a similar way to how they're currently being invoked for NuGet -- using Groovy scripts. There should be a Maven profile similar to the one for NuGet (check the one with`<id>run-nuget-it-tests</id>` for an example).

The test case must cover at least the following:
- Resolve dependencies
- Deploy an artifact

We need something along the same lines implemented for NPM.

Please, note that the work for this will have to be done in a different project -- [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests/).

This issue relates to #430, #431 and #432.

**Comment by danielbrzn** [comment]
I'll work on this 👍

**Comment by carlspring** [comment]
Great! Could you please join our channel on [Gitter](https://gitter.im/strongbox/strongbox)? @SoulSilence is working on same thing but for SBT. I guess you could help each other out and also, it would be easier to explain things in one place, when there are questions (and the questions are applicable to all tools). :)

Thanks!
