### ISSUE TITLE
Remove the RepositoryLayoutEnum class

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#437]
All the classes using this enum like this:

```
RepositoryLayoutEnum.NUGET.getLayout()
```

should now be using: 

```
NugetLayoutProvider.ALIAS
```

**Comment by carlspring** [comment]
@sanket407 , 

This is related to #434. Would you perhaps Like to look into this as well?

**Comment by sanket407** [comment]
@carlspring  yes

**Comment by sanket407** [comment]
@carlspring RepositoryLayoutEnum class has to be deleted too ? Or only the enum use should be changed as given above ? As RepositoryLayoutEnum.MAVEN_2 is used else where too.

**Comment by carlspring** [comment]
I was just giving an example with NuGet. The same approach used for NuGet
should be applied to Maven as well. This `getLayout()` string should be
replaced with the `ALIAS` of the respective layout provider implementation.

**Comment by carlspring** [comment]
This will be handled as part of #612.

**Comment by carlspring** [comment]
Resolved.
