### ISSUE TITLE
Implement a Spring controller that returns the list of files and directories in a path as JSON

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#444]
# Description

We need a new Spring controller to be implemented that returns a JSON representation of the contents of a path.

* The controller should:
  * Be called `BrowsingController`
  * Be placed in the `strongbox-web-core` under the `org.carlspring.strongbox.controllers`
* The web resource path should be `/browse/{storageId}/{repository}/{path}`.
* The returned results must be sorted

# Examples

## Listing all the storages

`curl -H "Accept: application/json" -X GET http://localhost:48080/browse/`

### Expected JSON response
```
{
    'storages': [
      'storage0',
      'storage1',
      'storage2'
      ....
    ]
}
```

## Listing all the repositories in storage

`curl -H "Accept: application/json" -X GET http://localhost:48080/browse/storage0/`

### Expected JSON response
```
{
    'repositories': [
      'releases',
      'snapshots',
      ....
    ]
}
```

## Listing the contents of a repository

`curl -H "Accept: application/json" -X GET http://localhost:48080/browse/storage0/releases/`

### Expected JSON response
```
{
    'directories': [
        // any directories found in /storage0/releases/* (depth level 1) without trailing slash
        // if none are found, this should be an empty array.
        'com',
        'org',
        ....
    ],
    'files': [
        // and any files in /storage0/releases/* (depth level 1)
        // if none are found, this should be an empty array.
        'maven-metadata.xml',
        'maven-metadata.xml.md5',
        'maven-metadata.xml.sha1',
        ...
    ]
}
```

## Listing the contents of a path in a repository

`curl -H "Accept: application/json" -X GET http://localhost:48080/browse/storage0/releases/org/apache/maven/`

### Expected JSON response:
```
{
    'directories': [
        // any directories found in /storage0/releases/org/apache/maven/* (depth level 1) without trailing slash
        // if none are found, this should be an empty array.
        '3.5.1',
        '3.5.2',
        '3.5.3',
        ....
    ],
    'files': [
        // and any files in /storage0/releases/org/apache/maven/* (depth level 1)
        // if none are found, this should be an empty array.
        'maven-metadata.xml',
        'maven-metadata.xml.md5',
        'maven-metadata.xml.sha1',
        ...
    ]
}
```

**Comment by carlspring** [comment]
Implemented by @guidograzioli.
