### ISSUE TITLE
Refactor UserController to return proper JSON messages upon successful/failed action

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#445]
Refactor `org.carlspring.strongbox.controllers.users.UserController` (located in `strongbox-web-core`) so that it returns `JSON` messages upon successful/failed actions with the appropriate messages as follows:

1. If an action is successful we need to return the following JSON:
   ```
   {
       "message": "User successfully updated / deleted / etc"
   }
   ```

2. If the action has failed we need to return an error message that describes what's wrong:
   ```
   {
       "message": "A user with this username already exists! Please enter another username. / etc"
   }
   ```

**Comment by carlspring** [comment]
Implemented by @ptirador.
