### ISSUE TITLE
Extract the code for the directory browsing into a set of methods in the BaseArtifactController and make the implementation generic enough to be able to serve all layout providers

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#446]
At the moment, the logic for this exists only in the `MavenArtifactController`. The code for this needs to be extracted into the `BaseArtifactController` and made more re-usable. The respective layout provider implementations of the controllers should then use these methods as required, to avoid duplication.

This task is similar to #447 .

Relates to #418, #419, #420.

**Comment by sanket407** [comment]
Working on this !!

**Comment by carlspring** [comment]
@sanket407 , 

I assume this is now to be considered resolved, so I will close it. Let me know, if this is not the case! Thanks for your help! :)
