### ISSUE TITLE
Extract the code for the ranged requests into a set of methods in the BaseArtifactController and make the implementation generic enough to be able to serve all layout provider controllers

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#447]
At the moment, the logic for this exists only in the `MavenArtifactController`. The code for this needs to be extracted into the `BaseArtifactController` and made more re-usable. The respective layout provider implementations of the controllers should then use these methods as required, to avoid duplication.

This task is similar to #446.

**Comment by sanket407** [comment]
@carlspring  I will check this out.

**Comment by carlspring** [comment]
Okay, thanks! :)

**Comment by sanket407** [comment]
@carlspring I think this has already been resolved. All artifact controllers now call the provideArtifactDownloadResponse() in BaseArtifactController. So they all should be supporting ranged requests.

**Comment by carlspring** [comment]
@sanket407 : You are right! Thanks for checking! :)
