### ISSUE TITLE
When an artifact has been deployed, or requested via a proxy repository, the parent directory(ies) of the temporary file is not removed on successful download

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#460]
# Description
When an artifact is being deployed, or downloaded, the temporary file is stored under:
```
strongbox-vault/storages/${storageId}/${repositoryId}/.temp/
```
with the respective path of the artifact (for example: `org/foo/bar/1.2.3/bar/...`.

When the artifact has successfully finished being written (regardless of whether this is a deploy, or resolve operation) and the file has been moved under the proper place under the repository's directory (`strongbox-vault/storages/${storageId}/${repositoryId}/org/foo/bar/blah-1.2.3/blah...` (this is an approximation, as the actual file name is a timestamp)), the parent directory gets left behind lying around empty under the `.temp` directory.

Please, note that **nothing** outside the `.temp` directory should be removed.

# How to fix
Once the artifact has been successfully moved to the proper location under the repository, the respective parent directories up until a level that contains only empty directories must be removed. For example, if the path in the `.temp/` directory to the artifact was `com/foo/bar/1.2.3/bar-1.2.3.jar` and there are `com/blah/2.2.1/blah-2.2.1.jar` and an empty directory `com/foo/bar/1.2.3/` (with no files in any of the subdirectories under `com/foo`), the `com/foo/bar/1.2.3/` path should be removed up until `com` and the `com/blah/2.2.1/blah-2.2.1.jar` should be skipped.

# Steps to reproduce
Rough steps to reproduce this:
1. Option 1 for reproducing (deploying an artifact):
1.1 Build `strongbox` with `mvn clean install` (you can add `-DskipTests`, if you like)
1.2 `cd strongbox-web-core && mvn clean package -Pjetty-block`
1.3. Use the [hello-strongbox-maven](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-maven) example project (and the instructions there on how to deploy an artifact to Strongbox)
1.4. Check the `strongbox-vault/storages/${storageId}/${repositoryId}/.temp/`
2. Option 2 for reproducing (using Strongbox as a proxy repository):
2.1. Use the following `settings.xml` file:
```
<?xml version="1.0" encoding="UTF-8"?>
<settings>

    <localRepository>/home/carlspring/.m2/repository-strongbox</localRepository>

    <mirrors>
        <mirror>
            <id>strongbox</id>
            <name>strongbox</name>
            <url>http://localhost:48080/storages/public/public-group/</url>
            <!-- Or try: -->
            <!--url>http://localhost:48080/storages/storage-common-proxies/maven-central/</url-->
            <mirrorOf>*</mirrorOf>
        </mirror>
    </mirrors>

    <profiles>
        <profile>
            <id>carlspring-repositories</id>

            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>

            <repositories>
                <repository>
                    <id>strongbox</id>
                    <name>strongbox</name>
                    <url>http://localhost:48080/storages/public/public-group/</url>
                    <layout>default</layout>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>strongbox</id>
                    <name>strongbox</name>
                    <url>http://localhost:48080/storages/public/public-group/</url>
                    <!--url>http://localhost:48080/storages/storage-common-proxies/maven-central/</url-->
                    <layout>default</layout>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>
</settings>
```
2.2. Try building Strongbox (or one of it's modules) against this running instance
2.3. Check under `strongbox/strongbox-web-core/target/strongbox-vault/storages/"storage-common-proxies/` (or `strongbox/strongbox-web-core/target/strongbox-vault/storages/storage-common-proxies/storage-common-proxies/maven-central`, depending on what you chose).

**Comment by carlspring** [comment]
@fuss86,

Could you please remind me, if you fixed this, or whether it's still up for grabs?

**Comment by fuss86** [comment]
I don't think so I've fixed this :)

**Comment by carlspring** [comment]
Okay -- so I can close this?
Could you please backlink this to your pull by mentioning which PR it was? Thanks?
