### ISSUE TITLE
The Maven Indexes are being downloaded to the java.io.tmpdir, instead of the respective repository's .temp dir

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#461]
The maven indexes are currently being downloaded to the `java.io.tmpdir`. This is incorrect. Each repository has a `.temp` directory in it's base directory. If all of the indexes that have been downloaded temporarily to the `java.io.tmpdir` are all just spewed there, it becomes a mess and it's hard to figure out which of them belongs to which repository.

Once the remote index has been downloaded and updates/merged, these temporary files should probably be removed from the `.temp` directory.

**Comment by fuss86** [comment]
#559

**Comment by carlspring** [comment]
Implemented by @fuss86 in #559 .
