### ISSUE TITLE
Get the maven plugin's prefix properly when generating metadata

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#462]
This needs to be addressed properly, as it's not correct.
This can be obtained from the jar's `META-INF/maven/plugin.xml` and could be read via a `ZipInputStream`.

For more details, please check `org.carlspring.strongbox.storage.metadata.MetadataMerger.updateMetadataAtGroupLevel()`.

**Comment by dinesh19aug** [comment]
`org.carlspring.strongbox.storage.metadata.MetadataMerger.updateMetadataAtGroupLevel() `
The above method is trying to update the information if artifact is not a plugin. Please clarify if I need to fix this method or add a new method to update the metadata for plugin artifact.
If you look at the existing method. The if condition code -` if(!found) ` will only be entered  if the artifact type is not a plugin.

Either I need write a new method or update the existing method by adding an else part which will cater to file artifact which are not of type plugin. Ex download the two jar files  -  maven-dependency-plugin and commons-lang3. For the dependency plugin jar information is under META-INF/maven/plugin.xml and for commons jar the information is under META-INF/com.xxx/pom.xml

Please clarify.

**Comment by carlspring** [comment]
Implemented by @dinesh19aug .
