### ISSUE TITLE
Create a "System Requirements" wiki page

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#483]
# Task Description

Gather the list of requirements here and produce a wiki page with them.

You will need to create a PR in the [strongbox-docs](https://github.com/strongbox/strongbox-docs) repository. Please add this as a page under the `User Guide`.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86
  * @steve-todorov

**Comment by thecodingdoc1** [comment]
Does this issue still need to be handled?

**Comment by carlspring** [comment]
Hi!

Yeah, this is up for grabs!

Would you like to join 
our [chat channel](https://chat.carlspring.org/)?

**Comment by Shubhang-Sharma** [comment]
is this still up-for-grabs? 
I would like to solve it

**Comment by steve-todorov** [comment]
Hi @Shubhang-Sharma,

Sure, feel free to pick this up. You will need to create a PR in the [strongbox-docs](https://github.com/strongbox/strongbox-docs) repository. Please add this as a page under the `User Guide`.

**Comment by carlspring** [comment]
We need to clarify things with the `ulimit` issue under Linux (#1289).
