### ISSUE TITLE
Refactor the port management code in ConfigurationManagementController

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#490]
The port management code located in `org.carlspring.strongbox.controllers.ConfigurationManagementController` is not exactly working as expected. We need to have the following changes made:

1. `GET /configuration/strongbox/port` - needs to return in `JSON` the following output:

   ```
   {
       "port": 12345 // or whatever the actual port is
   }
   ```
 
2. `PUT /configuration/strongbox/port` - (new endpoint) which should require the following `JSON` body to be submitted:

   ```
   {
       "port": 48081 // or whatever the new port is
   }
   ```
 
3. `PUT /configuration/strongbox/port/{port}` - has to respond with `Status 200` and plain text body `OK` when the operation has been successful and `Status 500` and plain text body `FAILED` if something has gone wrong. This will make the life of people using scripts a lot easier than having to actually parse the response of `curl` and monitor the `status code`.

**Comment by carlspring** [comment]
I think that all of the similar methods in this controller.

**Comment by ptirador** [comment]
What if a method, similar to point 3, also returns a `Status 404`? Do I respond with that status and plain text body `NOT FOUND`?

**Comment by carlspring** [comment]
Well, yeah, you can respond in the manner defined by the "Accepts" header.

**Comment by carlspring** [comment]
Fixed by @ptirador .
