### ISSUE TITLE
Remove the ArtifactFileUtils class, as it's no longer used

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#494]
This class is no longer needed, as it's been properly replaced by a better mechanism -- the `RepositoryFileAttributes`.

Check if the [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests) still need this (the order of building is `strongbox` > `strongbox-web-integration-tests`).

**Comment by steve-todorov** [comment]
Fixed in #501 by @gokhankuyucak.
