### ISSUE TITLE
Implement directory browsing for repositories with an NPM layout

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#498]
Similarly to the Maven implementation, we need to also implement directory browsing for NPM.

**Comment by carlspring** [comment]
@sbespalov ,

Can this task be closed?

**Comment by sbespalov** [comment]
@carlspring I will check it during the day

**Comment by carlspring** [comment]
@sbespalov, I don't think we followed up on this? Does this still need to be implemented?

**Comment by sbespalov** [comment]
I think we can close it.

**Comment by carlspring** [comment]
@steve-todorov : Could you please confirm and close this, if this is so? Thanks!

**Comment by steve-todorov** [comment]
It seems to be working. Closing! :)

**Comment by carlspring** [comment]
Thanks for following up on this! :)
