### ISSUE TITLE
Review NuGet functionality implemented in Strongbox

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#504]
Currently we assume that Nuget protocol version 2 is sufficient implemented for real use.
Within this task we need for someone with .Net experience to confirm that common NuGet cases will work in real world.
What need to be done:
1. Update the list of commands for different build tools ([nuget cli](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference), [dotnet](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore2x), [Cake](https://cakebuild.net/) etc. ) that supported and describe it in [wiki](https://github.com/strongbox/strongbox/wiki/NuGet-Layout-Provider);
2. Check common NuGet cases within VisualStudio IDE (with different versions of VS that support NuGet; at least the latest two versions + the free versions of VS):
* Search packages via local repo
* Search packages via remote/proxied repo
* Resolve transitive dependencies
* Something else???
3. Check current API implementation against [official specification](https://github.com/NuGet/Home/wiki/Filter-OData-query-requests#supported-query-patterns) and describe what supported in [wiki](https://github.com/strongbox/strongbox/wiki/NuGet-Layout-Provider);

As a result, we need to have actual information on the [wiki](https://github.com/strongbox/strongbox/wiki/NuGet-Layout-Provider) and list of issues if there will be some.

**Comment by gokhankuyucak** [comment]
@sbespalov while testing with cake build tool. I found that Cake script is using 
localhost:48080/storages/public/nuget-public/FindPackagesById()?**id**='Cake'&semVerLevel=2.0.0'

but in [NugetArtifactController.searchPackageById ](https://github.com/strongbox/strongbox/blob/2d6b8a742ec4451333f456f7d961fda1c253753a/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/nuget/NugetArtifactController.java#L310:26) is accepting the parameter "**Id**". The url is case sensitive so while running cake script gets http 400.

what is the best approach for this? [supporting case-insensitive for whole urls](https://stackoverflow.com/questions/4150039/how-can-i-have-case-insensitive-urls-in-spring-mvc-with-annotated-mappings/29810228#29810228) or [implementing a custom solution for only this method](https://stackoverflow.com/a/8924030).

**Comment by sbespalov** [comment]
@gokhankuyucak I think that first will be good, also we already have `org.carlspring.strongbox.utils.CustomAntPathMatcher` for our Spring MVC.
@carlspring  do you approve case insensitive URLs?

**Comment by carlspring** [comment]
Hi,

Yes, I think that we should allow this for the NuGet controller.

**Comment by sbespalov** [comment]
@gokhankuyucak probably we should just change it back to lower case `id`
see this issue, https://github.com/NuGet/Home/issues/2439

**Comment by gokhankuyucak** [comment]
One more issue while using remote proxy https://www.nuget.org/api/v2
While running nuget install command for package id="Cake" version="0.26.0", the application first searches in local repos  if there is no result it tries to execute request for proxy url to download artifact but  it logs that "Remote repository https://www.nuget.org/api/v2 is down".
In [ProxyRepositoryArtifactResolver.getInputStream](https://github.com/strongbox/strongbox/blob/fc4792de378662e6e3d782caf50aeb9e426af4b8/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/proxied/ProxyRepositoryArtifactResolver.java#L51:24) the condition remoteRepositoryAlivenessCacheManager.isAlive(remoteRepository) returns false so the artifact can not be downloaded from proxy. I removed that condition block and it works without any error. 

the [RemoteRepositoryAlivenessCacheManager.put](https://github.com/strongbox/strongbox/blob/abfeea4194defa648a48eb93bfc7e27f5f82adce/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/storage/repository/remote/heartbeat/RemoteRepositoryAlivenessCacheManager.java#L36:5) method is only used in RemoteRepositoryHeartbeatMonitor. So it seems that remoteRepositoryAlivenessCacheManager.isAlive(remoteRepository) will always return false. 
Do you have any idea?

**Comment by carlspring** [comment]
@fuss86 ,

Do you have any thoughts on this? Could you have a look at it, please? Thanks! :)

**Comment by fuss86** [comment]
I'll run and test why it claims that

> Remote repository https://www.nuget.org/api/v2 is down

maybe it was just a temporary problem accessing this URL. Will let you know.

**Comment by fuss86** [comment]
I think everything works as expected, so I suspect temporary problem with unavailability of https://www.nuget.org/api/v2

@gokhankuyucak, `RemoteRepositoryHeartbeatMonitor` is a scheduled job for each remote repository checking the accessibility of the remote repository. We cache the `aliveness` status for default `60 seconds` time.

Could you please let me know if this issue still occurs on your end ? If so, I'd like to know steps to reproduce this issue. What have you built and how did you run the application. 

Thanks!

**Comment by gokhankuyucak** [comment]
@fuss86 , I still got this issue with below steps:
 in maven projects > strongbox-web-core > Plugins > right click to "jetty:run" and select run or debug.

**Comment by carlspring** [comment]
@gokhankuyucak , 

I don't think that's the best way to be running things. There is a special profile for running Jetty. It does a bunch of things. You can trigger this by doing:

```
/path/strongbox/strongbox-web-core $ mvn clean package -Pjetty-block
```

**Comment by sbespalov** [comment]
@carlspring @fuss86 @gokhankuyucak 
seems that I meet the same issue:
```
10:44:06.744 15-03-2018 | DEBUG | http-nio-8080-exec-3 | .p.r.p.LocalStorageProxyRepositoryArtifactResolver | Remote repository 'http://dev.carlspring.org/nexus/content/groups/carlspring' is down.
```
it says that remote repo is down, but it's not true :)

**Comment by carlspring** [comment]
Okay, could someone please pick this up?

**Comment by sbespalov** [comment]
I will, after SWIT

**Comment by sbespalov** [comment]
@gokhankuyucak I have fixed this issue with remote repositories, can you please check it with current master?

**Comment by steve-todorov** [comment]
@gokhankuyucak , @sbespalov hi guys - what is the state of this issue? Can we consider it as fixed?

**Comment by carlspring** [comment]
I will be closing this task. The review and documentation has been done. The follow-up work on absorbing the bits of the JNuGet project into our code base is handled in other tasks.
