### ISSUE TITLE
Make sure TrashController is following the "How To Write Controllers" guide

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#510]
Currently the [TrashController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/TrashController.java) is not fully following the [How-To-Write-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) guide. This needs to be fixed.

**Comment by carlspring** [comment]
Implemented by @ptirador.
