### ISSUE TITLE
Make sure LoggingManagementController is following the "How To Write Controllers" guide

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#512]
Currently the [LoggingManagementController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/LoggingManagementController.java) is not fully following the [How-To-Write-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) guide. This needs to be fixed.

**Comment by steve-todorov** [comment]
Fixed by @ptirador in #545.
