### ISSUE TITLE
Make sure HttpConnectionPoolConfigurationManagementController is following the "How To Write Controllers" guide

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#513]
Currently the [HttpConnectionPoolConfigurationManagementController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/HttpConnectionPoolConfigurationManagementController.java) is not fully following the [How-To-Write-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) guide. This needs to be fixed.

**Comment by steve-todorov** [comment]
Fixed in #546 by @ptirador.
