### ISSUE TITLE
Make sure UserController is following the "How To Write Controllers" guide

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#516]
Currently the [UserController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/users/UserController.java) is not fully following the [How-To-Write-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) guide. This needs to be fixed.

**Comment by steve-todorov** [comment]
Fixed in #580
