### ISSUE TITLE
Make sure CorsConfigurationController is following the "How To Write Controllers" guide

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#517]
Currently the [CorsConfigurationController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/security/cors/CorsConfigurationController.java) is not fully following the [How-To-Write-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) guide. This needs to be fixed.

**Comment by steve-todorov** [comment]
Fixed in #558.
