### ISSUE TITLE
Rename the NpmPackageController and NugetPackageController

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#520]
For consistency, please rename the following artifact controllers:
* `NpmPackageController` to `NpmArtifactController` (for more info, check [NPM Layout Provider](https://github.com/strongbox/strongbox/wiki/NPM-Layout-Provider))
* `NugetPackageController` to `NugetArtifactController` (for more info, check [Nuget Layout Provider](https://github.com/strongbox/strongbox/wiki/NuGet-Layout-Provider))

Also, for consistency, please update the two wiki pages above to point to the renamed classes.

These classes are located under the `strongbox-web-core`.

**Comment by danielbrzn** [comment]
I'll work on this!

**Comment by carlspring** [comment]
Hi,

Yes, they will! Thanks for picking this up! Also, please sign the ICLA as described in the CONTRIBUTING.md.

Martin
