### ISSUE TITLE
HandlerMethodArgumentResolver to resolve Repository instance based on `{storageId}/{repositoryId}` path variables

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#528]
We'd like to have a Controller request method argument resolver for `org.carlspring.strongbox.storage.repository.Repository` instances.

For example, consider existing `org.carlspring.strongbox.controllers.TrashController#undelete` method which looks like this:

```
@RequestMapping(value = "{storageId}/{repositoryId}/{path:.+}", method = RequestMethod.POST)
public ResponseEntity undelete(@PathVariable String storageId, @PathVariable String repositoryId, @PathVariable String path)
```
In many Controllers we have repeated pre-conditions validating existence of the repository for provided path variables. 

It'd be awesome if we could refactor above implementation to something like:

```
@RequestMapping(value = "{storageId}/{repositoryId}/{path:.+}", method = RequestMethod.POST)
public ResponseEntity undelete(@RepositoryMapping Repository repository, @PathVariable String path)
```

Implemented `HandlerMethodArgumentResolver` should validate:
* Repository existence (followed by storage existence check first, of course)
* If repository `Repository.isInService().`

If validation fails, we should throw some newly implemented Exception(s) and handle it/them using `@ControllerAdvice`/`@ExceptionHandler` spring features.

**Comment by sbespalov** [comment]
@fuss86 I think this validation could also check that target repository is in service `Repository.isInService()`.

**Comment by carlspring** [comment]
> @fuss86 I think this validation could also check that target repository is in service `Repository.isInService()`.

I think it should also, check if there is such a storage in the first place.

**Comment by sbespalov** [comment]
@fuss86 also I have thoughts that we can provide `Repository` instance using something like `ThreadLocal` context which can be populated within `HeaderMappingFilter`, the thing is that we already have similar validation logic there. In this case `HandlerMethodArgumentResolver` will just check these `Repository` instance in `ThreadLocal` context.

**Comment by fuss86** [comment]
> @fuss86 I think this validation could also check that target repository is in service Repository.isInService().

Correct, updated ticket description. Thanks.

> I think it should also, check if there is such a storage in the first place.

Of course.

> we can provide Repository instance using something like ThreadLocal context 

I like this idea, in general ...

> which can be populated within HeaderMappingFilter

but `HeaderMappingFilter` works only for `"/storages"` mapping. I'd like to to make it worked not only for this mapping (consider also `org.carlspring.strongbox.controllers.TrashController`). I know it makes this task more challenged but it's doable. Person picking this task may also take some ideas from `org.springframework.web.servlet.mvc.method.annotation.PathVariableMethodArgumentResolver`.

**Comment by carlspring** [comment]
@sbespalov : How will your changes from #1269 affect this?
@ptirador : Would you like to pick this up?

**Comment by sbespalov** [comment]
> @sbespalov : How will your changes from #1269 affect this?

this issue probably need to be done somewhere within `CustomRequestMappingHandlerMapping`.

**Comment by ptirador** [comment]
Hi, I'd like to take this.

**Comment by carlspring** [comment]
Great, @ptirador ! I've assigned it to you!
