### ISSUE TITLE
Test the packed indexes using Nexus 2.x

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#531]
* Start the `strongbox-distribution`
* Deploy artifacts to one of the Maven 2 repositories
* Run the cron task for rebuilding the Maven Indexes. This should produce a packed Maven Index once it's finished.
* Create a new proxy repository in Nexus 2 pointing to the one in Strongbox the you've deployed the artifacts to.
* Via the web interface, try to browse the remote index. If you see the artifact in it, the test has been successful. While you're at it, please also report your findings in regards to browsing the remote repository via the Nexus web UI.

This issue relates to #523, #548.

**Comment by carlspring** [comment]
It seems this is not working properly due to the number of columns Nexus expects.

![screenshot - nexus - 2 14 3-02 - directory browsing in nexus proxy repository agasint strongbox hosted repository](https://user-images.githubusercontent.com/1436265/35531369-aa5e1eac-052e-11e8-9778-821df7a794b8.png)

**Comment by fuss86** [comment]
#560

**Comment by fuss86** [comment]
#576

**Comment by fuss86** [comment]
Fixed and tested in #576

**Comment by carlspring** [comment]
![screenshot - nexus - 11-02-2018 - 2 14 3-02 - directory browsing in nexus proxy repository agasint strongbox hosted repository](https://user-images.githubusercontent.com/1436265/36069194-c736bd38-0edc-11e8-9570-500739514cec.png)
![screenshot - nexus - 11-02-2018 - 2 14 3-02 - remote index browsing in nexus proxy repository agasint strongbox hosted repository](https://user-images.githubusercontent.com/1436265/36069195-c74a303e-0edc-11e8-8b0e-04c8b2723faa.png)
