### ISSUE TITLE
Test the packed indexes using Nexus 3.x

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#532]
* Start the `strongbox-distribution`
* Deploy artifacts to one of the Maven 2 repositories
* Run the cron task for rebuilding the Maven Indexes. This should produce a packed Maven Index once it's finished.
* Create a new proxy repository in Nexus 3 pointing to the one in Strongbox the you've deployed the artifacts to.
* Via the web interface, try to browse the remote index. If you see the artifact in it, the test has been successful. While you're at it, please also report your findings in regards to browsing the remote repository via the Nexus web UI.

This issue relates to #523.

**Comment by carlspring** [comment]
[Remote repository browsing is not available in Nx3](https://stackoverflow.com/questions/39901695/browsing-remote-repository-in-nexus-repository-v3-x).

**Comment by fuss86** [comment]
So... we can close this ticket ?:-)

**Comment by carlspring** [comment]
Well, yeah, I think we can close this task and whenever this feature is implemented by them, (if ever), we can re-open it.
