### ISSUE TITLE
Test the packed indexes using Artifactory

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#534]
* Start the `strongbox-distribution`
* Deploy artifacts to one of the Maven 2 repositories
* Run the cron task for rebuilding the Maven Indexes. This should produce a packed Maven Index once it's finished.
* Create a new proxy repository in Artifactory pointing to the one in Strongbox the you've deployed the artifacts to.
* Via the web interface, try to browse the remote index. If you see the artifact in it, the test has been successful. While you're at it, please also report your findings in regards to browsing the remote repository via the Artifactory web UI.

This issue relates to #523.

**Comment by carlspring** [comment]
@fuss86,

For some reason, there are dots ( ".." ) when browsing the remote. It seems they're expecting something else as a response... Maybe we'll have to return a different response for their `User-Agent`...?

```
05:16:43.417 11-02-2018 | DEBUG | qtp1348274608-173    | o.s.web.filter.CommonsRequestLoggingFilter         | After request [uri=/storages/storage0/snapshots/org/carlspring/strongbox/strongbox-authentication-api/;client=127.0.0.1;headers={Connection=[keep-alive], User-Agent=[Artifactory/5.8.4], Host=[localhost:48080], Accept-Encoding=[gzip], X-Artifactory-Originated=[398f4628e954136a:-11c90c1a:1618342c806:-8000], Origin-Artifactory=[398f4628e954136a:-11c90c1a:1618342c806:-8000]}]
```

![screenshot - artifactory - 11-02-2018 - 5 8 4 - remote directory browsing in nexus proxy repository agasint strongbox hosted repository](https://user-images.githubusercontent.com/1436265/36070056-0afeb27e-0eeb-11e8-83c4-4a5a452906ba.png)

**Comment by fuss86** [comment]
after the review of `org.artifactory.repo.remote.browse.HtmlRepositoryBrowser` it's enough to replace `".."` by `"../"` specifying the link's destination.

tested under Nx2 too.

**Comment by fuss86** [comment]
#599

**Comment by fuss86** [comment]
Done.
