### ISSUE TITLE
Produce proper code coverage reports using JaCoCo for both unit and integration tests

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#535]
We need to produce a merged report of both our unit and integration tests and store this in Sonar. We have Jenkins in place that could be doing this for automatically.

Our unit tests are executed using the `maven-surefire-plugin`. We also have integration tests (triggered by passing in `-Dintegration.tests`). In the `strongbox/strongbox-parent/pom.xml` we have our configuration settings for JaCoCo.

The problem is that the numbers that we are getting, somehow are not adding up. With the extensive amount of tests that we have, there is no way our test coverage could be as low as 30%. It seems that the reports which we are producing are somehow getting overwritten, (or some other sort of weirdness is going on). We need somebody to look into this and help us get our numbers right. Last time this was producing proper results was, probably back in 2016 and then the results were ~85-90%. Despite the amount of new code added, we've always been adding new tests as well, so this figure should be significantly above 30-40%.

For ease of testing, you can use your own Sonar instance.

See also:
* [JaCoCo multi-module](https://github.com/jacoco/jacoco/wiki/MavenMultiModule)

**Comment by steve-todorov** [comment]
I would like to add that we currently have Sonar 6.6 which are running from the official [sonar:6.6](https://hub.docker.com/r/library/sonarqube/tags/) docker image. There seems to be a newer version - 6.7 which you can pull using docker.
