### ISSUE TITLE
NuGet checksum validation during package uploading

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#540]
Currently we have checksum generated on server side within `NugetArtifactController`, which is wrong because checksum assume to check the uploaded artifact consistency, so it's not damaged during uploading.
Within this task we need to know how checksums assumed to be provided by NuGet client. 
Is there any specification for this on protocol level?
After the understanding of how the checksums work in Nuget, we will need to implement the necessary support for this on our side

**Comment by carlspring** [comment]
@gokhankuyucak ,

Could you please help us investigate how this should be done? Does NuGet generate these checksums on the client side? How does this work in [NuGet Gallery](https://github.com/NuGet/NuGetGallery), for example? Is it done on the server side?

If you can't find anything, could you please ask a question on their Github issue tracker and/or on Stackoverflow?

**Comment by gokhankuyucak** [comment]
I traced the Nuget push command and found nothing about checksum validation, it overwrites the existing files if exists and didn't find any validation control after successful upload. 
Checked the class [PackageUpdateResource.cs](https://github.com/NuGet/NuGet.Client/blob/993e1f2742da08f8e3e1858857f134a7b6dcd84c/src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs#L179:23) 
and following methods: 

- PushPackage
- PushPackageCore
- PushPackageToFileSystem
- PushPackageToServer

Checked the class [NuGetPushCommandTest.cs](https://github.com/NuGet/NuGet.Client/blob/389e5ac32c213c0d50579ab96f86a005fb9d4f37/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPushCommandTest.cs)
and following methods 

- PushCommand_PushToV2FileSystemSource
- PushCommand_PushToV3FileSystemSource

these methods just test the file exists in source repo or not, after push command

As described in the wiki [page](https://github.com/NuGet/Home/wiki/Author-Package-Signing):
_
> NuGet packages do not include any mechanism to determine if a given package has been modified from creation to consumption or who is the legitimate author of the package
_

On the other hand  I realized that the sha512 file created with strongbox is different from the file that the nuget server created. I partially forked the Hash logic from [Nuget Home](https://github.com/NuGet/Home) in [here](https://github.com/gokhankuyucak/NugetHashProvider) and the sha512 file has different contents for the same nupkg

**Comment by carlspring** [comment]
@gokhankuyucak ,

Thanks for investigating!

@sbespalov ,

Any thoughts/comments on this?

**Comment by sbespalov** [comment]
> On the other hand I realized that the sha512 file created with strongbox is different from the file that the nuget server created.

yeah, we have it base 64 encoded as it was implemented in JNuget :)

>  I partially forked the Hash logic from Nuget Home in here and the sha512 file has different contents for the same nupkg

so, if they have no checksum validation within upload, then where they using `sha512` then?

**Comment by sbespalov** [comment]
@gokhankuyucak also, am I understand correctly that there is no way to get package checksum from Nuget Gallery?

**Comment by gokhankuyucak** [comment]
according to class [PackageUpdateResource.cs](https://github.com/NuGet/NuGet.Client/blob/993e1f2742da08f8e3e1858857f134a7b6dcd84c/src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs) the "PushPackageCore" method is checking the source parameter, if the source  parameter is a file it will check the nuget version, if the nuget version v2 there will be no sha control, otherwise it will check sha512 hashes in source and destination in [OfflineFeedUtility.PackageExists](https://github.com/NuGet/NuGet.Client/blob/98fd6e140c80c3932d6e857b456ee5120751ae46/src/NuGet.Core/NuGet.Protocol/Utility/OfflineFeedUtility.cs#L22:28) method.
If the source parameter is a server "[ServerPackageRepository.AddPackage](https://github.com/NuGet/NuGet2/blob/e89c4b2fc6dc2fc752d2fceecd2a2175b0f4ab69/src/Server/Infrastructure/ServerPackageRepository.cs#L147:30)" is used to push packages.

Our source parameter is a http Uri so I didn't find any hash control while pushing to the server

**Comment by sbespalov** [comment]
@gokhankuyucak great research, thanks
but this is client, and how about server?

seems that they assume to have **sha512** file [here](https://github.com/NuGet/NuGet.Client/blob/98fd6e140c80c3932d6e857b456ee5120751ae46/src/NuGet.Core/NuGet.Protocol/Utility/OfflineFeedUtility.cs#L39) and if I understand correctly it should be also pushed to server. 

Am I right?

**Comment by gokhankuyucak** [comment]
hi sorry but I gave wrong reference for ServerPackageRepository. the correct one should be under the package NuGet.Server.Core.Infrastructure. 
I think in our case the methods are invoked in the following order

1. Nuget Client pushes the nupkg  to the source server
2. On the server side [NuGetODataController.UploadPackage](https://github.com/NuGet/NuGet.Server/blob/2ee751ab71048d87f97f45807a420517a9aa9e27/src/NuGet.Server.V2/Controllers/NuGetODataController.cs#L379:56) is invoked
3. [ServerPackageRepository.AddPackageAsync](https://github.com/NuGet/NuGet.Server/blob/2ee751ab71048d87f97f45807a420517a9aa9e27/src/NuGet.Server.Core/Infrastructure/ServerPackageRepository.cs#L326:9) is invoked 
4. [ServerPackageStore.add](https://github.com/NuGet/NuGet.Server/blob/2ee751ab71048d87f97f45807a420517a9aa9e27/src/NuGet.Server.Core/Infrastructure/ServerPackageStore.cs#L37:1) is invoked 
5. [ExpandedPackageRepository.AddPackage](https://github.com/NuGet/NuGet2/blob/e89c4b2fc6dc2fc752d2fceecd2a2175b0f4ab69/src/Core/Repositories/ExpandedPackageRepository.cs#L44:30) is invoked and sha512, nupkg, nuspec files are created here

To be ensure about checksum validation I created a private NugetServer by following [instructions](https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server)
And tried following steps:

1. Run `nuget.exe push HelloNuget.1.0.2.nupkg -Source http://localhost:52338/nuget`
2. 'HelloNuget.1.0.2.nupkg', 'HelloNuget.1.0.2.nupkg.sha512', 'HelloNuget.nuspec' files are created under packages folder.
3. Added some new dependencies to HelloNuget project created same nupkg with same version to generate different sha512
4. Run `nuget.exe push HelloNuget.1.0.2.nupkg -Source http://localhost:52338/nuget` again
5. The last push package action overwrites the old one. So  I assume that there is no checksum validation.

**Comment by sbespalov** [comment]
seems that I am starting to understand something :)

they just generate sha512 checksum on server side in [ExpandedPackageRepository](https://github.com/NuGet/NuGet2/blob/e89c4b2fc6dc2fc752d2fceecd2a2175b0f4ab69/src/Core/Repositories/ExpandedPackageRepository.cs#L56)
so our v2 protocol implementation is the same, and seems that we found why it was implemented like this in JNuget

@gokhankuyucak , many thanks for this research
@carlspring I think that we now can resolve this task.

> 'HelloNuget.1.0.2.nupkg', 'HelloNuget.1.0.2.nupkg.sha512', 'HelloNuget.nuspec' files are created under packages folder.

just in case, what version of NuGet client you are using?
I am asking because, I have no sha512 file generated within push using v3 client.

**Comment by carlspring** [comment]
@gokhankuyucak ,

Thanks for tracking this stuff down! It seems like a lot of digging around! This will make our implementation of NuGet (protocol v2) feature complete!

**Comment by gokhankuyucak** [comment]
@sbespalov my Nuget Client is NuGet Version: 4.4.1.4656

**Comment by sbespalov** [comment]
@carlspring I think we can resolve this task

**Comment by carlspring** [comment]
@gokhankuyucak ,

Once again -- thanks for all your help with this investigation that checks whether, or not our implementation is correct! I will now close this task, as per @sbespalov 's recommendation.
