### ISSUE TITLE
Implement a test case for proxy repository with raw layout

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#542]
We currently have [Raw Layout](https://github.com/strongbox/strongbox/wiki/Raw-Layout-Provider) implemented for hosted repositories. Raw layouts have no particular format -- artifacts could be stored in whatever place, or way needed.

For proxy repositories, this would mean that whatever's on the remote host could be downloaded via the raw proxy repository.

We need a test that can cover the case, where:
* A proxy repository with `Raw` layout has been created (programatically via the test)
* A path that exists on the remote host is requested, downloaded and stored properly and then streamed back to the client requesting it
* A path that does not exist on the remote host is requested and the client requesting it receives an error 404

This test should be an integration test called `RawProxyRepositoryTestIT` and it should be under the `raw-layout-provider`.

As an example, please, have a look at [MavenProxyRepositoryProviderTestIT.java](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/MavenProxyRepositoryProviderTestIT.java) and follow the same approach.

**Comment by sbespalov** [comment]
@carlspring I think that this can't be implemented within our UnitTests because for proxy repositories we need URL which must be avaliable through http. So as a proxy repository, we need to have our RAW hosted repository which is deployed somewhere and available with http. 
So I think this tests need to be done within `s-w-i-t`.

**Comment by sbespalov** [comment]
Also I think that it will be good to improve `s-w-i-t` structure regarding groovy tests. My suggestion is to place appropriate tests under `src/test/groovy` folder.

**Comment by carlspring** [comment]
As these will be integration tests, they will be expected to be able to connect to the Internet, just like the tests implemented for Maven repositories that @fuss86 wrote.

Have a look at [this test](https://github.com/strongbox/strongbox/blob/2d53eb7b8371b6283cd005e3a45718e8218ec640/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/ProxyRepositoryProviderTestIT.java).

**Comment by carlspring** [comment]
Also, I agree with your idea about the restructuring.

Could you please raise a new issue for this and we'll look into it? @SoulSilence , @danielbrzn : You might want to do this from now'

**Comment by sbespalov** [comment]
> Could you please raise a new issue for this and we'll look into it? @SoulSilence , @danielbrzn : You might want to do this from now'

ok, will do it after @danielbrzn PR with gradle tests will be merged

**Comment by carlspring** [comment]
> they're using Maven Central, so I think it's not our case

That doesn't matter. The purpose of this would be to be able to proxy anything that is, or is not a repository. It could be any file or directory out there on the internet.

**Comment by sbespalov** [comment]
oh, seems that I see now the RAW layout purpose.
@carlspring sorry for this confusion :)
In this case we really can use Maven Central as RAW artifact source :)

**Comment by carlspring** [comment]
Yes, the whole point of this sort of layout provider is that there are times when you need to be able to host, or proxy artifacts that have no special layout format (like Maven, Gradle, NPM, NuGet, or whatever). For, example, let's say that some third-party application, or library that you use, is published as a zip somewhere like `http://some-third-party-corp.com/binaries/betascool-app/coolapp-1.23-beta2.zip`. So, there is no way to proxy this, if you're using a strict layout provider like the ones I listed above, since the above link is not in any format, but in your locked down environment in your company you aren't allowed access to the Internet from your servers, so you need to use a proxy, or an artifact repository manager. This is the goal here.

**Comment by SoulSilence** [comment]
I'd like to take this task

**Comment by steve-todorov** [comment]
@carlspring, @SoulSilence ping? What is the state of this issue - can we close it?

**Comment by carlspring** [comment]
No, this is not implemented.

**Comment by carlspring** [comment]
Implemented as part of #709.
