### ISSUE TITLE
The paths in the directory listing are not sorted

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#550]
When displaying the list of files and directories the results should be sorted like this:
* Directories should be listed first and they should be sorted alphabetically
* Files should be listed after the list of directories and they should also be sorted alphabetically

How to test manually:
* Start up a Jetty in blocked mode, as explained [here](https://github.com/strongbox/strongbox/wiki/Building-the-code#running-jetty-in-blocked-mode)
* Deploy the [hello-strongbox-maven](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-maven) artifact to Strongbox (or some other artifacts for that matter, so that there are multiple directories, or simply create these files and directories under `strongbox-web-core/target/strongbox-vault/storages/storage0/the-respective-repository`

We will need an automated test for this using restassured.

**Comment by SoulSilence** [comment]
I published artifact to my local strongbox and got such response. 

{
    "directories": [],
    "files": [
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT-javadoc.jar",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT-javadoc.jar.md5",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT-javadoc.jar.sha1",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT-sources.jar",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT-sources.jar.md5",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT-sources.jar.sha1",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT.jar",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT.jar.md5",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT.jar.sha1",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT.pom",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT.pom.md5",
        "hello-strongbox-sbt_2.12-1.0-SNAPSHOT.pom.sha1"
    ]
}

As I see it's sorted. Isn't it?

**Comment by carlspring** [comment]
This is not necessarily always sorted (I've actually seen it not sorted, which why I've raised this issue). Do we have an explicit sort being invoked, or are we relying on the underlying OS to do it for us?

**Comment by SoulSilence** [comment]
` Files.list(baseDir)
                 .filter(p -> !p.getFileName().toString().startsWith("."))
                 .sorted()
                 .forEach(p -> (Files.isDirectory(p) ? directories : files).add(p.getFileName().toString()));
          `

**Comment by SoulSilence** [comment]
As I see it sorts in case sensitive order. Is it a problem? Do tou want case insensitive order?

**Comment by carlspring** [comment]
Please, have a look at this:

![screenshot - strongbox - directory browsing in hosted repository not sorted](https://user-images.githubusercontent.com/1436265/35747383-0451a756-0842-11e8-8cb7-a17e130507c2.png)

**Comment by carlspring** [comment]
Based on the code you quoted, I don't see what you mean by case-sensitive here, really... What am I not seeing?

**Comment by carlspring** [comment]
Also. I believe you're confusing things. I'm not talking about the `BrowserController` which returns JSON. If you open `http://localhost:48080/storages/storage0/snapshots/` (and, of course you have some artifacts deployed to that repository, you will see what I mean. (It's best to try [building strongbox against strongbox](https://github.com/strongbox/strongbox/wiki/Building-Strongbox-Against-Strongbox) to see what I mean.

**Comment by carlspring** [comment]
I've tested this and it works as expected! Thanks! :)
