### ISSUE TITLE
Refactor the strongbox-web-integration-tests to be one module per build tool

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#561]
We are starting to have more and more integration tests for different build tools. Initially, this only contained a set of tests that would execute Maven (from within Maven itself via the `maven-invoker-plugin`) and perform various checks using Groovy validation scripts.

A while ago @sbespalov added some tests written in Groovy that would check things for our NuGet layout support by invoking NuGet using Groovy in a similar way via Maven.

# Issues
* These tests require that all of the required build tools are installed on the developer's machine in order to run them, unless they manually disable all the profiles for the build tools they're not testing, or writing tests for
* This is not scalable and the tests for the different build tools cannot be executed in parallel

# Solution
* The project should be split as follows:
```
strongbox-web-integration-tests/
+ maven/
|  |- src/it/
|  |  + test-case-1/
|  |  + test-case-2/
|  |  + ...
|  |  \ test-case-n/
|  |- pom.xml 
+ gradle/
|  |- src/it/
|  |  + test1.groovy
|  |  + test2.groovy
|  |  + ...
|  |  \ testN.groovy
|  |- pom.xml 
+ sbt/
|  |- src/it/
|  |  + test1.groovy
|  |  + test2.groovy
|  |  + ...
|  |  \ testN.groovy
|  |- pom.xml 
+ ant-ivy/
|  |- src/it/
|  |  + test1.groovy
|  |  + test2.groovy
|  |  + ...
|  |  \ testN.groovy
|  |- pom.xml 
```

* The root `pom.xml` should be removed, as each of these sets integration tests will be run independently.
* Each of the `pom.xml` files in the respective test set directories will only have the section for running it's own tests (not like right now where we have them all in one `pom.xml`)

**Comment by steve-todorov** [comment]
@carlspring I believe this is now fixed? Can we close it?

**Comment by carlspring** [comment]
Closing, thanks!

**Comment by carlspring** [comment]
Implemented by @SoulSilence.
