### ISSUE TITLE
Require proper roles/privileges to access LoggingManagementController endpoints

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#569]
Our `org.carlspring.strongbox.controllers.LoggingManagementController` currently is not properly secured. It needs to have `@PreAuthorize` for each method. The list of privileges can be found in `org.carlspring.strongbox.users.domain.Privileges`.

```
CONFIGURATION_ADD_LOGGER
CONFIGURATION_UPDATE_LOGGER
CONFIGURATION_DELETE_LOGGER
CONFIGURATION_RETRIEVE_LOG
CONFIGURATION_RETRIEVE_LOGBACK_CFG
CONFIGURATION_UPLOAD_LOGBACK_CFG
VIEW_LOGS
CONFIGURE_LOGS
```

**Comment by adityasrini** [comment]
I’m taking this on. Unless someone else is working on this.

**Comment by carlspring** [comment]
Okay, thanks! :)
