### ISSUE TITLE
Implement directory browsing for the log files

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#570]
We need to implement directory browsing for the log files.

There may be more the one log file in the `${STRONGBOX_VAULT}/logs` directory (please, use `PropertyUtils.getVaultDirectory()` for this).

A new method should be added to the `LoggingManagementController` that handles requests for `/logging/logs`. This should display the contents of the `${STRONGBOX_VAULT}/logs` directory.

Accessing these resources should require the user to be logged in and have the `VIEW_LOGS` privilege (defined in the `org.carlspring.strongbox.users.domain.Privileges`).

Also, please check how the directory browsing for artifacts has already been implemented in `MavenArtifactController` and follow the same approach.

**Comment by adityasrini** [comment]
Hi Carl! I intend to work on a solution for this.
