### ISSUE TITLE
Convert the org.carlspring.strongbox.storage.repository.Repository class to use RepositoryPath objects instead of File-s

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#578]
We should try to avoid the use of `File`-s at all cost. There are a couple of methods in the `org.carlspring.strongbox.storage.repository.Repository` class that are currently returning `File`-s. A minor refactoring will be required in order to sort this out.

**Comment by fuss86** [comment]
@ptirador are you working on this ?

**Comment by ptirador** [comment]
Uhm, no at the moment. You can take it if you want.

**Comment by carlspring** [comment]
Implemented by @fu
