### ISSUE TITLE
Make sure AuthenticatorsConfigController is following the How-To-Write-Controllers guide

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#590]
Currently the [AuthenticatorsConfigController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/AuthenticatorsConfigController.java) is not fully following the [How-To-Write-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) guide. This needs to be fixed.

**Comment by ptirador** [comment]
I'm taking this, if there's no problem.

**Comment by carlspring** [comment]
Ok, great!

**Comment by steve-todorov** [comment]
Fixed in #600
