### ISSUE TITLE
Make sure AuthorizationConfigController is following the How-To-Write-Controllers guide

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#591]
Currently the [AuthorizationConfigController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/AuthorizationConfigController.java) is not fully following the [How-To-Write-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) guide. This needs to be fixed.

Also, keep in mind this needs to use Spring Form Validation for adding/updating roles/privileges/etc

**Comment by ptirador** [comment]
I'm taking this on if there's no problem.

**Comment by steve-todorov** [comment]
Sure! :)

**Comment by steve-todorov** [comment]
Fixed in #608
