### ISSUE TITLE
Make the strongbox-web-integration tests use the locally installed tools, or download and install them, if they aren't already installed

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#595]
The [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) requires the following tools to be installed in order to be able to run the tests:
* Gradle
* Maven
* NuGet
* SBT

As Maven is a pre-requisite to running the build, this will not affect Maven.

For Gradle, the script currently uses the `gradlew` wrapper, which is great, unless this is running inside our Docker images, which already have `gradle` installed. Obviously, in this case, there is no need to re-download `gradle` every time. Obviously, this will mean shorter build times in such cases.

It would be best to have the scripts check, if the system has `gradle`, `nuget` and `sbt` installed and, if not, only then try to download and install them from the Internet.

**Comment by SoulSilence** [comment]
I would like to take this task

**Comment by carlspring** [comment]
Ok, thanks! :)

**Comment by carlspring** [comment]
Implemented in a better way in #859, where this is solved by using `docker-compose`.
