### ISSUE TITLE
Check the strongbox-web-integration and potentially remove obsolete tests

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#597]
The following three tests are most-probably obsolete:
* [deploy-and-delete-artifact-directory-to-trash](https://github.com/strongbox/strongbox-web-integration-tests/tree/master/maven/src/it/deploy-and-delete-artifact-directory-to-trash)
* [deploy-and-delete-artifact-directory](https://github.com/strongbox/strongbox-web-integration-tests/tree/master/maven/src/it/deploy-and-delete-artifact-directory)
* [deploy-and-delete-to-trash](https://github.com/strongbox/strongbox-web-integration-tests/tree/master/maven/src/it/deploy-and-delete-to-trash)

To verify this, have a look at the following restassured test cases:
* [TrashControllerTest](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/TrashControllerTest.java)
* [TrashControllerUndeleteTest](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/TrashControllerUndeleteTest.java)

If the equivalent checks are not already done in the `strongbox` project in restassured test classes, then they should be done there instead and the `strongbox-web-integration-tests`.

**Comment by sanket407** [comment]
@carlspring 
> If the equivalent checks are not already done in the strongbox project in restassured test classes, then they should be done there instead and the strongbox-web-integration-tests.

Is the sentence incomplete ? Should it be 

>  If the equivalent checks are not already done in the strongbox project in restassured test classes, then they should be done there instead and the strongbox-web-integration-tests should be removed ?

**Comment by carlspring** [comment]
The three tests that I've mentioned from the `strongbox-web-integration-tests` could probably all be removed. I believe we already have this as tests with restassured, so it doesn't make sense to have them duplicated.

**Comment by sanket407** [comment]
@carlspring  I am not able to get my head around how groovy works. Even though by looking at the integration tests, it looks like they do the same tasks as done by restassured. But I am not able to get how to prove this

**Comment by carlspring** [comment]
@v3rtumnus ,

Would you like to take this task? Is should be quite simple.

**Comment by v3rtumnus** [comment]
I can have a look at it. If I understand you correctly, the goal of this ticket is to see if the mentioned tests in the integration-tests can be removed (and following that conclusion remove them) because they are covered by RestAssured. Is that correct?

**Comment by v3rtumnus** [comment]
Ok thanks for clarification! Will have a look into it

**Comment by v3rtumnus** [comment]
In my opinion, these tests can be removed as you suggested (I have done this in the merge request)
