### ISSUE TITLE
Implement `npm install` command support

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#602]
Currently, we have only partially implemented [npm](https://www.npmjs.com/) layout, so you can publish and download packages.
Within this task we need to implement `npm install` command support according to the [documentation](https://docs.npmjs.com/cli/install).

### How to begiп:
- Deploy/Start strongbox instance locally ([see here](https://github.com/strongbox/strongbox/wiki/Installation)) (or run the `strongbox-web-core`'s Jetty in blocked mode, as explained [here](https://github.com/strongbox/strongbox/wiki/Building-the-code#running-jetty-in-blocked-mode)).
- Follow the [hello-strongbox-npm](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-npm) guide to ensure that `npm publish` works fine for you.

### How to implement:
- First of all you, you will need to do some reverse engineering of how `npm install` works under protocol level. You can trace it with `HeaderMappingFilter` as all `storages` requests passes through this filter.
- Add methods to handle the required HTTP requests in the `NpmArtifactController`.
- To find the requested `npm` package within the *Strongbox* repository, you will need to use the `RepositoryProvider.search` method which will search for packages in the database.
- The results you get will need to be converted to the corresponding JSON format (please note that you should use Jackson Stream API for this, see [JsonFactory.createJsonGenerator](https://fasterxml.github.io/jackson-core/javadoc/2.3.0/com/fasterxml/jackson/core/JsonFactory.html#createGenerator(java.io.OutputStream))).

As a result of this task you need to create unit tests which publish some packages and then resolve them using same HTTP requests as `npm install` does. A follow-up task of this would be #433.

Check [here](https://github.com/strongbox/strongbox/wiki/NPM-Layout-Provider) for details on the NPM layout provider and feel free to update it as necessary.

**Comment by sbespalov** [comment]
@carlspring I have started to work on this.

**Comment by carlspring** [comment]
Great to hear!

**Comment by sbespalov** [comment]
done
