### ISSUE TITLE
Exclude `ru.aristar.jnuget.files.Nupkg` usage from Strongbox

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#611]
Within this task we need to replace `ru.aristar.jnuget.files.Nupkg` implementations usage with our custom entities.

# What should be re-implemented
- `org.carlspring.strongbox.controllers.nuget.NugetArtifactController.putPackage` method;
- `org.carlspring.strongbox.artifact.generator.NugetPackageGenerator`

# What to do
This task can be separated with 2 main parts:

* [ ] We need to be able to extract `nuspec` file from Nuget package
You need to use `java.util.zip.ZipInputStream` or `apache-commons` to extract nuspec file from package and then store it near the original package file within upload request.

* [ ] We need to be able to parse `nuspec` file with JAXB
You can just copy/paste `ru.aristar.jnuget.files.nuspec.NuspecFile` and related POJOs into `org.carlspring.strongbox.nuget.Nuspec` or create your own POJOs with JAXB annotations markup, and then use it to parse `nuspec` files.

Please note that within this task we shouldn't touch `org.carlspring.strongbox.artifact.coordinates.PathNupkg` as it's used to create `PackageFeed` and we will have another upcoming task to rework it.

**Comment by sbespalov** [comment]
@carlspring  can you please review and approve this task?

**Comment by carlspring** [comment]
@SevastyanDark ,

Feel free to pick this task.

**Comment by carlspring** [comment]
@gokhankuyucak :

Are you working on this task? If you are, then @SevastyanDark , perhaps we could find you something else to work on?

**Comment by carlspring** [comment]
@SevastyanDark ,

It might be a good idea to join our [Gitter chat](https://gitter.im/strongbox/strongbox) where all our developers hang out, so you could get quicker help/answers to your questions.

**Comment by SevastyanDark** [comment]
@carlspring yes, i'm working, but i cant get this done.

**Comment by carlspring** [comment]
@SevastyanDark, @gokhankuyucak told me he was working on this.

@gokhankuyucak : What have you done so far?
@SevastyanDark : Have you started this as well? (Also, please join our [Gitter chat](https://gitter.im/strongbox/strongbox)).

**Comment by SevastyanDark** [comment]
@carlspring Yes, i'm reinstalled windows and will continue work.

**Comment by carlspring** [comment]
@gokhankuyucak ,

How's it going? Have you had any time to look into this?

**Comment by carlspring** [comment]
It would be useful to sort this out, before implementing #860.

@gokhankuyucak , @SevastyanDark : Are either of you still interested in looking into this?

**Comment by kalski** [comment]
Hey guys, I like your project and the extensive docs you wrote!
 
Will you assign me this issue to help you out?

**Comment by carlspring** [comment]
Hi,

Please, feel free to take over this task and implement it from scratch!

**Comment by carlspring** [comment]
@kalski , @sbespalov ,

Just as a confirmation, are both tasks in the check-list above done? They are both ready, right? (Or, do we need to create any follow-up tasks for them as well?).
