### ISSUE TITLE
Move `Repository.implementation` into `Storage.implementation`

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#614]
**Repository.implementation** attribute means how repository store it's files, which can be *File System* or cloud storages. But actually the `StorageProvider` implementation is responsible for storage type, so we should have `implementation` atrubute to be in `Storage` instead of `Repository`.

**Comment by carlspring** [comment]
Hm... This is not necessarily so. You could have multiple repositories in a storage that use different data stores.
