### ISSUE TITLE
Upgrade org.junit:* to >= 5.1.0

### ISSUE THREAD

**Issue by ptirador** [strongbox/strongbox#616]
We need to upgrade to the latest version of JUnit: JUnit 5.

In order for JUnit 5 to be compatible with older versions, they have created the `org.junit.jupiter` package to avoid collisions.

Make sure that:
- The project still builds
- The tests are still passing

The version is controlled via the `strongbox-parent/pom.xml`.

The tests can be executed using:

`mvn clean install -Dintegration.tests`

These must all be passing successfully.

**Comment by steve-todorov** [comment]
This task has been picked up by @SevastyanDark.
