### ISSUE TITLE
Add methods for listing the available artifact coordinate validators in the ArtifactCoordinateValidatorsManagementController

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#619]
We need the following new methods added to the `ArtifactCoordinateValidatorsManagementController`
* `listArtifactCoordinateValidators()` : This should return a list of all the available artifact coordinate validators in the registry.
* `listArtifactCoordinateValidatorsForLayoutProvider(String layoutProvider)` : This should return a list of artifact coordinate validators supported for a given layout provider.

**Comment by carlspring** [comment]
@ptirador , @adityasrini ,

Would either of you like to pick this task?

**Comment by adityasrini** [comment]
I'll sign up if @ptirador isn't working on this.

**Comment by adityasrini** [comment]
You got it!

**Comment by carlspring** [comment]
Okay, thanks! :)
