### ISSUE TITLE
Improve `AuthorizationConfig` entity structure

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#629]
For now we have following structure of `AuthorizationConfig`:
```
AuthorizationConfig->Roles->Set<Role>
```
intermediate entity `Roles` is excessive here and need to be reduced.

#### How to do
1. Make `AuthorizationConfig` entity look like follows:
```
AuthorizationConfig
{
    private Set<Role> roles  = new LinkedHashSet<>();
}
```
2. Remove `org.carlspring.strongbox.security.Roles` class;
3. Resolve all compilation errors;
4. Create DB migration script to drop `AuthorizationConfig.roles` field, and replace it with `AuthorizationConfig.Set<Role>` field;
migration should be placed in `strongbox-data-service/src/main/db/changelog/v1.0.0`
5. Check that `mvn clean install` completes with `SUCESS` result.

**Comment by sbespalov** [comment]
@steve-todorov this task can affect on API and UI part;

**Comment by steve-todorov** [comment]
Breaking the UI part is fine by me. Ping @carlspring regarding the API part - he's currently doing some refactoring to the API and moving it into a separate context.. :)

**Comment by carlspring** [comment]
As there is no UI as of yet, I see no issue with proceeding with this. :)

**Comment by ptirador** [comment]
I'd like to work on this issue.

**Comment by carlspring** [comment]
Okay, Pablo!

**Comment by sbespalov** [comment]
@ptirador there is upcoming similar task #670
