### ISSUE TITLE
Refactor the configuration controller into multiple sub-controllers and move existing configuration classes into the new locations

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#630]
### Description
The [ConfigurationManagementController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/ConfigurationManagementController.java) is becoming bigger and harder to work with. We need to refactor this controller into smaller sub-controllers - each of which will only handle a specific part of the configuration. The working configuration code needs to be moved from `org.carlspring.strongbox.controllers.ConfigurationManagementController` into `org.carlspring.strongbox.controllers.configuration.*`.

Please keep in mind to create/modify/move existing test cases into new classes with the appropriate names.

### What needs to be done:

* Create a new package `org.carlspring.strongbox.controllers.configuration`.
* Move `org.carlspring.strongbox.controllers.security.login` into `org.carlspring.strongbox.controllers.login`
* Move `org.carlspring.strongbox.controllers.security` into `org.carlspring.strongbox.controllers.configuration.security`
* Move `AuthenticatorsConfigController` into `org.carlspring.strongbox.controllers.configuration.security.authentication`.
* Move `AuthorizationConfigController` into `org.carlspring.strongbox.controllers.configuration.security.authorization`.
* Create a new class named `ServerConfigurationController` in `org.carlspring.strongbox.controllers.configuration`. This class will hold methods for configuring core server settings such as `port`, `baseUrl` and other similar configuration properties.
* Create a new class named `StrongboxConfigurationController` in `org.carlspring.strongbox.controllers.configuration`. This class will hold the `getConfigurationXML` and `setConfigurationXML` methods.
* Create a new class named `ProxyConfigurationController` in `org.carlspring.strongbox.controllers.configuration` and move all proxy related configuration there.
* Create a new class named `StoragesConfigurationController` in `org.carlspring.strongbox.controllers.configuration` and move all storage related configuration there.
* Create a new class named `RoutingConfigurationController` in `org.carlspring.strongbox.controllers.configuration` and move all routing related configuration there.

**Comment by ptirador** [comment]
I'll take it :)

**Comment by carlspring** [comment]
Implemented by @ptirador in #633.
