### ISSUE TITLE
Make the strongbox-web-core use the OrientDB in-memory when running Jetty in blocked mode

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#634]
In the `strongbox-web-core/pom.xml`, under the settings of the `jetty-maven-plugin`, add and option for -`orientdb.profile=orientdb_MEMORY`.

Test things and make sure the OrientDB only takes a moment to load, as opposed to half a minute.

**Comment by sbespalov** [comment]
@carlspring it's fixed

**Comment by carlspring** [comment]
Resolved.
