### ISSUE TITLE
`Repository#httpConnectionPool` field is not respected for new repositories added in runtime

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#653]
We use the `org.apache.http.impl.conn.PoolingHttpClientConnectionManager` to maintain pool of HTTP connections per repository. By default, we have some predefined value specifying max number of connections in pool for each repository/route.

Every repository may be defined with its own value of max connections in pool (`repository.getHttpConnectionPool().getAllocatedConnections()`). This value per repository is respected in the initial run of the application (when the repository configuration is read from the XML file) (see `org.carlspring.strongbox.config.StorageApiConfig#setProxyRepositoryConnectionPoolConfigurations`). 

There is an option to add/edit repository in runtime (see `org.carlspring.strongbox.controllers.configuration.StoragesConfigurationController#addOrUpdateRepository`). 

**Issue**: When we deliver a new repository with a custom value of max number of connections in pool - this value is not respected and taken into account (besides it's stored in the database, but does not affects our pooling manager.

**Comment by fuss86** [comment]
@v3rtumnus, are you open for this task ?

**Comment by v3rtumnus** [comment]
I can have a look at it :)

**Comment by carlspring** [comment]
Thanks! :)
