### ISSUE TITLE
Upgrade org.apache.commons:commons-compress to version 1.16 or higher

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#654]
As described in [this vulnerability warning](https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-32122), we should upgrade our direct and transitive dependencies of org.apache.commons:commons-compress to version 1.16 or higher. If this is coming via a transitive dependency and there is a newer version of it that already uses a recent enough version of org.apache.commons:commons-compress, then we should upgrade to that. We need to make sure that no transitive dependencies are bringing this.

**Comment by ptirador** [comment]
I'm picking this up.

**Comment by carlspring** [comment]
Fixed! ;)
