### ISSUE TITLE
Refactor the UserController to use form validation and return proper responses on failed validation

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#660]
The `UserController` needs to be refactored so that it uses spring form validation. Also, make sure that the controller returns the proper responses according to the [How-To-Implement-Spring-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) when there is an error in the validation.

**Comment by ptirador** [comment]
I'll pick this up :)

**Comment by steve-todorov** [comment]
Happy coding! :)

**Comment by ptirador** [comment]
In this method:
```
public ResponseEntity updateAccessModel(@ApiParam(value = "The name of the user") @PathVariable String username,
                                        @RequestBody AccessModel accessModel,
                                        @RequestHeader(HttpHeaders.ACCEPT) String accept)
```

Do I need to validate `AccessModel` object? In that case, what should I validate? It has 3 `Maps` as attributes...

**Comment by steve-todorov** [comment]
@carlspring, @fuss86 , @sbespalov could one of you pitch in and let @ptirador know what needs to be validated here. I believe the submitted `accessModel` should be validated (as well as anything that is accepted from the user and saved in the database) but I'm not sure what exactly needs to be validated.

**Comment by carlspring** [comment]
@fuss86 ,

As I won't be around tonight, would you mind having a look? Many thanks! :)

**Comment by fuss86** [comment]
Every map fits into the following validation rules:
* not mandatory
* if provided then
  * keys _should_ follow pattern `/storages/${storageId}/${repositoryId}`
  * values _should not_ be `empty` nor `null`

Each map is independent to the others.

**Comment by ptirador** [comment]
@fuss86 Thanks for the info. What about the `User` class? It has these attributes:

```
private String username;
private String password;
private boolean enabled;
private Set<String> roles;
private String securityTokenKey;
private AccessModel accessModel;
```

**Comment by steve-todorov** [comment]
`username` - required, must not be blank
`password` - required, must not be blank and must be more than 6 symbols
`enabled` - can be either true or false.
`roles` - should be an array of valid roles.
`securityToken` - this was used for `nuget` and I'm not sure, @sbespalov could you give your thoughts?
`accessModel` - I believe @fuss86 already answered this?

**Comment by ptirador** [comment]
Thanks @steve-todorov!

**Comment by carlspring** [comment]
@ptirador ,

Yes, you are right. There are the also these follow-up issues:
* There's `org.carlspring.strongbox.security.User` and `org.carlspring.strongbox.users.domain.User`, vs. `org.carlspring.strongbox.controllers.users.UserInput`. I think there is some duplication here that needs to be sorted out. I don't personally support the idea of having multiple classes with the same name under the same project. I think that some one of the `User` classes needs to be removed, or merged into, or replaced by the `UserInput` class. Perhaps I'm missing something here...? @fuss86 / @sbespalov : What are your thoughts on this?
* There's `org.carlspring.strongbox.security.Users` which I would say should also be removed. @ptirador : Would you like to look into this?

**Comment by ptirador** [comment]
@carlspring,

The classes `org.carlspring.strongbox.security.Users` and `org.carlspring.strongbox.security.User` are used as mapping classes to load users from XML configuration file. For this, they need to be annotated with XML annotations. They could be renamed to `UsersXml` and `UserXml`, or something more appropiate.

On the other hand, the class `org.carlspring.strongbox.users.domain.User` seems to be used for DB operations (retrieve, update, delete, etc).

The class `org.carlspring.strongbox.controllers.users.UserInput` is gonna be replaced by `org.carlspring.strongbox.forms.users.UserForm`, which contains validation annotations and it's gonna be used in user validations when creating/updating a user.

I think that all of them have different functions, and they could be renamed depending on that. But I don't think that it could be a good idea to remove/merge them.

**Comment by carlspring** [comment]
Okay, thanks for the clarification!

**Comment by carlspring** [comment]
Fixed by @ptirador! :)
