### ISSUE TITLE
Create a new endpoint in ServerConfigurationController which will handle a form for submitting both baseUrl and port

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#661]
We need to create a new endpoint in the `ServerConfigurationController` which will be responsible for validating a form which contains both the `baseUrl` and `port`. This endpoint will be used in the front-end to "bulk" update the url and port. Please make sure you follow the  [How-To-Write-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) guide.

Validation rules:
* `baseUrl` should **not** be `blank` or `null`
* `port` should be an integer between `1` and `65535`

The endpoint will receive the following json:

```
{
    "baseUrl": "http://some-url.com/",
    "port": 1234
}
```

**Comment by ptirador** [comment]
I'll take this. Name if the new endpoint?

**Comment by steve-todorov** [comment]
I think `/form` would be ok. Do you have better ideas? :)

**Comment by ptirador** [comment]
I was thinking about `/serverSettings`. I'm not sure...

**Comment by steve-todorov** [comment]
`serverSettings` it is then. We can always rename it later if we find a better name. :)
