### ISSUE TITLE
Improve `UserAccessModel` class structure

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#670]
We need to remove XML list wrapper classes starting from `UserAccessModel` down to the component structure tree. 
Following wrapper classes should be directly replaced with collections:
- `UserAccessModel.UserStorages` replace with `UserAccessModel.Set<UserStorage>`  and remove `UserStorages` class
- `UserStorage.UserRepositories` replace with `UserStorage.Set<UserRepository>`  and remove `UserRepositories` class
- `UserRepository.Privileges` replace with `UserRepository.Set<Privilege> `  and remove `Privileges` class

#### How to do
1. Make code modifications described above
2. Resolve all compilation errors;
3. Check that `mvn clean install` completes with `SUCCESS` result.

_*Note that we wouldn't need any DB modification scripts here*_

**Comment by ptirador** [comment]
I'll take this.

**Comment by carlspring** [comment]
Okay, thanks! I've assigned it to you! :)
