### ISSUE TITLE
Create `ArtifactEntry.created` property

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#683]
New property should looks like this:
```
ArtifactEntry {
    ...
    private Date created;
    ...
}
```
Also we need to populate this property with `new Date()` every time we store new `ArtifactEntry` instance in DB.
Note that we shouldn't initialize field with `new Date()` directly in class definition, we must do it in code which crates new `ArtifactEntry` instead.

_**PS**_
new Liquibase changeset required here to modify our DB schema.

**Comment by mkuligowski** [comment]
Let me take this one

**Comment by carlspring** [comment]
Hi @mkuligowski ,

Feel free to pick this task! :)

**Comment by carlspring** [comment]
@mkuligowski ,

Also, please feel free to join our [Gitter chat](gitter.im/strongbox/strongbox) where all the developers hang out and where you could get help, if you need it.

**Comment by carlspring** [comment]
Implemented by @mkuligowski! :)
