### ISSUE TITLE
Refactor RoutingConfigurationController to use Form Validation and make sure it follows the How-To-Write-Controllers guide

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#692]
The `RoutingConfigurationController` needs to be refactored so that it uses spring form validation. Also, make sure that the controller returns the proper responses according to the [How-To-Implement-Spring-Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) when there is an error in the validation. 

Validation rules for `RuleSet`:

| Field | Validation  |
| --- | --- |
| groupRepository | required |
| routingRules | required |

Validation rules for `RoutingRule`:

| Field | Validation  |
| --- | --- |
| pattern | required |
| repositories | required |

**Comment by carlspring** [comment]
Fixed!
