### ISSUE TITLE
AQL case insensetive keywords

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#721]
Within this task we need to make AQL keywords case insensitive. This should be done within antlr grammar, so all the keyword rules will look like below:
```
STORAGE
:
   [s|S][t|T][o|O][r|R][a|A][g|G][e|E]
;
```

### How to implement:

- you need to modify **antlr** grammar file `strongbox-aql/src/main/antlr4/AQL.g4`;
- keyword rules are all uppercase named (it's anltr convention), so you need modify all such rules that contains keywords;
- at the end you need to make `mvn clean install` to be sure that compilation and tests are not broken;

**Comment by sbespalov** [comment]
@carlspring can you please approve this task?

**Comment by carlspring** [comment]
@sbespalov ,

Thanks, I approve it!

**Comment by carlspring** [comment]
Useful links:
* [ANTLR: Case-insensitive Lexing](https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md)
* https://github.com/antlr/antlr4/issues/1002
