### ISSUE TITLE
Use awaitility for asynchronous tests

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#795]
We should get rid of `org.carlspring.strongbox.cron.jobs.BaseCronJobWithMavenIndexingTestCase#expectEvent(long, long)` and `org.carlspring.strongbox.cron.jobs.BaseCronJobWithMavenIndexingTestCase#expectEvent()` methods and simplify all subtypes of `org.carlspring.strongbox.cron.jobs.BaseCronJobWithMavenIndexingTestCase` by using https://github.com/awaitility/awaitility tool.

**Comment by v3rtumnus** [comment]
I could do that if no one else is working on it :)

**Comment by fuss86** [comment]
Don't hesitate to start doing it 👍

**Comment by carlspring** [comment]
@v3rtumnus ,

This would be much appreciated! Please, feel free to take this task! Also, I would like to recommend that you join our [Gitter](https://gitter.im/strongbox/strongbox) channel where the other developers hang out and where you could get answers and help. :)

**Comment by fuss86** [comment]
Good job, @v3rtumnus ! @carlspring it's good to be merged !
