### ISSUE TITLE
Upgrade com.google.guava:guava to version 24.1.1 or higher

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#797]
As described [here](https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236), earlier versions of Guava are prone to deserialization of untrusted data vulnerability.

**Comment by ptirador** [comment]
I see that the current version used in strongbox is 25.0-jre, which is greater than 24.1.1-jre. The latest version of guava is 26.0-jre. Should it be updated to the latest one?

**Comment by carlspring** [comment]
Hi,

In this case, it seems it has been resolved as a transitive dependency of one of the vulnerable dependencies fixed by the Snyk.io bot! Thanks for double-checking!
