### ISSUE TITLE
Upgrade org.junit:* to >= 5.3.0 and upgrade tests annotations

### ISSUE THREAD

**Issue by ptirador** [strongbox/strongbox#803]
In the last issue about upgrading to JUnit 5 (#616), version was upgraded in poms but not test annotations in Java test classes. See more at [this link](https://junit.org/junit5/docs/5.0.2/user-guide/#migrating-from-junit4).

Make sure that:

- JUnit version is upgraded to 5.3.0

- JUnit 5 anotations are used in tests.

- The project still builds

- The tests are still passing

The version is controlled via the `strongbox-parent/pom.xml`.

The tests can be executed using:

`mvn clean install -Dintegration.tests`

These must all be passing successfully.

**Comment by ptirador** [comment]
I'm taking it if there's no problem about it.

**Comment by carlspring** [comment]
Great! Glad to see you're back!
Please, feel free to proceed!

**Comment by carlspring** [comment]
(Closed by accident).
