### ISSUE TITLE
Create an RPM distribution

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#840]
We are currently producing `zip` and `gzip` packages for our distribution. We need to be able to create RPM distributions using the [`rpm-maven-plugin`](https://www.mojohaus.org/rpm-maven-plugin/) (or similar). The place where we produce our assemblies is the [`strongbox-distribution`](https://github.com/strongbox/strongbox/tree/master/strongbox-distribution) module.

This task is similar to #841 and depends on #801 to be finished.

**Comment by v3rtumnus** [comment]
Hi @carlspring , I just created a PR for this. Could you please have a look into it, as my experience with RPM packages is limited and I am not completely sure that this is what you expect as outcome of this issue.

**Comment by carlspring** [comment]
Do you know, if it's possible to set up services via this plugin?

**Comment by v3rtumnus** [comment]
I am not sure unfortunately since I cannot test it (running on a debian based system atm)

**Comment by carlspring** [comment]
Would you like to try it under Docker with an image from [here](https://hub.docker.com/_/centos/)?

I think that, optimally, the produced `rpm` should be able to register the service management scripts which are packaged in the distribution. I assume this is possible with the plugin. Perhaps we will need to create a spec file.

Check out these resources:
* http://ftp.rpm.org/max-rpm/s1-rpm-build-creating-spec-file.html
* https://rpm-packaging-guide.github.io/
* https://fedoraproject.org/wiki/How_to_create_a_GNU_Hello_RPM_package

**Comment by v3rtumnus** [comment]
Will have a look into it!
