### ISSUE TITLE
Implement RpmArtifactCoordinates

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#847]
# Task Description

We need to identify what the artifact coordinates are for Yum (RPM) packages and implement a class for this. 

The code should be located in a class called `YumArtifactCoordinates` under `strongbox/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-yum-layout-provider/src/main/java/org/carlspring/strongbox/artifact/coordinates`.

Have a look at the [Artifact Coordinates](https://strongbox.github.io/knowledge-base/artifact-coordinates.html) wiki page for more information.

Whoever takes on the `yum`/`rpm` tasks will need to have:
- Sufficient knowledge and experience with Linux
- A Linux environment in which to test
- At least some basic knowledge `yum`/`rpm` in order to have their own opinion of what's required

This is a sub-task of #845 . It should be relatively straight-forward to implement this and you should get acquainted with the master task, before proceeding.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by shalini-s** [comment]
I'll take this!

**Comment by carlspring** [comment]
Okay, thanks! Have a look at the master task as well.
Are you familiar with `yum` and  `rpm`?

**Comment by shalini-s** [comment]
I'm not that familiar with it, but I'm looking to learn. I'm reading though the master task - are there any other resources I should look at?

**Comment by carlspring** [comment]
Generally, this would require some level of familiarity with `rpm`, `yum` and Linux. It may be worth joining our [gitter](gitter.im/strongbox/strongbox) chat channel.

**Comment by shalini-s** [comment]
Okay, I'll let someone else take it then.

**Comment by carlspring** [comment]
Have a look at [this](https://bobcares.com/blog/rpm-basics/) article.

> RPM packages are usually named using the following convention:
> 
> <name>-<version>-<release>.<arch>.rpm
> Consider the Apache RPM package – httpd-2.0.53-3.3.i386.rpm, then
> 
> httpd – name of the software
> 2.0.53 – software version (that of the original software source)
> 3.3 – package release
> i386 – architecture
> 
> Corresponding source package is httpd-2.0.53-3.3.src.rpm (note ‘src’ in the name).
>

Based on the additional example in the line above, I'd say the coordinates, are (actually) most-probably five, (and not just four):

```
<name>-<version>-<release>.<arch>.<classifier>.rpm
```

So, the coordinates would be:
| Coordinate       | Description                               | Is Mandatory |
|  --------------------- | ------------------------------------------ | ------------------- |
|  name               |  The name of the `rpm` package  |  Yes  |
|  version            |  The version of the `rpm` package  |  Yes  |
|  release            |  The release of the `rpm` package  |  Yes  |
|  arch                 |  The name of the `rpm` package  |  No (if none specified, this should default to `noarch`  |
|  classifier          |  Denotes that this is a variation, or additional part of the package (for example, documentation, or other secondary part of an artifact)  |  No  |

Whoever takes on the on the `yum`/`rpm` tasks will need to have:
- Sufficient knowledge and experience with Linux
- A Linux environment in which to test
- At least some basic knowledge `yum`/`rpm` in order to have their own opinion of what's required

**Comment by carlspring** [comment]
@shalini-s ,

If you think this task is something you can do and if you have the proper environment in which to test it and do the necessary research, then, by all means, feel free to proceed! If not, please join our [gitter](gitter.im/strongbox/strongbox) chat channel and we'll try to find you some tasks with which you could help out! :)

**Comment by Alov** [comment]
@carlspring Hi!
Can I take this feature? Any other from YUM-support pool?

**Comment by carlspring** [comment]
@Alov : 

Feel free to look into it, if you're experienced with `yum` and `rpm`. We are currently more focused on polishing up our support for `npm` and pushing forward with our implementation of the `pypi` layout support.

I think it would be best to discuss this on our [chat channel](https://chat.carlspring.org/). Looking forward to seeing you there! :)
