### ISSUE TITLE
`LayoutProvider.containsPath` should be replaced with `RepositoryFiles.artifactExists`

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#884]
What need to be done:
- replace `LayoutProvider.containsPath` with `RepositoryFiles.artifactExists` in `GroupRepositoryArtifactExistenceChecker`
- drop `LayoutProvider.containsPath` method
- check that corresponding logic in `GroupRepositoryArtifactExistenceChecker` covered with UnitTests

**Comment by vigneshtdev** [comment]
where can the tests for the <code>GroupRepositoryArtifactExistenceChecker</code> be found?

**Comment by sbespalov** [comment]
@vigneshtdev you can trace this class call stack in you IDE and look REST controllers and Cron Jobs which using it. Then you will be able to find tests.

**Comment by vigneshtdev** [comment]
@sbespalov  thanks for the reply. I am unable to resolve a dependency issue, which is causing an import failure & I am not able to run the existing test cases.

The import which is failing is <code>import org.carlspring.maven.commons.util.ArtifactUtils;</code>
Package maven is not found.

**Comment by sbespalov** [comment]
you should use [settings.xml](https://raw.githubusercontent.com/wiki/strongbox/strongbox/resources/maven/settings.xml)

**Comment by vigneshtdev** [comment]
@sbspalov Thanks, was able to fix it.
