### ISSUE TITLE
`LayoutProvider.deleteMetadata` method should be moved into `Maven2FileSystemProvider`

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#885]
What need to be done:
- move `deleteMetadata` method from `LayoutProvider` into `RepositoryLayoutFileSystemProvider` with `protected` modifier
- `RepositoryLayoutFileSystemProvider.deleteMetadata` should be called within `RepositoryLayoutFileSystemProvider.delete`, so all corresponding metadata should be removed within artifact delete,
- move `Maven2LayoutProvider.deleteMetadata` logic into `Maven2FileSystemProvider.deleteMetadata`
- use `Files.delete` method instead of `LayoutProvider.deleteMetadata` in `MavenMetadataGroupRepositoryComponent.cleanupGroupW
 henArtifactPathNoLongerExistsInSubTree`
- check that corresponding logic in `GroupRepositoryArtifactExistenceChecker` covered with Unit Tests
- provide additional tests if needed

**Comment by CodeJoshCode** [comment]
I'm going in!
