### ISSUE TITLE
Upgrade Jetty to 9.4.12.v20180830

### ISSUE THREAD

**Issue by bamarch** [strongbox/strongbox#890]
Using the current Jetty version of 9.4.6 there is a RuntimeException when starting Jetty, see here https://gist.github.com/bamarch/72bba0d8ca988902b2d7e9fd9bcdd6c4

The issue is related to compatibility with JDK 9 features that are present in some dependency jars.

The solution is to either downgrade the jars or upgrade Jetty (to a version >= 9.4.9). 

Relates to:
https://github.com/strongbox/strongbox/issues/407 
https://github.com/strongbox/strongbox/issues/421 
https://github.com/strongbox/strongbox/issues/422
https://github.com/strongbox/strongbox/pull/804

**Comment by carlspring** [comment]
If things are working properly after our recent Spring Boot migration, perhaps we should close all these similar tasks?
