### ISSUE TITLE
Re-structure the Maven layout provider modules

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#895]
We need a small refactoring in order to tidy up our Maven layout modules.

The following is required:
- [x] Rename the `strongbox-metadata-maven-api` module to `strongbox-maven-metadata-api`.
- [x] Reflect the above change in all `pom.xml` files that are affected.
- [x] Create a new aggregator called `strongbox-storage-maven-layout` under `strongbox-storage/strongbox-storage-layout-providers`.
- [x] Move the `strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout-provider` module under the `strongbox-storage-maven-layout` aggregator.
- [x] Move the `strongbox-storage/strongbox-storage-layout-providers/strongbox-maven-metadata-api` module under the `strongbox-storage-maven-layout` aggregator.
- [x] Make sure all the unit and integration tests are still passing.
- [ ] Update the links in the wiki for the following wiki pages:
* [Maven 2 Layout Provider](https://github.com/strongbox/strongbox/wiki/Maven-2-Layout-Provider)
* [Maven Indexer](https://github.com/strongbox/strongbox/wiki/Maven-Indexer)
* [Maven Metadata](https://github.com/strongbox/strongbox/wiki/Maven-Metadata)

**Comment by ben-dasilva** [comment]
I would be glad to help with these Maven changes, if that's okay.

**Comment by carlspring** [comment]
This task is now still up for grabs.

**Comment by carlspring** [comment]
Leaving this open due to the wiki pages.

**Comment by bamarch** [comment]
> Leaving this open due to the wiki pages.

👍 I'll do them - but I will be out of action until next week whilst I'm abroad

**Comment by bamarch** [comment]
> * [ ]  Update the links in the wiki for the following wiki pages:
> 
> * [Maven 2 Layout Provider](https://github.com/strongbox/strongbox/wiki/Maven-2-Layout-Provider)
> * [Maven Indexer](https://github.com/strongbox/strongbox/wiki/Maven-Indexer)
> * [Maven Metadata](https://github.com/strongbox/strongbox/wiki/Maven-Metadata)

I updated the first two wiki pages - I was not sure how [Maven Metadata](https://github.com/strongbox/strongbox/wiki/Maven-Metadata) would require updating though, maybe you could take a look? ta

**Comment by carlspring** [comment]
Thanks for updating the links! It's all good! :)
