### ISSUE TITLE
Write test cases that check if all user interface assets are accessible

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#916]
We need to have some tests which check if UI assets are accessible. This should be done by reading the `assets-manifest.json` and doing a `for` loop which goes through all of the assets in the manifest and tries to access them with a request to the defined URL. 

The `assets-manifest.json` is available in `strongbox-web-core/target/assets-manifest.json` and will look like so:

```
{
  "Raleway-Thin.b2a0b765ded79576d3bb.ttf": "/static/assets/Raleway-Thin.b2a0b765ded79576d3bb.ttf",
  "3rdpartylicenses.txt": "/static/assets/3rdpartylicenses.txt",
  "index.html": "/",
  "ionicons.3c1e04901e63bef6c26c.eot": "/static/assets/ionicons.3c1e04901e63bef6c26c.eot",
  "ionicons.43d5c718339efeb1177a.woff2": "/static/assets/ionicons.43d5c718339efeb1177a.woff2",
  "ionicons.91433571f154776a1d46.svg": "/static/assets/ionicons.91433571f154776a1d46.svg",
  "ionicons.a21b9e1aad96623ef91b.woff": "/static/assets/ionicons.a21b9e1aad96623ef91b.woff",
  "ionicons.b2e0fc821c6886fb3940.ttf": "/static/assets/ionicons.b2e0fc821c6886fb3940.ttf",
  "main.0ba4015931f246f1a40e.js": "/static/assets/main.0ba4015931f246f1a40e.js",
  "OpenSans-Light.804037562eabaa5dbefa.eot": "/static/assets/OpenSans-Light.804037562eabaa5dbefa.eot",
  "OpenSans-Light.963eb32907744d9a0d6b.woff": "/static/assets/OpenSans-Light.963eb32907744d9a0d6b.woff",
  "OpenSans-Light.d79f021974b1f6bc5c21.svg": "/static/assets/OpenSans-Light.d79f021974b1f6bc5c21.svg",
  "OpenSans-Light.ecb4572a5e478b107dfc.ttf": "/static/assets/OpenSans-Light.ecb4572a5e478b107dfc.ttf",
  "polyfills.3ca8e1b4eda190f0a777.js": "/static/assets/polyfills.3ca8e1b4eda190f0a777.js",
  "4.2849da486e5a17f69b3d.js": "/static/assets/4.2849da486e5a17f69b3d.js",
  "runtime.15e5a56fbcf9e0436e1f.js": "/static/assets/runtime.15e5a56fbcf9e0436e1f.js",
  "styles.b2373954c17d12df6c1a.css": "/static/assets/styles.b2373954c17d12df6c1a.css",
  "4.2849da486e5a17f69b3d.js.gz": "/static/assets/4.2849da486e5a17f69b3d.js.gz",
  "polyfills.3ca8e1b4eda190f0a777.js.gz": "/static/assets/polyfills.3ca8e1b4eda190f0a777.js.gz",
  "styles.b2373954c17d12df6c1a.css.gz": "/static/assets/styles.b2373954c17d12df6c1a.css.gz",
  "OpenSans-Light.804037562eabaa5dbefa.eot.gz": "/static/assets/OpenSans-Light.804037562eabaa5dbefa.eot.gz",
  "OpenSans-Light.ecb4572a5e478b107dfc.ttf.gz": "/static/assets/OpenSans-Light.ecb4572a5e478b107dfc.ttf.gz",
  "ionicons.3c1e04901e63bef6c26c.eot.gz": "/static/assets/ionicons.3c1e04901e63bef6c26c.eot.gz",
  "Raleway-Thin.b2a0b765ded79576d3bb.ttf.gz": "/static/assets/Raleway-Thin.b2a0b765ded79576d3bb.ttf.gz",
  "ionicons.b2e0fc821c6886fb3940.ttf.gz": "/static/assets/ionicons.b2e0fc821c6886fb3940.ttf.gz",
  "OpenSans-Light.d79f021974b1f6bc5c21.svg.gz": "/static/assets/OpenSans-Light.d79f021974b1f6bc5c21.svg.gz",
  "ionicons.91433571f154776a1d46.svg.gz": "/static/assets/ionicons.91433571f154776a1d46.svg.gz",
  "main.0ba4015931f246f1a40e.js.gz": "/static/assets/main.0ba4015931f246f1a40e.js.gz"
}
```

Once you've parsed the `JSON` manifest the test should go through all of the paths (i.e. `/static/assets/Raleway-Thin.b2a0b765ded79576d3bb.ttf`) and check if it's accessible.

To check the `index.html`, you should make a request to `/` and check if the response is with `Status 200`. The test should also make sure the returned `HTML` contains all of these strings:
* `/static/assets/styles.([a-zAZ0-9]+).css`
* `/static/assets/runtime.([a-zAZ0-9]+).js`
* `/static/assets/polyfills.([a-zAZ0-9]+).js`
* `/static/assets/main.([a-zAZ0-9]+).js`

**Comment by carlspring** [comment]
@goel-sunny , please feel free to take it. Nobody else is working on this at the moment.

**Comment by steve-todorov** [comment]
@goel-sunny apologize, the right path is `./strongbox-web-core/target/classes/assets-manifest.json`

**Comment by carlspring** [comment]
You don't need to know where it is on the file system really, you'll be testing this with RestAssured.

**Comment by steve-todorov** [comment]
@carlspring Actually this file is not exposed via the public, so it's not accessible via http/rest. You need to read it from the filesystem/classpath i.e. with `Resource manifest = new ClassPathResource("assets-manifest.json");`. Afterwards - iterate over the assets to check if they are accessible by doing an actual http request using RestAssured. :)

**Comment by ptirador** [comment]
@steve-todorov: Can I take this issue? Or is @goel-sunny still working on it?

**Comment by carlspring** [comment]
@ptirador: Please, feel free to take it!
