### ISSUE TITLE
Upgrade `org.springframework.security:spring-security-ldap` to versions `5.0.9`, `5.1.1`, or higher

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#919]
# Overview
This issue has been reported by snyk.io.
[org.springframework.security:spring-security-ldap](https://springframework.org/) provides security services for the Spring IO Platform. 

Affected versions of the package are vulnerable to Authentication Bypass.

# Remediation
Upgrade `org.springframework.security:spring-security-ldap` to versions `5.0.9`, `5.1.1`, or higher.

# References
[GitHub Commit](https://github.com/spring-projects/spring-security/commit/7269aacbdd42183afeedc84e2233580b917da4c0)
[GitHub Issue](https://github.com/spring-projects/spring-security/issues/3392)

**Comment by ptirador** [comment]
With the migration to Spring Boot, i think the Spring Security versions cannot be updated specifically. I guess that if Spring Boot is update to last version (2.1.0 now), it will update the rest of dependencies.

According to this [release note](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes), Spring Boot 2.1 builds on and requires Spring Framework 5.1.

**Comment by carlspring** [comment]
@ptirador ,

Thanks for following up on this! I think we need to wait a newer release that contains the proper version, or maybe even raise an issue with the Spring Boot guys to bump in a newer version...?

**Comment by ptirador** [comment]
@carlspring, 

What I meant is that, if we update Spring Boot to `2.1.0`, all Spring Security dependencies will be updated automatically to `5.1.1`. That solves your problem?

**Comment by carlspring** [comment]
I see! I must have misunderstood. Well, let's try upgrading Spring Boot to `2.1.0`, then! :)

**Comment by ptirador** [comment]
I'll start on it.
