### ISSUE TITLE
JUnit 5 - Parameterize tests using annotation @ParameterizedTest

### ISSUE THREAD

**Issue by ptirador** [strongbox/strongbox#929]
WIth the new migration to JUnit 5, many tests can be now parameterized. The most typical examples are located in `strongbox-web-core` tests:
```

    @Test
    public void shouldNotRemoveAliasNotFoundWithResponseInJson()
    {
        shouldNotRemoveAliasNotFound(MediaType.APPLICATION_JSON_VALUE);
    }

    @Test
    public void shouldNotRemoveAliasNotFoundWithResponseInText()
    {
        shouldNotRemoveAliasNotFound(MediaType.TEXT_PLAIN_VALUE);
    }

    private void shouldNotRemoveAliasNotFound(String acceptHeader)
    {
        String url = getContextBaseUrl() + "/{storageId}/{repositoryId}/{alias}";
        String repositoryId = "releases-with-default-validators";
        String alias = "alias-not-found";

        given().header(HttpHeaders.ACCEPT, acceptHeader)
               .when()
               .delete(url, STORAGE0, repositoryId, alias)
               .peek()
               .then()
               .statusCode(HttpStatus.NOT_FOUND.value())
               .body(containsString(NOT_FOUND_ALIAS_MESSAGE));
    }
```

This can be parameterized like this:

```

   @ParameterizedTest
   @ValueSource(strings = { MediaType.APPLICATION_JSON_VALUE, MediaType.TEXT_PLAIN_VALUE })
    void shouldNotRemoveAliasNotFound(String acceptHeader)
    {
        String url = getContextBaseUrl() + "/{storageId}/{repositoryId}/{alias}";
        String repositoryId = "releases-with-default-validators";
        String alias = "alias-not-found";

        given().header(HttpHeaders.ACCEPT, acceptHeader)
               .when()
               .delete(url, STORAGE0, repositoryId, alias)
               .peek()
               .then()
               .statusCode(HttpStatus.NOT_FOUND.value())
               .body(containsString(NOT_FOUND_ALIAS_MESSAGE));
    }
```

List of affected tests classes:

`strongbox-web-core`:

- [x] `ArtifactCoordinateValidatorsManagementControllerTest`
- [ ] `AuthenticatorsConfigControllerTestIT`
- [x] `AuthorizationConfigControllerTestIT`
- [ ] `CorsConfigurationControllerTest`
- [x] `HttpConnectionPoolConfigurationManagementControllerTestIT`
- [ ] `LoggingManagementControllerTestIT`
- [x] `PingControllerTest`
- [x] `ProxyConfigurationControllerTestIT`
- [x] `RoutingConfigurationControllerTestIT`
- [x] `ServerConfigurationControllerTestIT`
- [x] `TrashControllerTest`
- [x] `TrashControllerUndeleteTest`
- [ ] `UserControllerTestIT`

The following guides can be used:
* [Strongbox wiki](https://github.com/strongbox/strongbox/wiki/JUnit-User-Guide#parameterized-tests)
* [Official guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests)

**Comment by carlspring** [comment]
Yeah, we could make a list of such tests and improve them.

**Comment by fuss86** [comment]
This is really great proposal, thank you @ptirador ! Awesome ! 

👍

**Comment by adavid9** [comment]
@carlspring Hi, can I work on this one?

**Comment by carlspring** [comment]
Hi!

Yes, of course!

There are also a few more tasks relating to JUnit in the issue tracker. Feel free to have a look at those as well!

**Comment by carlspring** [comment]
@adavid9 ,

What is the status of this task? Is there indeed still work to be done?

**Comment by adavid9** [comment]
@carlspring Hi, there left just 2 tests that should be rewritten, `LoggingManagementControllerTestIT` has been `@Disabled` and is not in use, so you can cross out this one.

**Comment by adavid9** [comment]
@carlspring This issue can be closed, because all tests has been parameterized. One of them it is `Logging` is to cross out, because this one was disabled by Przemyslaw.

**Comment by carlspring** [comment]
Thanks for clarifying this, @adavid9, and thanks for all your help! :)
