### ISSUE TITLE
Fix failing test in strongbox-web-integration-tests for NuGet Layout Provider

### ISSUE THREAD

**Issue by ptirador** [strongbox/strongbox#944]
After the [Spring Boot upgrade to 2.1.0 version](https://github.com/strongbox/strongbox/issues/919) (see pull request #930), the `strongbox-web-integration-tests` module for NuGet Layout Provider is failing. The following error is shown:

```
Execute command[s]: 
mono /usr/local/bin/nuget-3.4.4.exe push Org.Carlspring.Strongbox.Examples.Nuget.Mono/1.0.0/Org.Carlspring.Strongbox.Examples.Nuget.Mono.1.0.0.nupkg -ConfigFile /workspace/nuget/target/it/NuGet.config
Pushing Org.Carlspring.Strongbox.Examples.Nuget.Mono.1.0.0.nupkg to 'http://localhost:48080/storages/storage-nuget/nuget-releases'...
  PUT http://localhost:48080/storages/storage-nuget/nuget-releases/
18:23:52.259 24-11-2018 | INFO  | qtp1592099291-20     | o.c.s.users.userdetails.StrongboxUserDetailService | Authorise under SpringSecurityUser{username='admin', enabled=true, authorities (count) = 58, accessModel=null, url='null'}
18:23:52.394 24-11-2018 | INFO  | qtp1592099291-20     | o.c.s.c.layout.nuget.NugetArtifactController       | Nuget push request: storageId-[storage-nuget]; repositoryId-[nuget-releases]
0
18:23:52.428 24-11-2018 | ERROR | qtp1592099291-20     | o.c.s.c.layout.nuget.NugetArtifactController       | Failed to process Nuget push request: storage-nuget:nuget-releases
org.apache.commons.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly
	at org.apache.commons.fileupload.MultipartStream.readHeaders(MultipartStream.java:540)
	at org.carlspring.strongbox.controllers.layout.nuget.NugetArtifactController.writePackagePart(NugetArtifactController.java:626)
	at org.carlspring.strongbox.controllers.layout.nuget.NugetArtifactController.extractPackageMultipartStream(NugetArtifactController.java:588)
	at org.carlspring.strongbox.controllers.layout.nuget.NugetArtifactController.putPackage(NugetArtifactController.java:438)
	at org.carlspring.strongbox.controllers.layout.nuget.NugetArtifactController$$FastClassBySpringCGLIB$$ebeabea.invoke(<generated>)
[...]
  InternalServerError http://localhost:48080/storages/storage-nuget/nuget-releases/ 347ms

gave the following error: 
[ERROR] 500 (Server Error)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

This error is happening at `NugetController#putPackage#extractPackageMultipartStream#writePackagePart `method.

The error, `org.apache.commons.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly`, is related to `commons-fileupload` library, and it's already registered in Apache JIRA, still unresolved: 
[https://issues.apache.org/jira/browse/FILEUPLOAD-265](https://issues.apache.org/jira/browse/FILEUPLOAD-265)

All this could be happening because of the upgrade of Spring Boot related dependencies too. This is the [table](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html) of dependency versions.

We need to resolve this error.

The sources for the `strongbox-web-integration-tests` can be found [`here`](https://github.com/strongbox/strongbox-web-integration-tests/). It would be easier to run these tests with `docker-compose`.

The Spring Boot upgrade didn't upgrade the version of the `commons-upload` (`1.3.3`), or `httpclient` (`4.5`) dependencies. It's quite likely that one of the transitive dependencies of these two are no longer working properly and we might need to consider upgrading the `commons-upload`, or `httpclient`, or play around with their transitive dependencies.

**Comment by carlspring** [comment]
Upgrading `httpclient` to `4.5.6` doesn't seem to help.

**Comment by carlspring** [comment]
Downgrading `commons-fileupload` to `1.3.2` didn't help either.

**Comment by carlspring** [comment]
@ptirador : Should we consider reverting the Spring Boot upgrade, until we've been able to figure this out?

**Comment by ptirador** [comment]
Yes, I agree. We can revert it.

**Comment by sbespalov** [comment]
seems that this issue related with Jetty version which was updated in `spring-boot` v.2.1.0 from **9.4.11* to **9.4.12**.
with new Jetty version it can't read bytes from request stream in `NugetArtifactController.putPackage`, and `ServletRequest.getInputStream()` always read 0 bytes.

**Comment by carlspring** [comment]
Relates to #1023.

**Comment by carlspring** [comment]
@sbespalov , @ptirador , @fuss86 ,

Could we now close this?

**Comment by ptirador** [comment]
@carlspring: In my opinion, yes, we could.

**Comment by carlspring** [comment]
@sbespalov , 

Please confirm! :)

**Comment by sbespalov** [comment]
confirmed
this was resolved with `spring.servlet.multipart.enabled=false`
