### ISSUE TITLE
Make the strongbox-storage-nuget-layout-provider's tests work in parallel

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#947]
# Task Description

The test cases in this module are taking quite a long time, as they're all running consecutively.

With our upgrade of JUnit to JUnit5 (handled by @ptirador in #871), we now have the means to further fine-tune the parallelization of our tests.

* [x] Each test method of each test must now take care of creating its own test resources and not rely on them to be created by a common test initialization method, or other test methods.
* [x] Test cases which require a repository, should create the repository in each test method and not rely on them to be created by a common test initialization method, or other test methods.

# Task Links

* This is a sub-task of #839.
* For reference of how things should be done, you can have a look at #936. 
* This task depends on #1083, #1084.

**Comment by carlspring** [comment]
Re-opening, due to failing tests.

**Comment by ptirador** [comment]
HI, I'd like to work on this.

**Comment by carlspring** [comment]
Great! Feel free to dig in!
