### ISSUE TITLE
Make the strongbox-storage-npm-layout-provider's tests work in parallel

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#948]
The test cases in this module are taking quite a long time, as they're all running consecutively.

With our upgrade of JUnit to JUnit5 (handled by @ptirador in #871), we now have the means to further fine-tune the parallelization of our tests.

* [ ] Each test method of each test must now take care of creating its own test resources and not rely on them to be created by a common test initialization method, or other test methods.
* [ ] Test cases which require a repository, should create the repository in each test method and not rely on them to be created by a common test initialization method, or other test methods.

This task is a sub-task of #839. For reference of how things should be done, you can have a look at #936.

**Comment by carlspring** [comment]
Re-opening, due to random test failures.

**Comment by ptirador** [comment]
@carlspring : Currently there are 3 tests in this module:

`org.carlspring.strongbox.artifact.coordinates.NpmArtifactCoordinatesTest`
`org.carlspring.strongbox.cron.jobs.FetchChangesFeedCronJobTestIT`
`org.carlspring.strongbox.dependency.snippet.NpmDependencyFormatterTest`

All of them have an `@Execution(CONCURRENT)` annotation, and they're all working.
Should we mark this as done?

**Comment by carlspring** [comment]
In the junit properties file, is the setting for parallel tests enabled?

**Comment by ptirador** [comment]
Yes, it is:
strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/resources/junit-platform.properties

**Comment by carlspring** [comment]
@ptirador : 

Please, feel free to close this, if you think it's now working properly!

Thanks! :)

**Comment by carlspring** [comment]
Thanks! :)
