### ISSUE TITLE
Fix the JWT test issues in the SpringSecurityTest

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#956]
Tests methods to be re-written in the `SpringSecurityTest`:
* [ ] `testJWTAuth()`
* [ ] `testJWTExpire()`

**Comment by kdpapado** [comment]
Hi @carlspring! Could you please explain what's the problem with these test methods?

**Comment by carlspring** [comment]
Hi, @kdpapado!

Thanks for offering to help! It seems like one of our core developers (@sbespalov) will be taking this one. Would you like to join our [chat](https://chat.carlspring.org/], so that we could discuss some other issues, that you oculd perhaps help out with...?

**Comment by kdpapado** [comment]
Thank you @carlspring ! Are there open issues available for beginners? I am new in GitHub world and I'm looking for a way to do my first contribution. I 'd prefer to contribute in code (something easy like this issue) for the beginning!

**Comment by carlspring** [comment]
Yes, there are quite a few. Please, join our chat and we'll discuss it there.

**Comment by adavid9** [comment]
I can work on that one.

**Comment by carlspring** [comment]
@adavid9 : Could you actually hang on with this one? I think @steve-todorov , @sbespalov and @fuss86  will have to clarify the requirements for this one in particular. (Sorry!).

**Comment by steve-todorov** [comment]
I think we are already doing this partially in the `LoginControllerTest`. We will probably just need to add an `JWT expiration` test which confirms expired tokens are not permitted. @sbespalov what do you think? :)

**Comment by sbespalov** [comment]
@steve-todorov as I see there is no JWT related test cases in `LoginControllerTest`.

@carlspring @adavid9 regarding this issue we probably should expose `SpringSecurityTest.testJWTAuth()` and `SpringSecurityTest.testJWTExpire()` methonds into new test class `JwtAuthenticationTest.
Also `/api/users/user/authenticate` should be changed to `/api/login`.

**Comment by sbespalov** [comment]
the `/api/users/greet` probably can be also changed to `/api/users/{username}`

**Comment by adavid9** [comment]
@sbespalov Okay, so I will create a new separate class where I will test these methods you mentioned above.

**Comment by carlspring** [comment]
The `/api/users/greet` path was just for some testing a previous developer did a very long time ago. I think this should be removed.

**Comment by steve-todorov** [comment]
I agree with @carlspring , I don't think we need the `/api/users/greet` anymore.
