### ISSUE TITLE
Separate the endpoints for adding and updating storages

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#958]
Currently, the `StoragesConfigurationController` is using the same route for both actions and acts does `add or update` based on whether or not the storage exists in the database or not.  We need to have separate endpoints for these actions, because the following issues arise with it:

1. Unable to update an existing storage's `id`
2. Unable to display a `duplication error` to the user when creating a `new` storage with an `id` which already exists

This is why we need to separate the `PUT /api/configuration/strongbox/storages` into the following endpoints:

1. `PUT /api/configuration/strongbox/storages` - creates a new storage and:
    * Enforces `duplication` check - if the storage `id` or `basedir` are already in use, saving the form should return the appropriate form error
    * The storage `id` and `basedir` are both required and **must not** be empty or null
2. `PUT /api/configuration/strongbox/storages/STORAGE_ID` - updates an existing storage and:
    * The validation will be the same as when creating, but **must** allow updating the *same* storage. When the user `edits` an existing storage from the UI, the form will contain the storage `id` and `basedir`. He might not update the `id`, but the submitted JSON to the backend **will** contain it. In other words, the validation logic should be something like this:
        ```
        if(STORAGE_ID !== SUBMITTED_ID && exists(STORAGE_ID)) 
           isValid = false 
        }
        ```
    * We have a similar scenario for the `UserController` (`UserForm`) which can be used as an example.
3. Currently, there is no success/failed messages returned from upon adding/updating a storage. Please add the respectful message for the add / update actions by using `getSuccessfulResponseEntity(...)` or `getFailedResponseEntity(...)`.

While working on this task:

* Be sure to follow our [How To Implement Spring Controllers](https://github.com/strongbox/strongbox/wiki/How-To-Implement-Spring-Controllers) rules
* Feel free to join in our chat and ask questions! [![RocketChat.Community.Channel](https://chat.carlspring.org/images/join-chat.svg)](https://chat.carlspring.org/channel/community)

**Comment by hexadecimal16A** [comment]
Hey, I want to work on this.

**Comment by carlspring** [comment]
Hi!

Okay, feel free to pick it up!

**Comment by steve-todorov** [comment]
@hexadecimal16A Hi, Have you already started working on this? :)

**Comment by carlspring** [comment]
If not, @ptirador , would you like to maybe pick it up?

**Comment by hexadecimal16A** [comment]
Yes, please pick it up.

On Jan 7, 2019 21:54, "Martin Todorov" <notifications@github.com> wrote:

If not, @ptirador <https://github.com/ptirador> , would you like to maybe
pick it up?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/strongbox/strongbox/issues/958#issuecomment-451991485>,
or mute the thread

**Comment by ptirador** [comment]
Yes, I'll take it.
