### ISSUE TITLE
Enable LdapAuthenticatorConfigurationControllerTest.ldapConfigurationTestShouldFailWithWithInvalidManagerDn()

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#960]
# Task Description

Currently this test is disabled because the `ManagerDN` doesn't work as expected in unit tests. 

What to do:
- Find out how to disable anonymous access for Embedded Open LDAP server configured in `ldapServerApplicationContext.xml`
- Configure proper `ManagerDN` credentials in `strongbox.ldif`

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by anki2189** [comment]
@carlspring We can close this now, this was fixed in https://github.com/strongbox/strongbox/pull/1670

**Comment by carlspring** [comment]
Thanks for following up on this!
