### ISSUE TITLE
Exclude JUnit 4.x from the project dependencies

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#992]
Since we upgraded to junit 5.X (see #616, #667, #803) we should exclude all possible transitive dependencies to junit 4.X so for example `org.junit.Test` will no longer be accessible in the project.

**Comment by efedchen** [comment]
I will take it

**Comment by fuss86** [comment]
Great, assign it to yourself, please :)

**Comment by carlspring** [comment]
@efedchen , what is the status of this task?
Can we close it?

**Comment by ptirador** [comment]
@carlspring: This issue can be closed.

**Comment by carlspring** [comment]
Thanks! :)
